---
mqtt:
  host: mosquitto.home
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: False

# Global objects configuration
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

# Global ffmpeg configuration
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - warning
  hwaccel_args:
    - -c:v
    - h264_qsv
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac

# Global rtmp configuration
rtmp:
  enabled: true

# Global snapshots configuration
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 7

# Global record configuration
record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 15
    retain:
      default: 10
      mode: active_objects

# Specify camera's
cameras:
  doorbell:
    # Camera-specific ffmpeg configuration
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_CAMERA_DOORBELL_USER}:{FRIGATE_CAMERA_AMCREST_PASSWORD}@{FRIGATE_CAMERA_DOORBELL_HOST}:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - rtmp
            - record
        - path: "rtsp://{FRIGATE_CAMERA_DOORBELL_USER}:{FRIGATE_CAMERA_AMCREST_PASSWORD}@{FRIGATE_CAMERA_DOORBELL_HOST}:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
    objects:
      track:
        - person
        - car

    # Camera-specific detection configuration
    detect:
      width: 960
      height: 720
      fps: 10

    # Camera-specific recording configuration
    record:
      retain:
        days: 15
        mode: all
      events:
        retain:
          default: 30

    # Camera-specific snapshots configuration
    snapshots:
      retain:
        default: 30
        
  lr:
    # Camera-specific ffmpeg configuration
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_CAMERA_LR_USER}:{FRIGATE_CAMERA_AMCREST_PASSWORD}@{FRIGATE_CAMERA_LR_HOST}:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - rtmp
            - record
        - path: "rtsp://{FRIGATE_CAMERA_LR_USER}:{FRIGATE_CAMERA_AMCREST_PASSWORD}@{FRIGATE_CAMERA_LR_HOST}:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect

    # Camera-specific detection configuration
    detect:
      width: 960
      height: 720
      fps: 5

    # Camera-specific recording configuration
    record:
      events:
        retain:
          default: 14

    # Camera-specific snapshots configuration
    snapshots:
      retain:
        default: 14

  crawlspace:
    # Camera-specific ffmpeg configuration
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_CAMERA_SUMP_USER}:{FRIGATE_CAMERA_SUMP_PASSWORD}@{FRIGATE_CAMERA_SUMP_HOST}:554/live"
          roles:
            - rtmp
            - record
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - bear
        - sheep

    # Camera-specific detection configuration
    detect:
      width: 960
      height: 720
      fps: 5

    # Camera-specific recording configuration
    record:
      events:
        retain:
          default: 14

    # Camera-specific snapshots configuration
    snapshots:
      retain:
        default: 14
