---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v7.0.25

    env:
      TZ: America/New_York

    service:
      main:
        type: LoadBalancer
        annotations:
          coredns.io/hostname: unifi
        loadBalancerIP: "${LB_UNIFI_IP}"
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918-ips@kubernetescrd

        hosts:
          - host: "unifi.${DOMAIN_2}"
            paths:
              - path: /

        tls:
          - secretName: unifi-controller-tls
            hosts:
              - unifi.${DOMAIN_2}

    persistence:
      data:
        enabled: true
        existingClaim: unifi-data

    resources:
      requests:
        cpu: "25m"
        memory: "1024M"
      limits:
        memory: "1536M"