apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unifi
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m

  values:
    global:
      nameOverride: *app
    image:
      repository: jacobalberty/unifi
      tag: v7.1.68

    env:
      TZ: America/New_York
      # -- Run UniFi as root
      RUNAS_UID0: "false"
      # -- Specify the user ID the application will run as
      UNIFI_UID: "999"
      # -- Specify the group ID the application will run as
      UNIFI_GID: "999"
      # -- Java Virtual Machine (JVM) initial, and minimum, heap size
      # # Unset value means there is no lower limit
      # JVM_INIT_HEAP_SIZE:
      # -- Java Virtual Machine (JVM) maximum heap size
      # For larger installations a larger value is recommended.
      # For memory constrained system this value can be lowered.
      JVM_MAX_HEAP_SIZE: 1024M
      # # -- External MongoDB URI
      # DB_URI:  # mongodb://unifi-mongodb:27017/unifi
      # STATDB_URI:  # mongodb://unifi-mongodb:27017/unifi_stat
      # DB_NAME:  # unifi

    service:
      main:
        type: LoadBalancer
        annotations:
          coredns.io/hostname: unifi
        loadBalancerIP: "${LB_UNIFI_IP}"
        externalTrafficPolicy: Local
        ports:
          # -- Configure Web interface + API port
          # @default -- See values.yaml
          http:
            enabled: true
            port: 8443
            protocol: HTTPS
          # -- Configure Controller port used for device command/control
          # @default -- See values.yaml
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          # -- Configure Captive Portal HTTP port
          # @default -- See values.yaml
          portal-http:
            enabled: false
            port: 8880
            protocol: HTTP
          # -- Configure Captive Portal HTTPS port
          # @default -- See values.yaml
          portal-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          # -- Configure Speedtest port (used for UniFi mobile speed test)
          # @default -- See values.yaml
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          # -- Configure STUN port
          # @default -- See values.yaml
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          # -- Configure remote syslog port
          # @default -- See values.yaml
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          # -- Configure device discovery port
          # @default -- See values.yaml
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918-ips@kubernetescrd

        hosts:
          - host: "unifi.${DOMAIN_2}"
            paths:
              - path: /

        tls:
          - secretName: unifi-controller-tls
            hosts:
              - unifi.${DOMAIN_2}
            

      # # -- Enable and configure settings for the captive portal ingress under this key.
      # # @default -- See values.yaml
      # portal:
      #   enabled: false
      #   annotations:
      #     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

      #   ingressClassName:  # "nginx"

      #   hosts:
      #     -  ## Host address. Helm template can be passed.
      #       host:
      #       ## Configure the paths for the host
      #       paths:
      #         -  ## Path. Helm template can be passed.
      #           path: /
      #           ## Ignored if not kubeVersion >= 1.14-0
      #           pathType: Prefix
      #           service:
      #             ## Overrides the service name reference for this path
      #             name: main
      #             ## Overrides the service port reference for this path
      #             port: portal-https

    persistence:
      data:
        enabled: true
        existingClaim: unifi-data
        mountPath: /unifi
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/k8s-bak/unifi
        mountPath: /var/lib/unifi/backup
        readOnly: false

    resources:
      requests:
        cpu: "25m"
        memory: "1000Mi"
      limits:
        memory: "1400Mi"