---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/instance: navidrome
    app.kubernetes.io/name: navidrome
  name: navidrome
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system  
      interval: 15m

  values:
    image:
      repository: ghcr.io/onedr0p/navidrome
      tag: 0.49.3@sha256:5ce3d0c20b1c8bac22f8644edf18e4fd85a49fc41f1c9ad07171a1625dc2a21b

    env:
      ND_DATAFOLDER: /data
      ND_SESSIONTIMEOUT: 48h
      ND_PORT: "4880"
      ND_ENABLESTARRATING: "false"
      ND_LOGLEVEL: info
      ND_MUSICFOLDER: /music
      ND_SCANSCHEDULE: "@every 1h"
      ND_LISTENBRAINZ_ENABLED: "false"
      ND_LASTFM_ENABLED: "true"
      ND_PROMETHEUS_ENABLED: "true"

      # ND_LASTFM_APIKEY: 
      # ND_LASTFM_SECRET: Last.fm Shared Secret
      # ND_UILOGINBACKGROUNDURL: URL
      # ND_SPOTIFY_ID: ID
      # ND_SPOTIFY_SECRET: Spotify Client ID

    ingress:
      main:
        enabled: false
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "headphones-box"
        hosts:
        - host: &host "music.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host

    persistence:
      config:
        enabled: true
        existingClaim: navidrome-config
        mountPath: /data
      old:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/Media/Music/Old
        mountPath: /music/old
        readOnly: true
      new:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/Media/${SECRET_NEW_MUSIC}
        mountPath: /music/new
        readOnly: true
      classical:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/Media/Music/Classical
        mountPath: /music/Classical
        readOnly: true

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100

    resources:
      requests:
        cpu: 15m
        memory: 145M
      limits:
        memory: 215M

    service:
      main:
        ports:
          http:
            port: 4880
