---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: excalidraw-room
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: docker.io/excalidraw/excalidraw-room
      tag: sha-49bf529

    env:
      TZ: "${TIMEZONE}"
      PORT: &port 3002

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: false
        # ingressClassName: nginx
        # hosts:
        #   - host: &host "{{ .Release.Name }}.${DOMAIN_1}"
        #     paths:
        #       - path: /
        #         pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host

    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        memory: 500Mi
