---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: registry.${DOMAIN_1}/testproj/excalidraw
      tag: test
      pullPolicy: Always

    env:
      TZ: "${TIMEZONE}"
      PUB_SRV_NAME: draw.${DOMAIN_1}
      PUB_SRV_NAME_WS: draw-collab.${DOMAIN_1}
      VITE_APP_BACKEND_V2_GET_URL: https://draw.${DOMAIN_1}/api/v2/
      VITE_APP_BACKEND_V2_POST_URL: https://draw.${DOMAIN_1}/api/v2/post
      VITE_APP_WS_SERVER_URL: https://draw-collab.${DOMAIN_1}

      # set this only if using the collaboration workflow we use on excalidraw.com
      VITE_APP_PORTAL_URL: ""
      

    service:
      main:
        ports:
          http:
            port: &port 80

    ingress:
      main:
        enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      # limits:
      #   memory: 1000Mi
