---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: registry.${DOMAIN_1}/testproj/excalidraw
      tag: test
      pullPolicy: Always

    env:
      TZ: "${TIMEZONE}"
      NODE_ENV: development
      # VITE_APP_BACKEND_V2_GET_URL: https://draw.${DOMAIN_1}/api/v2/
      # VITE_APP_BACKEND_V2_POST_URL: https://draw.${DOMAIN_1}/api/v2/post
      # VITE_APP_WS_SERVER_URL: http://excalidraw-room.home.svc.cluster.local:3002
      # VITE_APP_WS_SERVER_URL: https://draw-collab.${DOMAIN_1}
      COLLAB_ADDR: https://draw-collab.${DOMAIN_1}
    command: "/bin/ash"
    args:
      - -c
      - "sed -i s,http://localhost:3002,$COLLAB_ADDR,g /usr/share/nginx/html/assets/*.js && /docker-entrypoint.sh nginx -g 'daemon off;'"
      
    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      # limits:
      #   memory: 1000Mi
