---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:

    controllers:
      main:
        replicas: 1
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/ryan-mcd/excalidraw-collab
              tag: "0.0.3237"
            env:
              TZ: "${TIMEZONE}"
              COLLAB_ADDR: https://draw-collab.${DOMAIN_1}
            resources:
              requests:
                cpu: 100m
                memory: 50Mi
              limits:
                memory: 50Mi
  
      room:
        replicas: 1
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/ryan-mcd/excalidraw-room
              tag: 0.0.82
            env:
              TZ: "${TIMEZONE}"
              PORT: &room-port 3002
            resources:
              requests:
                cpu: 100m
                memory: 75Mi
              limits:
                memory: 75Mi

    service:
      main:
        ports:
          http:
            port: 8080
      room:
        # nameOverride: excalidraw-room -> creates service named excalidraw-excalidraw-room
        controller: room
        ports:
          http:
            port: *room-port

    ingress:
      main:
        enabled: false
        # ingressClassName: nginx
        # hosts:
        #   - host: &host "{{ .Release.Name }}.${DOMAIN_1}"
        #     paths:
        #       - path: /
        #         pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host

