---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/ryan-mcd/excalidraw-collab
      tag: "0.0.3111"
      pullPolicy: Always

    env:
      TZ: "${TIMEZONE}"
      COLLAB_ADDR: https://draw-collab.${DOMAIN_1}
       
    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        enabled: false
        # ingressClassName: nginx
        # hosts:
        #   - host: &host "{{ .Release.Name }}.${DOMAIN_1}"
        #     paths:
        #       - path: /
        #         pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host

    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        memory: 500Mi
