---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-nas-pv
spec:
  storageClassName: media-nas
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDRESS}
    path: /mnt/user/Media
  mountOptions:
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-nas-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-nas
  resources:
    requests:
      storage: 1Mi
