---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 2
    nfs:
      server: "10.11.1.111"
      path: "/mnt/user/PersistentVolumeClaims"
      mountOptions:
        - noatime
    storageClass:
      defaultClass: false
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
      onDelete: retain
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nfs-subdir-external-provisioner
              topologyKey: kubernetes.io/hostname
