# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: loki-secrets
    namespace: flux-system
stringData:
    S3_BUCKET_HOST: ENC[AES256_GCM,data:LmX16LOeJUw7DT3Ac6Xz,iv:2zIIC/BUcNqs6nJQT/xvbFButJ1sWbgboQcye7zIOL0=,tag:yGyf5CThoMlAg0ZwAeVlQA==,type:str]
    S3_BUCKET_REGION: ENC[AES256_GCM,data:53UfJSO+dkHa,iv:lIgddwHufoFoIXu3OOqJa7Dbi5EGWM4EZvwatctx3ek=,tag:41/xduWtxZRoVDaf/VggmA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:d6VsZM7Q6mnyISpicoAiLg==,iv:m2cTtwvND25vCPbkr6VNcTrSOZbwcq1x10a8O2OxNRk=,tag:Mm6Eqy/nDbFK1LK34g/Lyw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:e+JGtLEwTlmxxQI6KRC0BaE030HfHS7rfb5TeplSsnM=,iv:73RLMgfOLCVU6cK4nngTgN0bijuBtKvYyahO7OCjpuE=,tag:kB039+rDV7+XEoDrVsQDEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2024-01-04T21:35:28Z"
          enc: vault:v1:tGf7sCkr/VL0g0tYnqqfDxW5l/4/fvDuYEEqbB7gDEq8y02QfYoBuCJk+2hz+kYhHVT/FAxDeCKrqO4l
    age:
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdmJvaWFxQTdNL293aHM0
            UjV5bzJMa3duQUFxSUhUbndUazBOVHF3WkdBCnhFc1VzdnhnanducVc1ejR2S0lt
            ZVpiUUdaTmJ3bkE3THF5U3U5ZmUyZk0KLS0tIEMwYUYzVU9kb0FCaWZpVFFHUzdJ
            ZlZqYzQrUThGTzFUWERpL3cyR3Q5SmcKhsiy9ElGJCFkhQ3/mYK4uktaKcW9H1zR
            +BNPAfEpNNjqafzpX+oF1iT0VvWc3LK49RZnOJ1zJN7WsfJHEO8ZCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cFhCNkhURlkxNSswUFd0
            aUJYeUZQQitCTTFUWlpOM2pvc05WaFR6d1dVCkIxV0thc29JNGszTFFIc0lPcVVi
            MlBxbnVVTGZBclN5QUwvU29udW5aa3cKLS0tIHJraWlxSVo0bFNKMHVCR1VZSjZv
            TTFSOUU2cG1VRFNQeU9tL1I4aDg1eHMK3YmNP1Axtdnj254x5TG8JM0i/uyYDuSo
            q0pRONjjYFhR5tKeLex8QLlqj8KgLLh8VoYdQWONOesvro28HbUwSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N0xtUGlGVmNjNWcwbGJN
            eGxMbnlJcGp0b3BLSE4xZ2VTc0xyaXRwdDNjCnZCZFBqVXdEUzQ0cEhBdXVMRWlV
            eUpNUUNCSWhtd1lNU1NUVmhDc1NwMDgKLS0tIGFWYlBkQ0tISU9lSy82ZDI3REVs
            VFlZSkltSXNvdzlIbEVMNVNGejB5dlkKbGSE68gBkjbDySAdwtf4kyWBW9xa8+2q
            Zvzu95Nv8rcI4iWrvwDRkwAp7D6ICWL+UdO4Ef4s2VMXTGOyuAmuxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T22:00:25Z"
    mac: ENC[AES256_GCM,data:m9EjfiTLDCXjD8+FzSCJ1y7M9CILvjDfP9m1LXZyb93vXYTXhAHUNG+oHMlQj6oSsFqYV5kjwQcTTWIZ/VKlzIYtQuj9nzdD+f13tPCoLdJHX66m0cCqNGxvzPe12L9SsvA4GO01CQ9VKRMs8aN4W/Y7cvqlaKVgsxVjdXftDfw=,iv:CCZDue8dW0JQUSCE6O/+tq5RFZLruzlNxQi0W8rJNpc=,tag:olxTmTIjVCbl/BvTx3SMcQ==,type:str]
    pgp:
        - created_at: "2024-01-04T21:35:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//SmbfjltDIrHZvvqngCGTtOcX991xIWf8wo16jAPWJX0f
            8/NAtOHukktlpjxQoKzn93RgBnY9UY1et9Wt9RZNENEzj7K9fihd38ehLsnkMeRO
            iNWClB8lsV8MyF3p1ekVrsRBic31ns2FBpwNp0apPT05nB6UffPaDSfzM7LCCt+4
            8LhSzui3osX/6dJl9165VBDM+i1fcrVTOyElXLdszBVMMZk5kU0ENsh0slMzNzMD
            ou6KmSyqq33T+56UAjnFu6NXIieeHv4U+UVDslUpzims8/Xp/oQSbtxEy9otg3i2
            CwuyLPif1C6ONw2kG08ToeLk2UceehK1WdYV4/DCFs+KEHuuSGx8Fm2KlQlplsXu
            BuC9F39ZiiZ6qIIQ74VYh4C1MO1Am9JiunNRX0ZkcSts+70m05gV2tLTwlzUDdK4
            JuKR6LpT63ixB6+9zC6bNUfeLvE6BFogZjlrooVokf+glNOEWkHVhtToqyDHctaq
            BC4HXyvcfYE4XINJ8oOlew6ky90LUWw9lDUH45fQUMLN2PXTLpv8Ytx0/ErWEPyq
            zX1doHrYWEl4j2XJ5MhYXxnN21CUTDv33JMhBa+oa8cNpug8d/yWXy97c6lK7h84
            fmnxEAY/Co+M95OClimD3sn6mIKNbGknWgc8ywip1IgD+D4ZkgvrQk7BDAQ0cNHS
            XgG9deRskLgyN6XJakw89fHUfcEhDGoAlBFw7yXae1znRDPEDuA7wuX0TlVi2QVH
            an6V5602bNpnGZ9t2poAbJQjucLUCYqkbVsFSsL2ApwaP8h9c5VGWsMVVk1pLhc=
            =LRew
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2024-01-04T21:35:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ//SNedaT6z9CCP3HYSK/qu+PdcWvn9b44c4rz6upOkUoai
            o4Nub2kXr1b5TwHghGrntGZYskxQUq5c6tymqeV8OvxvD9ZEqcEwq6CyXLedqrS9
            vQK4xqibzGIDPLW+Bfq32q8OxirNreog9U7KZZFW266m2sClJwIIF3hg/9jFRWwr
            gd2I/5NKFAUcCUzfLMt4Zzk2DtYSAQQM/oC1JqEbKtcsfrAUT9uCiKwaZfdbnvmS
            Uak2Sle3X+c0LoEE9cGC7HP7xlH7CriJvTrtUetuCD5evrQhD/Svn/FBkEbZ5Z3j
            m1pwI+Y1WNBwhDkWtmA0/xZ+7nXE4ryQljcVoE+bwRKuHaijhhsCcIdiQt/i4q0s
            +gcybh53MXdiFhtBmjUELZbn11wuAIdIwMif3BvxJbFri6rEzYna1SFERNcOgo3M
            u7w2lx8nzNp2kngWkv4VHfjuGHC5KHJ49YQusA4XowS2zMJ//jqTxEUfV2JUH9kS
            +r44deNABMQzkmjqrUE4NLFE6cr72f7oOahNHKChyi3IH3t0qilHPvYw+6yYrsQ1
            InoTmBPacA+IQ5kbxKANYloA+IKIbZtz9Xe6XjICZmwn9Sp59nnPNjm5PVyiVW5+
            j7M1ZsTpuzhZ+9rvg5lic3NhtYoPgmacfZABoDyajP/FGkuO4vqzeAUo/EXVCl/S
            XgGvNJV+5tcmKbXVlkvLL15dJWzc1v5FtBzRn0QVLv+eYga2vn6bO8pr/OVvHFeJ
            eNpqURx76IdbAdKBpdjKSBcJ2/FknaI+ubzp5qOwls8XZetxV+YJq/TjQCsj+sc=
            =rwrF
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2024-01-04T21:35:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAAokub/Sq3AHoYzsJ6tZ/qTNYaNlC9PeSDbg3GpTCFNgYu
            Wvzc7dF+KaM18t1CHKcaMbUDxYLETnXBUFuyTGb99BhXpeg69/qlxs0pm20uUiTq
            /dfXj10b63IK6MELmhjfxJsMPZhRBJc2tnyu9GxP3a4PEqUu80zz5k3nKU420UDL
            a4xulnlZjPqhRjP4dMVW+7vf/bZ/dX/dh2HjFdQ8yo0oKIDZ/9slLSiN4+jLbXr8
            3bMAXTaAigqsLONZ8+7inCV4JmE4xX3bl69/yyc37WNd/QhzlrTYH/ktwtRUxmrG
            8+ohND1biyB7zXx14/gVmMvth1sQUv1MBZ+ivPuivjLW021q89sjlvcuDmSJrx3X
            18K4qnGZtyWsN1edSbzww4XFt0/nXPTQv6GVlWuOXpjcGKzzq+xEy1WF+rqHZjvF
            oOjC7BZvBNbgZFwt58LTlrYKoNg9dLR1TLXPkh/Bu5LpMjsezrLcAfE1dQuMZGEx
            COGYLDQu2WrdRoNJ8z6jgH8X8xTbaxnap4EMgZtRURRqziDTch0NKEwS6kUYGQE2
            ULU+8+3Wf0+XoONl8il6R6FCQuFCkuB8RMbuuzBqY6cWXJaVGtYOQrMPUJvXx2Rm
            UCJPucp7QqOGP1NkbA1aDciXwZRsuppFnnfh33u7GmBsV3h6LE4NlgP/ikJacbXS
            XgGuVjanb7sP77dE0PdBTByCO5A4nKSjyBJm1j046Yr4jm22biqi+a4O2Q24FAu4
            XoMJAHbE0CeqPg56vCRMjn39E+C1f6llW653MkUzUzzOdfBbOwNTSRvrX02erJk=
            =P9VG
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
