---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web
  # - maintenance
  # - sync
namespace: services
configMapGenerator:
  - name: kopia
    files:
      - repository.config
generatorOptions:
  disableNameSuffixHash: true
