---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-ips-secure-headers
  namespace: networking
spec:
  chain:
    middlewares:
    - name: cloudflare-ips
    - name: secure-headers