---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudflare.yaml
- external-auth.yaml
- internal-auth.yaml
- secret.enc.yaml
- basic-auth.yaml
- rfc1918.yaml
- longhorn-headers.yaml
- longhorn-tls.yaml
- nextcloud-regex.yaml
- nextcloud-tls.yaml
- plex-redirect.yaml
- secure-headers.yaml
- cloudflare-secure-headers.yaml
