---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nc-tls
  namespace: networking
spec:
  chain:
    middlewares:
    - name: rfc1918
    # - name: cloudflare-ips
    # - name: svc-nc-regex