apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: svc-plex-redirect
  namespace: networking
spec:
  redirectRegex:
    regex: "^(http|https)://plex.${SECRET_DOMAIN}/"
    replacement: "https://plex.${SECRET_DOMAIN}/web/"
    permanent: true