apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name:  airsonic
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m

  values:
    image:
      repository: ghcr.io/kagemomiji/airsonic-advanced
      tag: edge-11.1.3-SNAPSHOT.20230825142534
      pullPolicy: IfNotPresent
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      # Run Once for /var/airsonic/transcode permissions issues      
      fsGroup: 2000
      # fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 100
      - 65540
    env:
      TZ: "America/New_York"
      JAVA_OPTS: "-Xms256m -Xmx512m -Dserver.forward-headers-strategy=native -Dserver.servlet.session.timeout=2880m"
    enableServiceLinks: false
    persistence:
      config:
        enabled: true
        existingClaim: airsonic-config-v1
        mountPath: /var/airsonic
      podcasts:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/airsonic_podcasts
        mountPath: /var/podcasts
        readOnly: false
      old:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/Media/Music/Old
        mountPath: /var/music
        readOnly: true
      new:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/Media/${SECRET_NEW_MUSIC}
        mountPath: /var/new
        readOnly: true
      classical:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/Media/Music/Classical
        mountPath: /var/Classical
        readOnly: true
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/k8s-bak/airsonic-backup
        mountPath: /var/airsonic/backups
        readOnly: false

    service:
      main:
        ports:
          http:
            port: 4040
    ingress:
      main:
        enabled: false
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "headphones-box"
        hosts:
        - host: &host "as.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
    resources:
      requests:
        memory: "1500Mi"
      limits:
        memory: "2000Mi"

    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /rest/ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /rest/ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      startup:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /rest/ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 30