---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster3
  namespace: staging-vcluster3
spec:
  interval: 15m
  chart:
    spec:
      chart: vcluster
      version: 0.15.6
      sourceRef:
        kind: HelmRepository
        name: loft-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  # kubectl get secret vc-my-vcluster -n test --template={{.data.config}} | base64 -d
  values:
    vcluster:
      image: ghcr.io/ryan-mcd/k3s-nfs-1.25:v1.25.12-k3s1
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 256Mi

    sync:
      nodes:
        enabled: true
        syncAllNodes: true
      ingresses:
        enabled: true

    # Enable HA mode
    enableHA: false
    replicas: 1
    # Storage settings for the vcluster
    storage:
      persistence: true
      size: 5Gi
      # # Optional StorageClass used for the pvc
      #className:
    # Scale up syncer replicas
    syncer:
      replicas: 1
      extraArgs:
        - --tls-san=vcluster3.${DOMAIN_2}
        - --out-kube-config-server=https://vcluster3.${DOMAIN_2}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    # Scale up controller manager
    controller:
      replicas: 1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    # Scale up api server
    api:
      replicas: 1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    # Scale up DNS server
    coredns:
      replicas: 1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          cpu: 100m
          memory: 170Mi
        requests:
          cpu: 3m
          memory: 16Mi

    isolation:
      enabled: true

      podSecurityStandard: baseline

      resourceQuota:
        enabled: true
        quota:
          requests.cpu: 2
          requests.memory: 20Gi
          requests.storage: "100Gi"
          requests.ephemeral-storage: "60Gi"
          limits.cpu: 4
          limits.memory: 40Gi
          limits.ephemeral-storage: "160Gi"
          services.nodeports: 20
          services.loadbalancers: 2
          count/endpoints: 40
          count/pods: 30
          count/services: 40
          count/secrets: 100
          count/configmaps: 100
          count/persistentvolumeclaims: 20
        scopeSelector:
          matchExpressions:
        scopes:

      limitRange:
        enabled: true
        default:
          # ephemeral-storage: 2Gi
          memory: 512Mi
          cpu: "300m"
        defaultRequest:
          # ephemeral-storage: 1Gi
          memory: 128Mi
          cpu: 100m

      networkPolicy:
        enabled: false
        outgoingConnections:
          ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 100.64.0.0/10
              - 127.0.0.0/8
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16

    # service:
    #   type: LoadBalancer
    #   loadBalancerIP: ${LB_VCLUSTER_IP}
    ingress:
      enabled: false
    telemetry:
      disabled: "true"
      instanceCreator: "helm"
      instanceCreatorUID: ""

    # securityContext:
    #   runAsUser: 12345
    #   runAsNonRoot: true
