---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dev-nas-pv
spec:
  storageClassName: development-nas
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDRESS}
    path: /mnt/user/gitea-pvc
  mountOptions:
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-v1
  namespace: development
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: development-nas
  resources:
    requests:
      storage: 10Gi
