---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m

  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/tautulli
              tag: 2.15.1@sha256:2d5a1bce27a8e29e287aec1735001e68fc23dea08806c7124587cdbfaf0ddcff
            env:
              TZ: ${TIMEZONE}

            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 500Mi
      
    service:
      main:
        ports:
          http:
            port: 8181
    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config-v1
      backup:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: /mnt/user/k8s-bak/tautulli
        mountPath: /config/backups
        readOnly: false