---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helm-release.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: frigate-config
    files:
      - config/config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
commonLabels:
  app.kubernetes.io/name: frigate
  app.kubernetes.io/instance: frigate
