apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- plex/ks.yaml
# - _pvc
# - jellyfin/ks.yaml
# - tautulli/ks.yaml
components:
  - ../../components/common
  - ../../components/repos/app-template