# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint: ${NAS_IP}:${NAS_PORT}
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:mBtSkZmkntoLMyar25+5YKo4yxiH80J09SAUUdTKiwMAQrYhcpUUCWxqC5gzkoKplLM92MGkUPL4ZugBN+wPpSOhxAGUvAowb2jUK92vVro0VyD+YilP+GDukObH48ZUf+NGP22tnsGYCJBzopubPmI19UFz4SNEGFP19UK9nYuUOsiak8HK+Zct33A55TgnuWQw79DgGNkBhbxUVQ==,iv:7SNYaqT46CspOYoY79H2km0EM1KZA8HiwLB1htEDDyY=,tag:U0XqRzIwFSJz0mtEPJTaQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-11T04:48:28Z"
    mac: ENC[AES256_GCM,data:J79JehBMmGpIxVPMMeUjF80Rgbzo6Ad8bsoxqwxztKF5f2oXz2Dr+xzy976C1v9WMdGDYvtQT08opVv2RL14twn3YDTHW4MIiLgkUfIGoSAQtpoxFZO+Fz71Yp6iPWzPkTqVDaUZEceEb0arxAcnzny9/RzbJwY6lBC9J1MCeJM=,iv:fzawqWWUegQ/LOkgQwYNGstJXpOlJkhVLvoUk5igpn0=,tag:a5j2CvsRi03lh6xT6pyt9g==,type:str]
    pgp:
        - created_at: "2021-10-15T01:42:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//foQFvLXLsIW5DxDEkgxL6yHdoUazDzXnbsEOMg0VPNly
            LljRz5Qb6tKXU0q8nn+NLBmtM9O47qk7d7jUEaWcaR7GitzL4rZ6yEgNHUutSswy
            W5TrAeS1RU6bLVJGE+dBmvBazMTx/xWeUo82jNexk3fqnXsqBuEp3mQNcRiXJQym
            SId7SIYA0efzj/mhWA4IV4nP5A+ZxBTnDGFjbbLlhxPABrmoi1hzh5pqAy6rWKMq
            KZrdts5anGUj+Yu/fqLLcuEGXvOe/OG78c0w3tLwjYOClFz8N3FG6/EtdoG0pNPW
            3QTsiZhDJiFYfmZdM6Stng4oLPZHrOF44mKnmc4yvaFTXWrjtFQhoLLPTyv8GUOr
            pckUhp8vNZJkRodrnoXh2lVccEQWAfIiyFSMs2MHKhSiO1rNJlEmP+vs4EgTtQfS
            9Ay6ILKb8hC2J8dqxFtbxlQakJkwpz5q/Iq7cw69H/Wmoo7ASxGMPjdyQtTPmXKg
            D56WA/5GP57JVPqIcBD/RPGvPRzLRe2xXuWzJ/areF/ksFelHhGtqBkmyQnVhQ8u
            gdeYcGOo+fxB0EwTImMbR9jvuIBYX0626wVwvNtfnNK+y/DFabeSajLUQS7msk9S
            9mFYYu6Y/4p+dOr9kLxEnqThufkeDWWCAOAbTfHv7uV9H17yGaQK7sAgsiDdkArS
            XgFKuRjYH4uEEgOjAQ0J1lZS9SmWoBaNalrIlDfsuYBz0KtxzeruQoY7f6szF7J9
            bnO88qb6yEeIF7lN77SX6vJWfDf4BTleqBAeVeoYN4W42Ao6pZLT97WcSpxu0RI=
            =EroR
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2021-10-15T01:42:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAeewpgcrFXuBHgOubv8nB4VYl44xCx4jXOJYTMMlox5BL
            I9XDf2qGPA/2sIYta2m73YQk/Nft7qyBKd6+jC+PzgQn2xTfn+geja5If8d6bD9u
            fPngbwc4XG6U3KdKBYlGA+Xhl4jKrWHvIwmZkMKlAJJbiP/H2psIp1z//2gwY2ve
            9GXjH8bBBBVYQohu70SASRNpHeyBCqjlhLiGM5pfeYEm3p1jPtCnIYA1RqhBqQpd
            gwRlJa2xs5O+kK6VQ8CL1vJlm9ylmXHzKsHSgydHehi6a9KCkqs30Wrr/+XvwJM0
            Uma/cFBAI/5u5xJI0+gZB3WHAaUlN8hO8J9HRZqYofxUPJRkSaJUwqulTQobq6xA
            x6L94gNk6wj/lKO4EjPDH22/Las/OnGD7UEW/FjWd4oY9DVt9a1QUWZq5Do0BZAE
            Fb5GiPR6ps2J88zGSkTKPa/Bbb0gmPjSDzbZBut6FKHw11kPychQ39yr0YwbiqFR
            +L3ekPNfXWnsTVSkywXL1cTNg22gHsC+0rVekTT6o8gIjrzfPqG5EKbvz3Mxjfu4
            +DUl/huUgHaiO6X4PMeG5tsh62u9JElLf5k9aVPCJp7smAD6nPRNpdf4CYrXDole
            Ds3yY9UWx97UhdGwAEa4DMypEjPqv6slWOsC+kvQmYOQJ7yibmJHNMNWgngb8kjS
            5gGzGnqhN5I+RN4+Iim9+1syHndNIgmCuwT7gzK8UxAk2hfRmhDdj48EaFLFn7rL
            Fpvd7Fj9gzt5YL/r1T/8x1nkc34LvkKBghQRWBc3AVV6veL8iCXjAA==
            =qzbK
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
