# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint: ${NAS_IP}:${NAS_PORT}
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:VlUGp0g65aWlTZCnWrE599bQqN34nD+3fZ58SA+ZwovQCKm76iPvE8CLsAIZasIs3AW7fpYxav8Cx6MpOIHJRFdu+p9itZWz9i+FdPascuhUHpHzulTZkwzHYaW4W5BJE9o5jNaIGhQB9xa0VnSWnliPS2NXWqSvNpAK5Lj3GM+qgl/n41hZjok054zsj/8oTFJLJlu45Qv0QQ0ABQ==,iv:Q4QPqg45bmNTX54mt5nUaQw5AwXBQg/bwsoNnjm0IGk=,tag:j4l8cyoRI5L9YZRUbA0+eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2024-10-26T13:50:49Z"
          enc: vault:v1:Ws+c46WZAwQd5N+kUw5SovIqEX/BP9CvuCzR3MC5QJ3fzLkwcmrivVcV8H/IulIXzTUVCct8wOG88HxN
    age:
        - recipient: age1h4562p88dlf3mh8v585vuautuae4hs0pvuyeh8wlagplt5dz3yqsgx7q9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Uk1GSFMrN2loek95VXZv
            M21IaXFOcTdqSyt2NExVZkFYMmRzUklQcFFVClJyOCsra2tDWjVsNVAxNHhHQmNX
            c1VRbmYzbkZKekREUFlEUzZYdjlDakEKLS0tIDFPbU53amJlN2VEL09vbFBseVk0
            T0VHZHJMcU1rclZUNE1aNjBudWROSlkKLyOL65uDiOyi+1gRQDrRDM8cXrfEFx1Z
            iRhgGpkFmdFXuzyJltOFaStaxSNQmyfy4O0bDn9C7RWsRk1NuowsRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VjlxTWNzT2pCL3F3Q2t3
            V2FiS1pWWXZtT0RBTVo3MXNHK21iOW5QYXlnCksxbnVVOFVKbjl1YVhpTWMxVy9S
            WUNmUDR5SjdwRGFhVzFpazVpckxYd1UKLS0tIHVPNEp3U2xyVTlZcld0NitlbGhL
            M2phbWV6bE5POGh5THpaU2krNDVzTVkKVHgA27bFT+Kl9WRXFMRq1wpgmjDD2iPt
            XWz5to8o8kjsFejSaCm8wS+S/qxaK3KfJ4j9lRW5FHecYujSG2Inwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUVYyc20yY3NPK0t1TStS
            eTdKS1BxNDFZNFhHMDcxeHdxOFVjaWE0TUJFClhwSUVwRFIxMVZrQTFrK2JtQVZI
            VkxxSGpORkNIVXFuM29sWDRjVjVENzQKLS0tIFdqajhQcHdydUNoaW5XTXYwVUdE
            eTBCYVNBb013ZGlHclNVa1kraC9kcWsKW83Nry/r+yXQUdwUW5oSo9rAUQVxazKJ
            H/NDrfAh8TbLqRMSv/+PFKCR/puaR+2SvsNR1gZCB6191iphl7OEfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOGx1czJ4VG5jcGE1ZGtZ
            ZENySFBra2Y5eGdLUDlHcG5zTEJRaldjTHdBCnRQUVlMeDF1VFNCSmVwS2ZuRytK
            M1dvamgzcHBsMTc4TmovWVVCTjNPOWMKLS0tIGN5Q00zbVJMaVpmTzg3VVJEZ2Ji
            akFwMmhDM3g0SGtqRFJqa2NIa2cxMWMKn7GasaircswSrWK6zzCTM1tj/gsg/p43
            jPNTvEzXM1xde9x/doj6zG/8Urpt8buktpm755S7jsFPi6HInEkX+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T13:50:49Z"
    mac: ENC[AES256_GCM,data:u4EXcmXnJaevy5J7+aVZ/Ybt/GQhrhLaGbYiMhAbETwY0pyfHNwNmcJXfO/LCwWqRFSplnLiUDw4ym1/oj2CFFg/VnpyrFA/arIpIPZXfbB7JXm/lmqG0B0zax02xLmcYKCwqZhPJ0OOje1+LNcnmn7iSoALO0rbbq/5YsLBfUQ=,iv:mX4araflsAKyR21VcBf3x8xayCQAh4qzXS9PrJEpR4w=,tag:38Adof1e2t6LK3ZU+vT96A==,type:str]
    pgp:
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//UQU78Kd8rY0PQlpU3suoA6lG7Gqx1ma3w0CmzsWssT1q
            39Ow8C25648IF9e5C2jBiILHgykJtSJssXFbDD4mtdeFmxKVDwyDfGb3YNsuLZ67
            RWmU/M5SL1aYS3d1QPTbL49RbitDTikkTvSMzuZKcGz4fox5MsfvXYNcJTe9dtUR
            SpxcVG6B6kOoh/Gj53/m5/lRvZ8CP2dXjGCt+mo0g0w3yQ107IKBSXtHqdKHViWx
            tFXP6zd0SajjjwKX1SI76VFhIyE3Prl331JHf+jr7RTPYQStfUndNaJo/ioEAEuU
            hPpqfblGtnJKOIJ6v/B2wzfTJ+Bd+vsYZUtQMbCkDBK7Ioe83hCMD6o8xd81ghUX
            8UG6PyrrqgdWGKqXXfF1n0I5LNWSTmoZGEnDaDYRSxhp6KASwMRzKKrg5+JvzOe5
            m8e+0Amu6Tl/C2tGOhErkpM7qYe+VKl35KQNcr4LCUETAFw65k8rHykgbesfnUNO
            583Ab9lbYfpGx+vl93jnUy6j0NRp9b/V85LaMPGLPWmvSiTNv0nomfsKiZqZwZzI
            7OJpc/GxhWA1p+ORQKvJ+X63AAhgKEOY9Z5zQohHuD7dMQ+/tbc/lmuI+V//t7TF
            eawLcm4Ayx3GCp3tEPEAyj/4tBLYH7XhANqu/S4Bsi4TpB/sKBWTf+pHRgH/xUfS
            XAGuutDQqR335qx4K/ltKUl8R7ic7qZnDGc2GDGKdBLO/ApYKg+HehNaUUq5+G5l
            RdbInFGwYQb5Lx3FMqiPeKaGWzXl5mHOVeN4qVR0AQ+9QYCFgUiwV8j8gSBx
            =4SOE
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ//cphwKuTcQrNBsZwk+ERAxObyimNpvYMNk6frJl+weWHx
            JkTHX+jf5mAi+r82y8FnMZboufValH6viFBJrO0vH/fMbaSBTn+5epslpAU5rP7W
            bfTyH37iI56VmHgUuHEAweqETYKNwOHm70hNm3s+axG5EQni17aTGl3E9mNoNgxE
            vHpeTBEFSXuJHXrLWsFmqVO0wDEMMqxYPqgV9Vm4iChGhG02fSqSvrCX5kjkgMND
            9ZHR/Ci9jZHEg6euvjPreJVEPfUP+qfEKpL63+I4COTXUvPyps5T5VKohL5cxbel
            EQzaPNXfRssE75vbvrBbczhjDCIW0hQBehdjhnzPvMxFw4dbKKSgI/YH5sUcPQFK
            FA2e0sN53zTMrKGPfu9kiNHhuQKClabgljueCATevbKemly/UNZSEZgue7u5q01j
            lJt9EK4pkbGTIpJqDBpy5M8w7Kl6IGzjfP+rORlfm7/WIScAPWP+W66yZnJHsSmF
            +UfDloHJzfKKQbpdA6owYp0s6KwrvD87npFNjTkwKP3z6KTTwO/P3ECxrCt6CYgG
            6LuLBn+8iZ+3O07aIiZRm8MBUMELEB8tqmrzCRl68hPVMcIcetRK+8xvdUXusfTF
            6yCNSJvh5xDMXXlWgpKbYn8XyyqesjGiWuuhecAHTAAKGX199iRhyiuP46fkQDPS
            XAHvY1PnAobjNvyy2qxH0dGVhoRCf4quqX/YBGsL8kdAwIFWpu/NAnOA9CwuDj//
            kSNRFPd4CRs5001Y8sYw2RBCSg73GMmcVlnIuREsP5wuJvLx3bBPnNIHyE7i
            =VZnQ
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ//XfkIwy1R7OPX2EuPa6gxSrAenwdXl3g6bfvsRxBxUqga
            arMBa7DgXA5/DEAjjUFoZ+IKSSSuN8K8QPNgSZ4gswLsfTb2Ne/GLOWe4T+z2ZT3
            8SUFilmDFiuH3+B+gcVPEK0lwwxxQ5TfybeQI9H+4jlSd+RmlXkLgWWO95mch4IS
            NoF61C15yQM3yjyOmWtET0kaaENcx/XpWhyIOqB6ktCkefoWmnZseDXcnJN2q9ur
            Q8lTw1wnj4qjweyGRMm2fZaCHk9bRGk/XFkc41lNy0w4Ai4hLIfxHNeMi+vKizQR
            erGH/5qEgHdDTPM7TGFiXFrnPgHuiKJXPyw1VR7B0imaxxPRXHswfkODinjpsRhX
            cMqv6+ohbwoEAbjBQ+8zUGgS5UU7YPBQ6YsZ42qhHxayFnfE18rV1b2WkjZWI6gC
            p6deg2LBgank9uRxV2U3hFJi5AsP5VDDHbkarc2/NW7aZ0+rE/htDZzD9kc7SgbY
            27PhP3yZrjsOjO8sUiztdteLHevn4XdUztz9+zFNZxHeI5skPP4lVbfFlsRDKjzK
            zWGIL7mBc7zoM394Pt96pd9jcM/6o/PDPlOG+xqRZOWY86bzkbYKYF8j23DEqB7+
            2Nxdbpws6ixV1z6dR/14ISAkELOySS6h6AcuVy37RS6/zexQCUAbmxvYrEEk7UPS
            XAG7CiWAQ9Gw5VYfM4VrchIzyPHnuvp7wzk4ddfOcMYK4O/oq7nbLyF50b1MeFeC
            6Bl+NC+EB+ElCKDLd4E8Zh6NeE0+mM/TgDlzgrmRlLmcr3UlgaVxA09QIuOS
            =kD7R
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
