# general:
#     sleep_for: 0
#     verbosity: debug
#     tickle_rtl_tcp: false
#     device_id: 0bda:2838
# mqtt:
#     host: mosquitto.home.svc.cluster.local
#     port: 1883
#     tls_enabled: false
#     user: ${RTLAMR_MOSQUITTO_MQTT_USERNAME}
#     password: ${RTLAMR_MOSQUITTO_MQTT_PASSWORD}
#     ha_autodiscovery: true
#     ha_autodiscovery_topic: homeassistant
#     base_topic: rtlamr
# custom_parameters:
#     rtltcp: -s 2048000
#     rtlamr: -unique=true -symbollength=32
# meters:
#     - id: ${RTLAMR2MQTT_METER_ID}
#       protocol: scm
#       name: energy_meter
#       format: '######'
#       unit_of_measurement: kWh
#       icon: mdi:gauge
#       device_class: energy
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: rtlamr2mqtt-secret
    namespace: home
stringData:
    rtlamr2mqtt.yaml: ENC[AES256_GCM,data:AISsPT7elFRM9Nzk3LEvML4oM0uOAlDTJHDynLsd1WVIezuv78LlXswKAO7nHX6k7iOLfXFeenZdPowLWNy0DDDRgPAvCGlAoSuDeONDCgSof2QYDg79sXzo2k6hd2EXtVyLJVr+99qd8pcIHKV654zg9XRW5usBm1NaDCQAM+/7waGPmVI6kU9kK2lpi4suIHhw6ugepaB86BOJJvCeF2yMFyyNBKHDGoSwm+lJ8a8PPDccyjNKRdOy64YFLe7bPIq2k4AwW+X/Q3+EwgoqLOyyj58xQTgJrfupOQekcSdbiGE98PsIbOoc/CrKIbQ0EM2vTuDISZGSB6k2rd9FqLM30mhOY2YtIJweoME7aHXNWvJdMx8f5ZpF0JA/x3CwgUu6BvruVLTgdF2IiWipP3m5CY6tmrLb3xZL0AwdFZ3YUHUnf8dVEGZX9r78lB6nh9DtvJxNmAF50pONGyIYR/uw42EQ5RKcEot2IKSnG089D0z9z0n44lNvI87ywD2ui3hj7V0GY+udl2a7hfby+aO6wJHeiH00jgjgisHwi4eaZaTfDkr/wMB71cMqGiAcCS3iyNSg4mpsWwgTRgr9n2R6qfUSu471l1vWVrmLYK5J91E/wLly3dHarbMnMnfTtt2k/SPKEwdsYQcvGDm7xA76aO00FEkdH8V3EEXkp/j0B9ngLy9AWayVY3Nfbv7MkcjqHzN2+ozFA0wvsL3UdzOuOBTomeMyPG3il7xKlO+PdXdjJ/Ih1W4zU6h5h6JkmVy05bxlNJQ96xa0lZHkrdmD7meAeE5RICzr,iv:qJ2v8GIG8xja6csfr6/7Yk3TemCwANK23hiw4VlI6ZU=,tag:V1df+S442QYJr7jsSmi66w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2024-10-26T13:50:49Z"
          enc: vault:v1:filcP/hKxkkwBgiMnW+d61FRPCcbXpD90qItRFup9yHmmC39lDDISsQ+XN+wFAmt8mxDY3CL3PfUiln6
    age:
        - recipient: age1h4562p88dlf3mh8v585vuautuae4hs0pvuyeh8wlagplt5dz3yqsgx7q9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWDVmY3JSNFBNeUlXUlZY
            RXpIYjVSaTY3dkJNamE3akhuRXNhcGVYaUE4CndHdGx6b2lneG1NQkxsZnM3eXk5
            bzVqaDZsTnc1c1JmYVVsWUVpd2Q2eE0KLS0tIEZrN1VEeHdjQlNPU0ZkcG1URGFs
            UDlreGt0a2dEYi91OHRvS0RRaHloenMKoeXRituEE4bkNe8897W9DuVcFQgrw3Jb
            jgHalq8CNH+ENVeGfpfZxAbU3RpfbUaPUrrd9lN8VwtaOE9ZMEX8uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsV3Z6WDJoUTNUcytlVUs4
            SFkycGhlRldPcFB6TWVnTEwyK2w1OVlpRVRNCjNDRkdnUUVDd3FtNkVpZnVSdzE3
            cFlKb3gzUklrRmQ0TWR6cXRwMGhVclkKLS0tIDZkQm5qcnlJaGtmYXExN3Bxb29B
            bU1Ua0lxRE40c1VUZWV5VTNrRFc3MncKpcYFGImCzzHuYo8sk/AG01BRSGQrTiW1
            huQMOoe9O9+oykOePnxhsbzr1OrTX8EDEjPOG+fQdH2iA9tIuExt6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSDdOYWRmMlBXd0krdlJV
            U1VvMUE4aHkxanZ5S2hYN2UwOUJwNVJsTjMwClJhZWtOT2gzUmUzS0RXTnFvY1RB
            dE5wL1hrOG9xb2pORWRnWHNDUVVNakEKLS0tIGJUUDNWNHJJb25KZkt3N1BJSFQ5
            MThQdUZIcmJadUdySUJkdkYwYURWVmsKGZBWbe5SHHSHWIPV8PEAkLGa803mlw7l
            qyeThtTAziACBi67fNTNo7biG0LhTzJwPoHd8L+HeR3YW00LuQP9Ow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4V1RRODYvZWovblFxa3N1
            ZVVmODBSWU05c1BTczZ4cGZoRkFqdXgxWTBNCjdpZEhCYzNyQnBSV1dZSUNPcm44
            MlNPc2diaTd5TWY4clh0R2d6U1RKbEUKLS0tIGRHQ1R3cmNoQ256Nk1sWkJuZngx
            REVKM1FUcjhPOGtxYS9NeFIzNXFLbVUK7JOPIKjQsRSPUA0IyASd5/8PjvHFb6Ri
            WUyr2OxJPH3TESbU4+2lO7cKs+3N2FBNKomU/JAFhszipp2NQtJeWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T13:50:49Z"
    mac: ENC[AES256_GCM,data:xt+a9HrxcKYyYECm7G/BWUaA2LrHhp5393BsO+G/ac15yV33Pc0mJqeNhjKHLuZhq2YaUWc8eUWsAqDeDMiTtuUUA3hUOn9++r3jw7BN2zzH1oZJnLREGOzdPB5SJV8mFUa3g2vC1WqrZpQsktBiX90qpuviis0RKuANyAzX7IM=,iv:2t4vQ8Fgq9PIljI5qT0oUqJ9k5L9uoMNFKHO9jIIZjg=,tag:AJOJRfSfTitIsC67axLqEg==,type:str]
    pgp:
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//bqz2e4KxE56A/U0cgXWwZjDZfwXOe4rg6xnbUws/ynCW
            5M1boOESKSSV8bTGYNV9+Y4f3hK2puEnzPldAd3AoSEh6erXU5jJJpTRIA9jL6oq
            aOJL3IfLbGn75UBteFIL+7sxbtHWH1nRDPgLwHsTl11qg0GnR8Q5HAC3f+EagY7w
            0R3Klg5c6rY/LJ+Hz3BLZCvQypJg/+dGd/Caf6gGevy3ohc4QPjQzvA2Seg2SFep
            M9Ey4+AIVTHzGrae/sXEIuA4Vyf4quYsYKwrTn0kd/5xY7Jkw/zL6R7NmLGI/k2E
            4+Lui5AmUi4DqS3K4Il9MFIlaK3CRvHqk28mMJH5IntFwpp+oTjPdcYjQTezpOM7
            GvfxnrVedrmROOVt1Vn8xKxLyc43ZRbETIHn3Ip/hQ/MfFZmwhEbcrGJ3O0jJr7C
            6ghjyeTcIOcAifW2j732TQHVNUBnG4LW8yDIosObQmlLJvxk9f6/Huui854orddI
            cHNezzoEMMzYYeXma+T2z+M7Iggxza5iP4+JNK+DdXDHEWaVUDeXKmf/Mrl7Zqfh
            3FpKG/L+wyTWD5yCDR4FAW8Ni+imOLkrjdnZe4d7Q6i66WUL/4Ea+yIG2zxuKr3k
            9LD8F08HnV4LRPyr5u8t1v+ozVFM562bUsBmBe92izOlVGVpk+ljaaa1+ba/Gw/S
            XAGBY99pVLcUfHYzq6zTmW3+hDe0glsYAJq/pCCC0LhfHBJV1B5B/ynfmT84S5t9
            TzlAs2aGc171BBLQRNXn0DMYy2YkIsBoYcuV3sbeYQMId5YgknExo0IMUjgO
            =Ouw/
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAAgmMNToV49CkSoz3NHD68cfK5bVCt4GmqK/YtoySmrXvQ
            4+OP4HrR2DiqxSvMQcHNTBfljk+qhp9DPTWlCV4eEOjl1dZX4yCqvpQaDNurhvxV
            dZYJLen+CE8VWwIBJH3ShD2/nJ67DMiO14mhkM40onV3pzjFgJB/PR20h3cKHMtY
            aPnWiISYA7dQjA0LgRPhT9qOpkyqwSIInqieT2eMGxXxCHjfKOX55IsbgyeOtQpT
            3Jk8pMHel7j24UdNaXcFYJrIp0KeMdoc2ylKJS5XCgN+dsJFuZ+zUvOPYpVcgX4T
            A9Ebm1HP4kgRZwDr1c5GbfkLItQQipTUvXQy1FJyztQCPeHa1DOODiOC7Ig23akG
            ppAVhVA+MK6J1n6GowDmlAaqUM1Kz9Tx4acy1q7ib60Pr90DaUvM10b0sDr11hh2
            LaN9hg5+Xwklf81Cr0cKm0NWRmpyjo1Orvm9Uggs10uvaIyq79WQU/TTjc9kGTNp
            gbyXHIzn6HDIh48VRw5ulI9sBnqYslEo0chCKQx7CJdavFeYX2WHHId2Puw8ENB1
            M7PeMyb3r8HhS6t5Af5sHn/7Ky+SY89ib8HcgFQJ5EA2Q2Fn26/nGRzXvKki7lc8
            mVA+LXyp6cRTV8frvPOcDrj5AExy130qa5gHH7+a2zn0GOGkG1M5bZI39/kWAuzS
            XAFSht/vwJzb82ZmOK2BuofV/FWIZBOr1nAv2ibXmALIpKmKRmN9lcb+fXw90bYh
            MYm26xPIX/uI23W3dBR8Zy2ggUTGGDAsp0QITlqdmOlhco45q5LAvSVnvgCf
            =XXIA
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAAia8r+fz3rhw0EhADQZvNmKJqVy7Dq9+r/P1VoJl7YWwg
            1xnVHfl8UQPsVSWP4fq4XZI0O+Pvs28LdGjAYvyzOesQ5ciupr1LHFvAXlkDELl8
            Y+pJrnJE1Wz+di19qw0ft07lu+pZmBczpshIJO3hrAnVTt+st+UBSvPYpfOh4MM1
            Z2cwOdNdS+v9xGKMAW9ldM6pBa5Kj1rki/hP5Fga8K/uMzR7zb8KIbLCosWLybDB
            vA1yWPF1z1VTyOyjjeODuQj10MGRf2Tglds3Ka0adoNU0RQ5WYs62RzZa5qskezo
            972XBlsHQXFi0Le4BxQPc3n+vdlP+x48CkQWKd1nbw7JxjXWhzw5vbPraIhzwhVG
            dMiAIfHWUNoPQTd8auVajSZptUZDjIE7e2qG4p5mllphBJi4dxD0LYYHp6OctKBb
            mDL6Juann8OvjP9w4dGjgiA4uAvFX8B14AN8ICvk/92zFNwkUBP5+UJG/FLW2KcX
            spMuuSXIjSR1Q6nNg5+TsjiKOIB1Pj6LSJHa+5ozklaBF9ogQ7SmOeNJOwkA/BH2
            uNF4d6QB+JrRrCGiYmhM/XoUVWLiin+L8RzPu9x0r1IIIZqyP76W02ijW9qA2hdx
            wBg4Wv+bKUoErIQztim9AgUtAJYNyK/VnF3Cgqg1Hlu5b2HE5ih4N/LmPyk2SinS
            XAG2fKF2h8ORda9V5RDX6VzwfBeVi5YbCCdXGA55BSGjXFueXByWC2kr9YWplDIA
            Odpa8pnIocVt9cZXHQATloIWf5IBrHkMSaDKPJdZ17jRL4jsY1UvvRg5kuJz
            =pmAB
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
