---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: sso
  labels:
    app.kubernetes.io/name: &name postgresql
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "false"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ceph-block
