---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.15
    env:
      TZ: "America/New_York"
    service:
      main:
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
        type: LoadBalancer
        loadBalancerIP: ${LB_MOSQUITTO_IP}
        externalTrafficPolicy: Local
    auth:
      enabled: true
    # -- By enabling this, authentication and access control settings will be controlled on a per-listener basis
    perListenerSettings: false

    # -- When enabled, this adds the `listener` option to the mosquitto config.
    # Change this to false when using TLS.
    addListener: true
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto
    configmap:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            per_listener_settings false
            listener 1883
            allow_anonymous false
            persistence true
            persistence_location /mosquitto/data
            autosave_interval 1800
            include_dir /mosquitto/configinc
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
      config:
        enabled: true
        type: custom
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
        volumeSpec:
          configMap:
            name: mosquitto-config
      configinc:
        enabled: true
        type: custom
        mountPath: /mosquitto/configinc
        volumeSpec:
          secret:
            secretName: mosquitto
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 500Mi
