---

- include: host.yml
  tags:
  - host

- include: locale.yml
  tags:
  - locale

- include: packages.yml
  tags:
  - packages

# - include: power-button.yml
#   tags:
#   - power-button

- include: kernel.yml
  tags:
  - kernel

- include: boot.yml
  tags:
  - boot

- include: network.yml
  tags:
  - network

# - include: netplan.yml
#   tags:
#   - netplan

- include: filesystem.yml
  tags:
  - filesystem

- include: unattended-upgrades.yml
  tags:
  - unattended-upgrades

- include: user.yml
  tags:
  - user

# - include: rsyslog.yml
#   when:
#   - rsyslog.enabled is defined
#   - rsyslog.enabled
#   tags:
#   - rsyslog
