---

- name: power-button | disable single power button press shutdown
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "{{ item.setting }}"
    line: "{{ item.setting }}={{ item.value }}"
  loop:
  - { setting: HandlePowerKey, value: ignore }

- name: power-button | restart logind systemd service
  ansible.builtin.systemd:
    name: systemd-logind.service
    daemon_reload: true
    enabled: true
    state: restarted
