---

- name: user | add to sudoers
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"

- name: user | add additional SSH public keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop: "{{ ssh_authorized_keys }}"
  when:
  - ssh_authorized_keys is defined
  - ssh_authorized_keys is iterable
  - ssh_authorized_keys | length > 0

- name: user | check if hushlogin exists
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/.hushlogin"
  register: hushlogin_result

- name: user | silence the login prompt
  ansible.builtin.file:
    dest: "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
