# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:HlEsQe2rkJrrktbJhZoiCTHYO14XCQ3JyQS+7fL0i3DYY/gsqXHH9A==,iv:JpPL9lZDsE9q9X6EER5yQRo4++yv6VZgdtt9KmAba+A=,tag:BsBCI3JrELLjHQrnwlqidQ==,type:str]
sops:
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2025-05-04T04:00:06Z"
          enc: vault:v1:2YG9FAoYxxEN0JV9aRroMAADalWwfTRqN2doc9K14OihqveifDtmUsbo3yzaIbZEB0PlHtWt6ePhxytz
    age:
        - recipient: age1nhsedg5k84dkmeufjud2g0epwz8dsl2l9qnsrzg0vtwdd9zgkdvsh662xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBramdIcjhzRTc3bEJXYTA3
            R3V0U3l2L3l3MkFOTWZqYXlCNjVURVJHYmtRCnJCMC9CaTVLc2lySGM3VDZsMVN3
            Nm1aczZuNFplWTRYaDd6L0p2SHlCNEUKLS0tIGNiRG5RSWYveXlWTGRMTEZ6VE9M
            ZlVCVGQzNGVqUFJJeE5yeGhHazNkcjQKW22S4zlCs0thh5IM+L3Sq7a13XawfvtK
            O8/FSbkA0BQvMRpdsSI1d5FMmsSK7G8qEjpOauhXJuYchWkozZqY0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVmQrcGZ6WitpYmJRY0hq
            dlFSb1FtRVBmUVRJZ3NhdnczOHlTZmtxMHlJCnUyUXg2dk1SejNmakduQ1QxQWZU
            dURoRWowdkd4V0Q4MzdtbUxMZ0FKVzgKLS0tIDBoRkoxSlZ1blJIeWptSWczRVJ0
            Q1ZTS3lWdnVGUERRdXJKbkNnQ213MjgK3nf4bXB8wQ+jY+LqCgafDxK+4XWhyyWn
            zNCZALbekh71FnG/stXoXBSDpCChYHJWgf22VzmVb8xNRv7Xzp0z0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T04:00:06Z"
    mac: ENC[AES256_GCM,data:IF6hRdyjBK1tG+NLjRd+ssXCs6Nrm2HuGLK9hyi4NVomu8TNJF7z7FJ/cozC50st1Hhq5hzDKH5spJ7i1JGGgxhW29uBvzxuzAC4L+u5fCBd3mrw+v7rvXPKsbEQ0fOReLs1tx/eqMbjJR2WdoXb8Ky7ucDVGlHKJylDd2XyiFc=,iv:IMdECaQwgyUuYsrSdyMU9Y3tGhBwB/ruFdRhUF1eXjM=,tag:oLtkDKJOSTZ1lqAAL0F4tA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
