---

# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration

# Don't define the host as control plane nodes
k3s_control_node: false


# k3s settings for all worker nodes
k3s_agent:
  node-ip: "{{ ansible_host }}"
  kubelet-arg:
    - "feature-gates=EphemeralContainers=true,MixedProtocolLBService=true,ReadWriteOncePod=true"

  # Add node-label for longhorn to create disks
  # https://longhorn.io/docs/1.1.2/advanced-resources/default-disk-and-node-config/
  # CLI: kubectl label nodes k8s-worker01 node.longhorn.io/create-default-disk=true
  # Leaving here because maybe someday longhorn won't break after 2 months.
  node-label:
    - "node.longhorn.io/create-default-disk=true"
