# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: development
stringData:
    SECRET_GITEA_REDIS_PASSWORD: ENC[AES256_GCM,data:WpgaD0kRcU64cnQHqnaUGG624Rsi0ekj0rLOTIApyyrM,iv:1qLRr3aeoMWlunKlLqrhgfccqL/d0ovALYcoMyEqbl4=,tag:YOa9REfuyCnXK9HelRmcjQ==,type:str]
    SECRET_GITEA_REDIS_HOST: ENC[AES256_GCM,data:2DhGHDZHAU6CSzyt3v3FqSCuMwmjW141sD20CXZXAvqqCgluYSNvHqE0cadLnZjX24n6Nlt1BuYtDiUvX2FoUOGAuXY34imfFpdmye7zQIt9qq3F5M70elMXBu85,iv:x8RrxX1OqADi6q2h4DZ6YM9XvrFv84pKYhVdigy0JpA=,tag:0fgLUq8RQDHvrCX5EDOE+w==,type:str]
    SECRET_GITEA_SECRET: ENC[AES256_GCM,data:v/6CNqklBgZirwAZuxW+j8Nm3CBsBw==,iv:YPoWX36wAO2UJd/fERN/VCM7BSx9kRmoNLRJNmelnmo=,tag:3PClTSIHK+tl5LZoH0OTkg==,type:str]
    SECRET_GITEA_LFS_JWT: ENC[AES256_GCM,data:hx4V5e5DpraNiKNdL6/JiXVdSUi3+nQEMy8W4QC5QqkkTOD04Dl1xiE6hw==,iv:16QC+77HXKytbh14gxYmEP3NG9zyZOeV8qsBCKXElZw=,tag:9vMNHnvHV+cTQZpPVVi/wQ==,type:str]
    SECRET_GITEA_PG_PASSWORD: ENC[AES256_GCM,data:sO2z5UuGF/WAPFE+ryoxgr9EFgK7Q6wQLls=,iv:TS/GSI+c8D2XbjAdWq3BXJ/ZVfQj/0+OF2hsUY3yrHU=,tag:esYnc77Jb/tOZlJCl2AA1Q==,type:str]
    SECRET_GITEA_PG_HOST: ENC[AES256_GCM,data:Ec85akpGaJj5OkUBc5+Lqw==,iv:hjjhmpyXgaZ8hXJWlBr0MjRvi1Q+w8NtKBmcL+xVGUg=,tag:nOGqc+c0yxSrRmsr/R5sxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-10-08T01:49:39Z"
          enc: vault:v1:wl3CDPQyiMzNoma08btSvfQQFIt7CSxjdREVVJb+CLbCyNCFEGBoX1+3Cy3uZ7eY1IHI76HfpUSZyZ1w
    age:
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MmRycTdpeVFzZEQzNmFG
            UkU5V3FHN0I3bVhaeW9LV01za0FUSWorQjNrCjJ5djYyYkV3bUxBS2I2dklZMlc3
            dmM5SUpleHNBQUoyektTQ3MyL1pFR3cKLS0tIHVKMDJTMmtYUS8yd0wyenNoY1VY
            enJrcDJub3NtU1VIdDJwN1dWdmFVZ0UKtbk7GqrMLfcPNnC6pfYL0zBa4xpqoQyP
            daC1IoDzfPNJdvv90bhVXhEbyFaRPUz5PAWn3nEZydWofVYubSdN/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR1VzelozUE1wQnQrU0FX
            Ym4yaWhiMjdkT0l4QU9CcUs2bkpMUWxReFg4CnZGNUJ4V25TRDdDbmh6Nll4dmZn
            dk9KbWZWVTliaEZ2azNnMU1lMGZESEUKLS0tIE9tdjgxaWhjL1R2U3ZhaythOENm
            dVZvb0ZQQXJLSk52a0ZPSjNxaEIxL0kKFH3Z9KaBI163LyAgXZcJDaCBG1PZbZRI
            TEX3OQKhkLCnH2O5nMyN5ZKhVOb97iv0WvGnf8iDo2+7sjPoThefCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxKzZETkVTV3grcGhTdTRU
            ZklUOXdycStKR3FjYUlvSVFOYXZQS3BFT2lBCkF0V0g1M09PeGdYUFoweW5mcEM2
            bkh0bzJDYzhweC82dVpydmxkeGtuNG8KLS0tIEpZNHE5ZTRpLzlyaVNzZ0Q0M2dm
            L0NiTmFkK25kRGZ1eHNnblBIbFE5ZUEK8yJoPhqAGfj+v/KC8wN7Iq654l2LXipK
            VR0fkA7TfhYmdfLE+ms0pD/2bADZtbBnioqctrsuua+2dSn/gqYHBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T02:36:43Z"
    mac: ENC[AES256_GCM,data:VnDFWnbFcVKK/o/mf32Zc9TlFXdxx9hr2gdjLtQ+nmtqKkbeVAO1St+OBaaTkE8ZfBM6ivTS7rflLolncXF/z8hloDhVtWZvPK4e8A8wnUzGGkl1+G6xrru+9vaP1dMRBEVHmidT7Tpx1zYKc4ePd1WAqHt1wmcjWOn8Fk/p2JI=,iv:jfHzVEnIwyxsxIyoUMGcVaA8Y9rsI6at3rASCzyIl7o=,tag:gn/kj86F1DCergvNTxt6MA==,type:str]
    pgp:
        - created_at: "2023-10-08T01:49:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ/9EJPnIxu0oUsLa1C3WNHRgheJquZUaGGyTKpd4N+FjDnn
            SJiHJ7R11u3Uex9TfsqBSRfsYyKcsUfqJmeoLDzJaWwNRUG4UXf83N6NfBs7OFwK
            VWH5MYz2wK3qXkFRWQZaD0glCJlJsSklVqf1NBPQqBPQyEiIghMASPk9N5X1WGKM
            W00QT+uU6I6VhqnuCfU/LHANrjVxNPjXjpBcJavr9oli/GvEoyIZ+BD7vVjLBGae
            mQGIoPguQ9Ac+1a27NasdYf1hFbzmGb9ho1KaGX7cADnqMAqu+YRbLiJx+L8CiG3
            YMtn2T/JUIwt0kQUTdvgRY9vnvkPYELvB3g//oeATOT7IiHxEuSyj9b+rlTQ01h3
            RjcuY+lWiMu8bMmt1h/znAysmh+OI3xOAkPzD43wglUu+pSFI2GfwXnPmNJbkLMU
            F/TfbHi5L7xThqKTjMFlSs0M63JH77KkOmqwKGPsB1v6N/zXyCwCvrBsgkDocDXq
            salqiZD7M/8jDCUJzYv5ioUbJ8HBKQWSa+pb1jPMm6n7y33hsqt5VgbngAjIryPe
            4Xct/k7+YCJu8Pyf0migYPrn9URrUBC0ve6/S0d2ObEIeMg52yMuaqKAZWGDF97e
            ZRpgFrgMVt1UG4RcutBjOUw94Yd8Xzz2Md//fRz/0cQ/CN2a1JeUzhg3KunDnZvS
            XgGQGzrYArkmE5yvosmjHG8AXUXnYYkEXzdxsjknogSgqobNnEdAq10oC21wegnW
            ZIVKYix83pbhnPwQbackoO3+W096YXkkUZnrTeAxvcaaQKP8wKZ/25PYZ+aP5NQ=
            =N4/j
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-10-08T01:49:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAAwizQ0wBoLKYQuc3suafUbfcj9Ram1tNfMhW55IZbRQK6
            AWznvUGoQIi5pTnDsP5lzwkIw6CPjwKrRGYZnfr6Jcn76syyGlRM3pffUC8MqfFQ
            jCudRZC9CcWOfJEpsKyNjDIwXAq5XiBUNT9V1z4dyAtYzs8dRrdeVzjzWKzWHVKm
            h2T4OhxsKkbLgYe1tI5t8Z+EK370ErB+xJnBPIC6YVnLTR+pK5m8OCtV/3MzeDgk
            oHHXbgn/hfE9L21TImmPcvVQY12UriVixb+lZqlKOe5ZKkHd6AzXb1XhB9IAVARa
            DA0bLSTsrE2iBkaR2AcD1HneaesoGCEdFFpsvZHSufmgViyqCppej9UiC++hFtT5
            YJLZholbBhYXO+D+fs7MD+vyvwIgoW8lPuYZ1+uus/z6cysKMq/Qy3QVUuSJzZEN
            Gzn45gSO3oSiq5kGALtl96dFQiuVHKhzzwRhicbKYUeoxLIqprgafruiVbyKrmDA
            jdaxxsRn/C4FpEMyr2fSc0UqX+VCjyy2rETM+f/2rdHXjXwYhM6SBchLMz7w9Lpf
            qJXVgHdKQdDBYgeqCvrpHzA1GObFvKVvuLpmHZe8AVPDSoI2vv5BOfQAlISl8Ys7
            kYT6xoqbCG56tLHm0ZU2J+m6ucqt6DWXUFEaN0J1QQW5CNicxlqRj8JebmXTanLS
            XgHbKt63ov9r6EPYCxmlrCktWbzP4ZKSaYM3CwKgAcQGgrLmSl34pn7xk+WfP94C
            Gg+c3vf/nXgL1jg7IogWK71OBvRsw8qwdrNTaxoVajrSqOYNoMoA1RRI/C6wmrM=
            =5smG
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2023-10-08T01:49:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAAjvoPrx6iydWxviN7duV6UNUtnvvi0lXzt7iC1VaLJojb
            IzVctphQBoHklTCKqrRm26eIJN0g/N7vTc3kPrqUJlOaF5cdHXt4e/GYE7lFzBuM
            lUxTc52P6eSr6YzgwIAx3EKL0MqLC43oMJ83WryudPcrr5CWWRupaPx5ipMtcJCw
            Xbp7i7NvX8E4RJfLAZmLQ0bhKfONH/6pMKKSlOT2eUVd4uQ+A0r4kaNFEKHcegQE
            rCzPyRhn2X39TnvuMscpZJm+53nviMUzudB6C7FkfzJ9apVwVsiSNMWlL5AWIa0Y
            945Z5oUBRetwjDi2PnSuS1AvPkSxbj8tjFttZfKT7J7C9U4GsFoiXa9wXFuCagBR
            MLa8kLiuMqriv4eDYdSbKYNYGgBTRFDnumKp0MAR3LN0o4UrUZecCwUDvVrstaa2
            zrhBqHqhanmouoRSmVmOutZxiXP15fLbP7qU7Md8GzRLDEgIt+PCT6heF6vvNkL6
            vu6zaAgeipiH8Trwog6EkZMo3y+3LvLBFEqlj5fxuVLKik0v0+R3/oX4gdjB5i9a
            eCqkPrOB6HmaUab2x/uEgCjEvm/eZBM+vwnDJYBkB3HuK37iYami7mIsBJteySLp
            kg8pkNveXGqRoMIiofGxbns5pz25wRWAsZxGr9OqZ1kOxURHbb+eqvFrNlJ8iv7S
            XgH4k/NYM7lbpTs7Yto3SXb3n+GTFmCKVLPayqzUG6QBBX6T0392JYw/VFhr2/Y3
            ksQ9mKPh4Dnr+/NPcUDkSyvhSuvWgkedtMh/bBm3DwLqrFXMnyvQ6FM+d4uu4u4=
            =D3/2
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
