# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: development
stringData:
    SECRET_GITEA_REDIS_PASSWORD: ENC[AES256_GCM,data:W4H0yWfJawvqNrduI+lN0rx3Z6u0oj/U2/NdREnY94mf,iv:N6mLhIgjSCwRTPCQ/EongNYyUHIMzUIZrYlt5kKGjsU=,tag:KYfYPc6r/tJqc8/FvwqCnA==,type:str]
    SECRET_GITEA_REDIS_HOST: ENC[AES256_GCM,data:vCz2b9gqpyrEFAR1Pb3T2GmHKQwukaxuXx5pbZEUfOQGSC2OjpF4zfQJ6nyZt7Tni/sKKxKll60vp5TqnQdPxdGcTHNh6hFdpn1Px5OM4rCNWVZTEqAg0zHXk+eh,iv:+zuLDC7UT+E6kK0OAfir6zhLceuUwNACMPgiokmBXxc=,tag:TmmAFvJxLw0sJL+iMRVovQ==,type:str]
    SECRET_GITEA_SECRET: ENC[AES256_GCM,data:gcHgsjn7BN62xQYeWT/qhS7/EQpaxA==,iv:mDatULnf2SOmLNMmfNEBKW+5puKjqETV/ORyemer16g=,tag:3i8Q1DuaIR6XQYnvVBRiaQ==,type:str]
    SECRET_GITEA_LFS_JWT: ENC[AES256_GCM,data:EelIdYP7vostkBXrEUPAqaNysf/3q6u3WHqyJ7IDhzS4dncONfgQT2ZEcg==,iv:Ck1zH6B5l58aE4JGGc5Ct7z8t5/pRUsKDLoEC5++3hs=,tag:tlRp+grm9m0umDPKtZGv7w==,type:str]
    SECRET_GITEA_PG_PASSWORD: ENC[AES256_GCM,data:T2PrhLXtsaA3KmokQEbyqMLt+TW0IWBigI8=,iv:91j4urZmllQjpIDDKrVaICYiTyCrlv9uudql+93VpuQ=,tag:sq7VuTZryOsoxZtOsE5pnQ==,type:str]
    SECRET_GITEA_PG_HOST: ENC[AES256_GCM,data:PZ9fg0wd5CHPhjp/utpRuQ==,iv:gi/kQVScCwuBnabXkQY6ORf9hvwIBCJLeYm1xv1yRbc=,tag:GsYiA26fG1XSYCn53ephEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2024-10-26T13:50:50Z"
          enc: vault:v1:ufa59i+nk7+71VhlBAm3waqYTZ1Xkk1bI3Gpvw9YPOfuJBUUxDtsBqzsjMkPOMz/6B2KEaeGThBqP8V5
    age:
        - recipient: age1h4562p88dlf3mh8v585vuautuae4hs0pvuyeh8wlagplt5dz3yqsgx7q9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR2VwVFlsR0ErWE5hdWVZ
            L3hCZzNuU0xsNERobCs1TDBjbmtPSmZWc2p3CnNZSU8rVEhEaXNEVjF5aHNZTW5H
            ME41NUtNdWZESU4vS2pZWE0ycURlaWMKLS0tIEFEMUxFYmFaNVFZTURPUDFzSHRj
            azBYYVozUFNOTUUzaWZlOEl1UnF3L0UKmjleJy8c8n8ugMKqZWLIE0g8Feg0Ccet
            FbyQNjRAUTgT4Zkp58vkW+SCAMH4q7M/h8/QwRfAE2EL7T6HkLqLpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3emlNdHFGemZTeDRYZ0JR
            QlovWnkwTjhUOGs3VkVGUkM2WDRYQ1B5L3k0CkM5SW45eS8yZXprZHlkdTlGVkhr
            TnIrMEhSdEU2N3dqWW5tYjJIWEp1QVUKLS0tIEZ0NkRtT2FMSzdWUHRWLzM4bTBo
            em9GMVUzQ2FOeW5yRmtWWmJQZ0Q5SWcKU4caP0kh40MNGvN1MDknTGsNXnQbWuTx
            IZucr2TUMcdvnIjL872Gzea/7KtOlKDgWGPfgmhHoA4gJ7H3tUpDqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbWVKWWc2OWtrZFJ5a2lP
            bFkxaGpDaU52WWRLTWxkWGU5d1ZpVWtkQ200Cm92NEN1SWRZQWJGTTJ1TEpRVU1V
            NTN2UXhMWjkwV0xjd21kcFdnSFFTZlkKLS0tIGV3NUUva3ZCZlVOKzdVQW42Szh3
            di9ydmVzUG9lQXlFU3RzUGMwd0dxLzAKAkLbQutVwN4BSsQoqfjI+LQCziaI/UDb
            AVuXm1L+b21nh9sRcRPC407JnYLK3031L5D0tLIbW3XNbV+T6l//+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SnJlZ1o1ZDQ1TEVieXV0
            SUdsWUFZYkcxWnR5VVdpYXpwdk1OakJKZkdBCmY5b2RueUhTZExZRk5zTXhwRmlJ
            YkVkb29udmo4QmVYQ1Z3c09mL1R3aEUKLS0tIHljNVQ3ODViVjNlYXhmTy9vaFNH
            aDN4WkVQUVlzVXJ1VXhXN1RPTXd6bEkKQvdc2lmo1R8UeYKo3kdpY+1fzuvY5g8E
            rVUyt0tL0Y0FT94e5reyQmRchUVKAtzp3RH1ekfNcdWR3fJ763rghA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T13:50:50Z"
    mac: ENC[AES256_GCM,data:Owjf68uWviZOfAZMXMYxpn+OABX0LM3RE4qqrA2GARzov9jAKR9+MReucGANy3N30ZTr2dbPrH1XTmNf39C+eVf1lx4sFrVGRBDD61D/bNxJYZLjAtCUZHvWpZFI+xdQpR81kfOGP1PzLnj4Wt1U96kmxhJgbCgD0dSs48UY+KE=,iv:yZR3Qf+DTaa6CbH8CV+g/yxDzUWaiIsOqPyhHoSqo64=,tag:ppatSOjV1CJGwclQDUHt0g==,type:str]
    pgp:
        - created_at: "2024-10-26T13:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ/8DcglD35v516By3n+J2bT3ZcXWKO9Gxf13cXt+z5jdnWj
            rxEJgR6tObyhn1yvVfeXjqUNGGNCLsRHQ+IxDd+O9QKVUPsIaBQE/d+QeLpLVtqd
            RsQrT/19r9zbziQ2y2Ogy0EBSCywDgHH39812pSBe2UdiLw7rg0ApbON4eHb0a/k
            N2dPAqB0F9G/iyIsXR1TAKudPjM1wI1hOXvNfSXenJabJF3kyL3CEyZQX/O2Q5KF
            rFcDFWD8BKPez2WcxBj9wUun615cjyWH+JoBLI3iYRj9s2q80Z7KHj00uAQsNxsw
            RM8YTl37AgHSwxqNM+Zh9SoJYWUEniXXRBtOxvPxRxoHi8FtTvq4q9ZIJQ0bkkPP
            gH8ljjTwfz90Sik/aEk2p6RY2mGIQGGeEMGh+QivmALcOIKTmhNRx+SItsIeBGRc
            oDez74N04FJbuuwKBOqQ+boB6RmloxX344AQ3PaPPJLg7doG4f2RORuI/rnjnVN/
            LMnR26paIgSD0BRrNn+t+JT/z21NV/Eq7Opv05U0nS3nRPKLEklhosHguO0l/wt0
            j+HnsJtx+bt2n+K3VgHtYGCfxk2wf2lDQNKnbRbbvYDfuPOTD4gfucieXRDVfutQ
            Rc+LGllwF2yTRXXjGlgUUg80vo16coDjRFC87taEfFDwkSFZx/gU8d5AjTMCuLfS
            XgEjUxwRpKqgbds10x55bsvENclUI2yeDhXrJGQXRTloYozOtL5XGig10QEE45/X
            kHpX8WBTTpx2aq06iE+FmuE1krXyTm+8xTbUkE2rBPKi63szemmCakj/+allxus=
            =gRn3
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2024-10-26T13:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAApGs6I/TOIlhRZFibtDc0yWqq5abZJ2r9ATFlpiy1oNeC
            OKZsi/hvApsbkt9UVtHB0woFUp77uGqfFqNyI/2qeRlrdTMvXOAdFB6/d+w3KlD0
            pJq55ezW+iTKYsblkz48aMbXx0oD4mtqCbtF14J3rEVYSOW/hipJjItgPR2np4QL
            BdV03gGv0mLALW+j2+Y/NCyZ6GXbupkrocOeThdpc1q8g+nliCk5UnM2Oo+QHpIj
            5v1+52ACTjQ+AXT8UUBetFk8UcO1SKpdocuVEivq/xHAZscSz8Bisp+RU/93Q5hg
            MnZjbwd4ltBXobWQyLdlC589+kMXItfOYYQiJUzFhMaCr+5uLUOm1koqL6aQONjK
            BIPa+MkoPUlrrFJQBYxnVhj/eGSRhLWz4tLNPguDng8YPIG7p305bBkNbzI7ocYz
            2T/KR2VBDZ7dVQh7xbqzg8fxbzbGuSA1taYqBDtllcHspXlLuV3OHxAY12M+27pv
            9eYrwsjhCXAb7Q+x92F40aav6H2mvor2b6+DhDyMl0ZCyVOfUeOqH0cmplAUv1/Z
            KoWEscbnbhXtXK9B8APQsBxfT9rD7QawdTAaFnibfLO11zmW1u0XpPIZjuGEfro0
            CWcYGecfgBS40bEjUbMzcmwseyUol2q5gdXnfQ+VFbiWDzcmrf/y98EU45gYGdHS
            XgFL6SZonykR+4LyM+pt0Pfy3Gf7qyUsJBOIdQ03R1zBit2rXXrBwqdFHnf2Xaf9
            2gRVfCfRbVykYgSTkdEEyn+dl2tvhtke+WVPzML27ClKawDn6ddFzfh+DEAu2zM=
            =0Gck
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2024-10-26T13:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ//YbJPk7Rcspd8Wkb4c2xgDyoAPgX8HuzrnVOKLLjYH/7d
            oZMBaqX4qTCJRMDAdMO+c6vgUkZuWrffCO+4uPDsRmBqu6RKTfm8CN68NW2mlVHL
            lBsRRi5HW0tuGqEpp3ocoB0TKOPQRxRYfHUHKbzfv1QDRcJKqOUWUMItzBv159M9
            v4wxSdn60gV6SISi3X+tu05FDUTC7h/fSf6L0kVcRbKBa7zbsF2OUigYafhAlTN5
            J4HF1Tbigj6flBRAaKJ2NlAlqATVE4uKZwajNE4YvDThR5hVowHshPDv8rmX0wh8
            nx5maWM/x9b6j+rKnIl7SQ15MmbBaz3VvmYTKlKqExmi6xZBxpO/otm/QTuzhk0c
            v7ptQa+0GjOnJUimSBbruaPX8FxzGJgAi/D47xhBUIQ3QKrVJGsHJw8ODyidKmor
            BViKS6s3e0Vp+SvhDTNW3Wp7TN200ycGSkWQ0+sxI4HUNYEyjvRgH4+df34ilssC
            hgibbufxBdUGfbk6BcC8sYJOZGDeRO18rQEV/2wPKkvDT7tCZ49CHnP5Yc3Zuvv9
            AK7yr5ApcuHirEzxS8ko3tc2BoL0zzKOgIMzZ5G2apR2BOpl2bL+5/XXSrbHRPK/
            KrggxvMLUmfS08Vf0O5eQZeb6ew+q0p3Af3APiw0f0UceYCDd4zbQx9zuCEs9U3S
            XgH7tyEaTclp2xZSelkIbUz/QqwfpaZcPHb+jyTxIyl7DIiHJ0cmQJMz4H6wBifM
            9vdTlpCVg6PdLfg3Yo/Omv0dXFfgNnoSi804CgJNgz/B4F5KF0zRDR8xe23LFQE=
            =1/NG
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
