---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gitea/gitea
      tag: 1.16.5
    service:
      ssh:
        annotations:
          metallb.universe.tf/allow-shared-ip: traefik
        type: LoadBalancer
        port: 22
        loadBalancerIP: ${LB_GITEA_IP}
        # loadBalancerIP: ${LB_TRAEFIK_IP}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
      hosts:
        - host: "code.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "code.${SECRET_DOMAIN}"
          secretName: "gitea-tls"
    persistence:
      enabled: true
      existingClaim: gitea-config-v1
    gitea:
      admin:
        #existingSecret: gitea-admin-secret
        username: ${SECRET_GITEA_ADM_USER}
        password: ${SECRET_GITEA_ADM_PASS}
        email: "${SECRET_GITEA_ADM_EMAIL}"
      config:
        server:
          PROTOCOL: http
          DOMAIN: "code.${SECRET_DOMAIN}"
          ROOT_URL: "https://code.${SECRET_DOMAIN}"
          # START_SSH_SERVER: "true"
          SSH_DOMAIN: ssh-code.${SECRET_DOMAIN}
          LFS_START_SERVER: "true"
          LFS_JWT_SECRET: ${SECRET_GITEA_LFS_JWT}
        database:
          DB_TYPE: postgres
          HOST: ${POSTGRESQL_ADDRESS}:5432
          NAME: gitea
          USER: gitea
          PASSWD: ${SECRET_GITEA_PG_PASSWORD}
          SCHEMA: public
        service:
          DISABLE_REGISTRATION: "true"
        security:
          SECRET_KEY: "${SECRET_GITEA_SECRET}"
        migrations:
          ALLOW_LOCALNETWORKS: "true"

    postgresql:
      enabled: false
