---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
    speaker:
      resources:
        requests:
          memory: 64M
        limits:
          memory: 64M
