---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
    speaker:
      resources:
        requests:
          memory: 25Mi
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - "${METALLB_LB_RANGE}"
