# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-sync-secret
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:7IxM9Lp59U8TcROEqj31npJYNs4=,iv:Lwzz4eG8WNymSuY9qgyaMOVDjo3kM4PR4pb6KNI5svk=,tag:3tgLXeFlKyLqqUICaNvhAQ==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:6x8mi8QmiDA8LJ3JDQNpFNou42jaf9Z7JFqq5n0G3Ok=,iv:9FIjc/1hTs8+Tob6fSYpnqHek6NOKwab92KCdYrMwAQ=,tag:IH0oGIFtyqvcPpwoBRe7Ug==,type:str]
    WHITELIST_LIBRARY: ENC[AES256_GCM,data:b4j6CsKc+QTogMVegte8KhoUdMOM2DK6yNvyYRNB1KSKUmq66e09GUNYoA==,iv:0xBQ8uEtdizkjn+wKLOlaikQXU7UkjdNrGfIzuWRUwQ=,tag:qtCHXkxj/RO082Mp4wD5fw==,type:str]
    WHITELIST_USERS: ENC[AES256_GCM,data:t1sIEpuSO35WTr364JzsIV3k,iv:ebAycK4DY4B8Dcm+JmfZ2UqCxdn5GRqpk961Z5QBfmA=,tag:p2BRkYvSCMCucqAi/YG1gQ==,type:str]
sops:
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2025-06-04T04:26:28Z"
          enc: vault:v1:zpLpO53cG4FneGmzgZEE920ALHp+iarcfUKioOSxpgljRXhRLi/TQrHbsUWbc+NvmgjQU/xsox+9KicF
    age:
        - recipient: age1nhsedg5k84dkmeufjud2g0epwz8dsl2l9qnsrzg0vtwdd9zgkdvsh662xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheGdVbE5RL2tUNmxMVDZy
            YU81UEpSOVBYTWg3ZkZpVkswZ09YTi9aNFVzCkU1cXdkSmllQUdsQUJCQXhNZDZu
            VkdMMXlzSnZHRXBFelNaQTEvTjJxOFkKLS0tIG55T2Z3UGNld0ZqU0Irejc5aE42
            aHJMazZTUGZxREd3SEZZMHozbTNRL00KOWv94HIHJoarKs+CXRXPknfEOsANT9+N
            3KhwZX0uNvfs7D62RqBC8IdV78FvCiFj5J28UngvWu0mgr/02p8HyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS0pRSjVrdkM5NEJLZCtU
            eHdWM3Y1V1MyN2ptcWwyd1NhYTJZeHFXUTFFCm9tTWpLQ0taRVk2NWwzZURCeW8x
            d3FyQWVYbUIrRU92VWtSbVEwTDlUQUUKLS0tIGJuWklVN2IxZUJ4TWN0Z2tNcDhp
            UlM1MXl3ajV2amdhd0JhclBkcEZjNzgKpWTI28FU2oZpOIIMSdwI1LGre0sJho13
            XnzLdJbQ3YF7F0CMkIOEFTPsbjQ1onv2ZwelNVxP04LWYjuPQBFMTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-07T02:38:40Z"
    mac: ENC[AES256_GCM,data:dqkLLBv7RyNJfElIML67zEIIrESIvaFFELMTCQymwZxcmwR63g4Uimq4g8YP7Jgpo50eEILfRNVdp83ijWzsj1S2pJZrG9tcmp1w17DZXiWqvGsNQqi7TWyg+HL0VxMmzxkld6TlMaFI92OoG2RvdLUkkge8t8xzdearA3purD0=,iv:PwAVFHjkQTlWdv7zMyPXcpiCQrJXtkfr3eU2rvWuKdQ=,tag:B3zuVBNPfvaO2kEsxmirVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
