# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-sync-secret
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:7IxM9Lp59U8TcROEqj31npJYNs4=,iv:Lwzz4eG8WNymSuY9qgyaMOVDjo3kM4PR4pb6KNI5svk=,tag:3tgLXeFlKyLqqUICaNvhAQ==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:6x8mi8QmiDA8LJ3JDQNpFNou42jaf9Z7JFqq5n0G3Ok=,iv:9FIjc/1hTs8+Tob6fSYpnqHek6NOKwab92KCdYrMwAQ=,tag:IH0oGIFtyqvcPpwoBRe7Ug==,type:str]
    WHITELIST_LIBRARY: ENC[AES256_GCM,data:56DEQHJh6Wy3NeMv+wXs,iv:vh2mowr57l1b9KYthJaECMleY6MhK8l9HytQLI57Ebk=,tag:RZrq/yNqu15lO+YtfgoJLQ==,type:str]
    WHITELIST_USERS: ENC[AES256_GCM,data:/1qS+Q==,iv:lwns1qQ17rMbc6tK5zAqSzeWiSXoYC36vXrbKah8xk4=,tag:PfXlZ5ezGSTInqwvwXLqnQ==,type:str]
sops:
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2025-06-04T04:26:28Z"
          enc: vault:v1:zpLpO53cG4FneGmzgZEE920ALHp+iarcfUKioOSxpgljRXhRLi/TQrHbsUWbc+NvmgjQU/xsox+9KicF
    age:
        - recipient: age1nhsedg5k84dkmeufjud2g0epwz8dsl2l9qnsrzg0vtwdd9zgkdvsh662xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheGdVbE5RL2tUNmxMVDZy
            YU81UEpSOVBYTWg3ZkZpVkswZ09YTi9aNFVzCkU1cXdkSmllQUdsQUJCQXhNZDZu
            VkdMMXlzSnZHRXBFelNaQTEvTjJxOFkKLS0tIG55T2Z3UGNld0ZqU0Irejc5aE42
            aHJMazZTUGZxREd3SEZZMHozbTNRL00KOWv94HIHJoarKs+CXRXPknfEOsANT9+N
            3KhwZX0uNvfs7D62RqBC8IdV78FvCiFj5J28UngvWu0mgr/02p8HyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS0pRSjVrdkM5NEJLZCtU
            eHdWM3Y1V1MyN2ptcWwyd1NhYTJZeHFXUTFFCm9tTWpLQ0taRVk2NWwzZURCeW8x
            d3FyQWVYbUIrRU92VWtSbVEwTDlUQUUKLS0tIGJuWklVN2IxZUJ4TWN0Z2tNcDhp
            UlM1MXl3ajV2amdhd0JhclBkcEZjNzgKpWTI28FU2oZpOIIMSdwI1LGre0sJho13
            XnzLdJbQ3YF7F0CMkIOEFTPsbjQ1onv2ZwelNVxP04LWYjuPQBFMTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-04T04:26:29Z"
    mac: ENC[AES256_GCM,data:5y87A1gQ6YrH167oA0YqdB0viv3x++ltVFfuJ6Es1hn27eFW4wosqISYrW6IADv2XVYTU0UM5ZSjYkrt2L27dr5xGYZiRXmfDJGVaX33Uo7aG2X4IZ2q4wYqaLkLDl5NGSOqIuiHZK9eMnmG/Z0Umn8Q1yXYWvU/WAIgXsd2DNs=,iv:Wygs2zc3AOHqFL0nLswQIq5fwBRcmW+z/hTUZ0O/1Ls=,tag:uTKFn3n4Y2pWRi7OUVEeWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
