---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M

    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - "goldilocks.${DOMAIN_2}"
        tls:
          - hosts:
              - "goldilocks.${DOMAIN_2}"
            secretName: "goldilocks-${DOMAIN_2/./-}-tls"
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
