---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m

  values:
    global:
      nameOverride: *app
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    nameOverride: *app
    fullnameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: v1.25.0

    strategy:
      type: Recreate

    env:
      DATA_FOLDER: "config"
      ICON_CACHE_FOLDER: "config/icon_cache"
      ATTACHMENTS_FOLDER: "config/attachments"
      SENDS_FOLDER: "config/sends"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      DOMAIN: https://bitwarden.${SECRET_DOMAIN}
      ADMIN_TOKEN: ${SECRET_VAULTWARDEN_ADMIN_TOKEN}
      SMTP_HOST: "${SECRET_VAULTWARDEN_EMAIL_HOST}"
      SMTP_FROM: "${SECRET_VAULTWARDEN_EMAIL_ADDR}"
      SMTP_FROM_NAME: "${SECRET_VAULTWARDEN_EMAIL_FROM}"
      SMTP_SSL: true
      SMTP_PORT: 587
      SMTP_USERNAME: "${SECRET_VAULTWARDEN_EMAIL_USER}"
      SMTP_PASSWORD: "${SECRET_VAULTWARDEN_EMAIL_KEY}"
      YUBICO_CLIENT_ID: "${SECRET_YUBICO_CLIENT_ID}"
      YUBICO_SECRET_KEY: "${SECRET_YUBICO_SECRET_KEY}"

    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          hajimari.io/appName: "vaultwarden"
          # external-dns/is-public: "true"
          # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: &host "bitwarden.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              port: 80
          - path: /notifications/hub
            pathType: Prefix
            service:
              port: 3012
          - path: /notifications/hub/negotiate
            pathType: Prefix
            service:
              port: 80
        tls:
        - hosts:
          - *host
      admin:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
        - host: *host
          paths:
          - path: /admin
            pathType: Prefix
            service:
              port: 80
        tls:
        - hosts:
          - *host
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config-v1
      backup-scratch:
        enabled: true
        type: emptyDir

      vaultwarden-sh:
        enabled: true
        type: custom
        mountPath: /etc/vaultwarden.sh 
        subPath: vaultwarden.sh 
        volumeSpec:
          configMap:
            name: vaultwarden-init-script
            items:
              - key: vaultwarden.sh
                path: vaultwarden.sh

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 2000Mi
