# general:
#     sleep_for: 0
#     verbosity: debug
#     tickle_rtl_tcp: false
#     device_id: 0bda:2838
# mqtt:
#     host: mosquitto.home.svc.cluster.local
#     port: 1883
#     tls_enabled: false
#     user: ${RTLAMR_MOSQUITTO_MQTT_USERNAME}
#     password: ${RTLAMR_MOSQUITTO_MQTT_PASSWORD}
#     ha_autodiscovery: true
#     ha_autodiscovery_topic: homeassistant
#     base_topic: rtlamr
# custom_parameters:
#     rtltcp: -s 2048000
#     rtlamr: -unique=true -symbollength=32
# meters:
#     - id: ${RTLAMR2MQTT_METER_ID}
#       protocol: scm
#       name: energy_meter
#       format: '######'
#       unit_of_measurement: kWh
#       icon: mdi:gauge
#       device_class: energy
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: rtlamr2mqtt-secret
    namespace: home
stringData:
    rtlamr2mqtt.yaml: ENC[AES256_GCM,data:lIDfp4mCymPaAs/sQq27vjOBlw4EZNRGSjxL5byE7a1MqGNgodwkNK/ph87tBwvJNTDEcqXdavhvxgor5iS4OSo3gmkWz1ETK/4akteOYutsyo6j8qXAC36++i++Oc1xTliwolh4WOej1AhBkGnG3odY8AuxFFp1vhyPOyADXTPx8bjqF3B/SEnXjjRFz6WJ1D6N7jnZfmohvxRqe/YXX5jbdE+62rSkbqJZcE3XYG2lQXtHEqkSfc0SNyKL8g+WvCdryl9ksDH/EHOC9GHBCMfTykF+RiWTPYRL/qglxTcffZAQf1GATqcrjtdsm8vVoPQnyLVRbA/JpTyJJYiYRPo7WUujqiLlLWY2q8Ca4VyR20LfLCF49cYKgYk6idrNUqXJ21Ok6fyL1DgX9EwfmmDBsH4ydc/XOG5UidNFNSApIzxUarbcJOmi1NYVvt/sTN3RY9IDJv9EUuaphbXajpjIwIOQ+EYEnXH+BEnnnK6TYDM9m7QHLFX7CBMH/xOmGOw5p0uyZDkuiP86jJVmzJIcpZmYNi8MA772weHcAATrM0PJ0Z3bJsAM+fp7G8aI3sgzdU02Wb7L++Ic29WmlJBFcIqfIhYbaUjEcvRDisuQpQX8190u2PQdJ87olqn7a47CGMlCYHrItslWXYiy9ITAUIll2ovNf1OzwyAU6G3+2qMyKigCwnWr+u/vZ9FoRmU52RK1Zp9GpeTQ6I1gEuFUAOHinFiWoIP01IUjpwVg9X0Lll8akguEA6ryXlzbNB3t82ukgEyd7jwWEmYG+L8gkrOYJJ4c+W1L,iv:6JwtLCMqskExqklAUTz3j0vIrwW2oOsLzqaBNp6a9i8=,tag:Zb0uazBS5GM/CXE5YZTDbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-12-12T21:43:20Z"
          enc: vault:v1:qdNAnXU1Q/X3R2RweuInaU0T8apO2eqVNKS00YxHMzZgBMaW6AiTDEppJ74ww88JrSKCFJe+V6Es7WaN
    age:
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dXBGYjY2NVRvTFk1bzlC
            MlBJWWNnb3FWa1pDU3YyT1BLT1VsZWFqd0hJCitXY21yWWduSEppOFQ2cVlqSGlv
            R01sbUZsbkRaeDVvZk8xN0FPNWtIWXMKLS0tICt1WFE4Skh1dU5SdVU1K3pObVB0
            WVJIYjgvblU3SU50K3hpVnRwN1AzbFEKAfNUaspfiyO3NSYTkACNYmll1NSNxEqU
            Wotl47hWoG5cC2lL3Q/+AwcGBy1AKC0V673ywoSQpmkAldy3GSF3/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M0lIWS9jMDM0MDUrRjls
            d1VrRWEvZ1BLZkxYOTYxSTZVMnVRczdIc0JrClJzTERPV29ra0pFcjVhL0kxdm9L
            S3U4UHJ4RWZmQTloWVZTeCs5OHU2N00KLS0tIFFzejYvRUozVjI4L3FKc2l3MVB0
            SDl6NmVPbmtsRXc4WnpvUWJPdTkzZXcKkKlX51g2RHYBokHyzvlbuvoS70gYIkLy
            qC0sZdNte4xTTRlR+54RmywRNaNG2wmBygEuRtfQIysEh6IWcJR5pw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyclJQY1FGdnl5ZlhlRmN3
            bjlSMVRneUFlM2FGNzVJOG1xaHlrY3g0dmlFCkRzU0RBWG9KckVHeERsMzdlcGRw
            SWFnZlB5UzZORmNzSUFtRldPd0FFNG8KLS0tIHFreDhFZVB3K05YY0pNaHJybGxF
            QWozQlpleVRHSFBXTzg5R2ZFMTY4NmMK1YAWSaoZO5w6DO/9n8IR6/YvGMHeo0Y8
            3o6AYJ2zc9YtLzKVZiBwObOjO26gM7LI3YppZquznBAUHUQW8i15uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T22:40:24Z"
    mac: ENC[AES256_GCM,data:szn+8mc2nkb3LD6lNXMGk1miYN8BvNLONSGpVi6NHEyKoO4OPfoQsqiy7QS5tzYjMknOI4/ORuGUSBzh8tfka/Fnxs0QArtR2FAC6thZegYxzj6VSlxtx71cwgr0wrf5fiSQ1lFs4MBYjoBSuzB380k5oJYRfyvT6T4bCnxzWd8=,iv:VGvLAF+sBjNBsmysTHLkujKvlJ0Bbf2HnxIUF2oxfnQ=,tag:abDgl1W7kKa+Ww09yk5ZBA==,type:str]
    pgp:
        - created_at: "2023-12-12T21:43:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//WFFuI82s99a1k1Fq1n6t2qDJ/0zwRooAAYrRMiZ60kMt
            hShHzyiMq0jc/GtCzjyEyvVYaxENnj4zGku3fXKWrPBEsIB0/UNLzB8urJF7NNGj
            oXzeOajuoc5OYwBWGHwmJLrccoh2u0QJHhBwSYg192BOC6JR5CIsM5+M3gJMTOjq
            CHClC84P8P4kYTtI98DRN46aJfKphGnl/TykLRm1sEdvdFtsVyOOrztOg+yTcWOe
            sy8a1bufkmmQ0SDPsrm5x3+V5599vBmyIXGp+DqRBlOXAChgktS9/IAofabC/7W3
            13G36Zgue+Wx3LO7vDyYidEII5ekUkLvxPCycxzAKtq39SR8z1naKEFwspTxvHxE
            L21nUvk1o+v8NXqfz6PSNSENqWxU5Q8ap3dB1PL7ea1u9qM+cXND4ex7hSelJWJA
            QAeTHiJrug+KXAgImA5QwGiF+4geDfbW134gV2DMQ7Pb4XXH9a5cKLbMkNrAvw/0
            mmXYL2AHk6+NfyYpumdYabIs/xlif+ICPpG2B2J9lDSEFoejW+DcjFb+1T0cbSTJ
            19FYYdHjvq/b0sKbd1R0Ryeu66w65bhO1PbYcjKRFhFV4Svw4pQen27o68tScX0t
            QDCLF4NS7co1GlWBUZDHcwu+jI325cqldELSKoehVJIMecRDXIFAwPv5mB+0qDHS
            XgGV7GPOVf7XJhBiOm+f/4d2YBXIqhQ8vFMJrWGgse6ZPTU1DPmW/Qeiu88FsknF
            L5JIEKMe3+UiBbVIxurcYucZezI1o+k5cYmLqw8BeDIgvY7KNU1cgGjP13WbS1s=
            =pB7L
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-12-12T21:43:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAApcbtNEf1jfCg4/aoOwGmi37+cGNlK4ck4XPJfzIs3ubW
            ng3sjjRv2XrDVeH6TjYmB+1wlgWh8A4vGherg7kq9Hvg2nHZN/FfCljLI2pds4Vz
            ufZ4xWCuM/KyTlY1qTosRHedjKayYPM/C8CTSUvvg3AzwdPGimzHs5p2HU7oLoHV
            Q5LAGsiCPCHUXRPsPEPdF4fZ09MM18j6kxN5jUU4BIwNOTjoxqUFlPtbRd7F9bfO
            D5eZD6fyS/jVxXK1fFXzlStintaYV0ATB4zlsMXaSmQo5559vTc+IgG7WdHKZ/SA
            t3jcZB80V2am4fi5Pu2F+CYfQC9KKKicHLpTasyvPeANsHQlFVdX0L80d0bK0OSg
            yHd5WetOAP64590jCs2T7HBxoij98AcJt/WppFZ86guJX+uN7VvPnWkt2u2SXc4S
            7Yn0RcMNG2VlANATNi8bP/KgOz3PFpKoWYvSk0pml+hZmhC1j9Yov7NsQSKFFCrh
            PkSCE4eh65svOvv1buC/ZN1q288GvquVAUJdD+t6LJPB+EjJQUZ3iL4PSzkxwn4w
            VVbaJI5pKQwUMLxF/sn9CCJ+5uOnLIgDeqE2llRZFeUBfOYDldOnAudr4xw7mLc6
            Z0xPl2VxkUTpsGi4sWszFIB8pYz/f70WR5LMUDjCcX84OBd9j8GByPiOqWLAl0rS
            XgEbn1gKNWdLg1T3yhy6Q6/QRt3ZoQhwKpQAiIPZwSzzLXffwGhsNfwBITntJjXk
            KYU5bG1oJ9tX51IjVkeyeZmNw2Afk0+OkSA9eszwXLYl3XoMa0Y1uLK1aLrbufw=
            =TzJw
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2023-12-12T21:43:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ//V6hxzCdn4pCPnSSnpojZyT6xFT2gTtBXmf0UQVAOXXk3
            oHcIRaWlLQmlHnAh8JmvkO34fQp+58vMqZVkzkOe+0wmALEH7+8L/sKKVHbfQC1c
            fdDYiZ1s8kyR1Sq4YCGmUlF8KugQiUPtM64jL2sfFk+43yrtI91uOiP7jkJ/TcE9
            sjGlwS39qC5yWqAM84X0JougR3Ei/Hu4oZjT+Kxkb4MxCYPJxMW/l+JKrbNROHfh
            /PslhIX+yFOyyfnul3216l3Fq/viVJb81f/PuLeRy4JjtIyG1siR5t6lff/ZqFTn
            E1mgpHIoZmIyygg5mwKDsXpioOme0nWhnSrN9Av8otqFFAc/K/9mEqI8cAsCGvI6
            eEjRF0etCJPAjqM4YNvtSLZmndhMAwn2rGDu8jwB8aZzmc4eslI/9cWMkbKi3S8J
            Cy+FJ/CCtsXcYpl47bIfHhXCX9bkx1hQYopMuZ+15k5So2pEflI3qhrIxUBqM3sZ
            axenCItw8nfVEsK36Ua4Hh2TRGX7Oq7wYzMU8//kCq1axsKQEiz/NFR29NhkwiFk
            m7j69jbfRbpU3KkIJq5Alhpe/+MaNFXtj1ssXNYTImW3pubjVFnlBjsvs1NcIRiD
            iioQSNkHXlvEX190b9/2seCNI9Ovtz6kKKc9/HIiwGE6xwoLLIVpzWdVJuj1hSTS
            XgER2kapmhW+GufYD0eTg8kGA0r7pr4t721PbxbcufiDUGjC+po10AUQXCbP1Tfz
            9rPdoezs4ie+dwNSFIoRq8Cg7JoWFlfzM/6I+YGUsJZCY4oUXp0+mkwGzKl8tW0=
            =fcl+
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
