---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.5.3
    tolerations:
    - key: "arm"
      operator: "Exists"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
    # env:
    #   SPEEDTEST_SERVER: "server
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9798
    resources:
      requests:
        cpu: 15m
        memory: 50M
      limits:
        memory: 100M