---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app network-ups-tools
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/jr0dd/network-ups-tools
      tag: v2.8.0@sha256:8878ab0f9420801f110ba1f173c97ad056cd9a6f56b181e1b39add1d91dc9626
    controller:
      strategy: RollingUpdate

    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        ports:
          http:
            port: 3493
            protocol: TCP
        type: LoadBalancer
        loadBalancerIPs:
          - "${LB_NUT_V4}"
        externalTrafficPolicy: Local
        # ipFamilyPolicy: PreferDualStack
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LB_NUT_V4}"
          external-dns.alpha.kubernetes.io/hostname: "exporters.${DOMAIN_2}"
      metrics:
        enabled: false
        ports:
          metrics:
            enabled: true
            port: 9199
            protocol: TCP
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        type: configMap
        name: &config network-ups-tools-config
        mountPath: /etc/nut
        defaultMode: 256
      ups:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb/001/099
        mountPath: /dev/bus/usb/001/001
        readOnly: false
    configMaps:
      config:
        enabled: true
        # See https://github.com/networkupstools/nut/tree/master/conf for config sample files
        data:
          nut.conf: |-
            MODE=netserver
          upsd.conf: |-
            MAXAGE 20
            LISTEN 0.0.0.0
            LISTEN ::
          ups.conf: |-
            [kubernetes]
              driver = "usbhid-ups"
              port = "auto"
              desc = "Tripp Lite 1500VA SmartUPS"
              vendorid = "09AE"
              productid = "2012"
          upsmon.conf: |-
            MONITOR kubernetes@localhost:3493 1 upsmon secret primary
            SHUTDOWNCMD "/sbin/shutdown -h +0"
            POWERDOWNFLAG /etc/killpower
            POLLFREQ 15
            POLLFREQALERT 5
            HOSTSYNC 15
          upsd.users: |-
            [upsmon]
              password  = secret
              upsmon primary
              actions = SET
              instcmds = ALL

    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-tripp-lite-ups
                  operator: In
                  values: ["true"]
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists


    resources:
      requests:
        memory: 64Mi
        cpu: 25m
      limits:
        memory: 128Mi