---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: falco-security-charts
  namespace: flux-system
spec:
  interval: 120m0s
  url: https://falcosecurity.github.io/charts
  timeout: 3m