---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgresql
  namespace: security
  labels:
    kasten.io/backup-volume: "true"
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: longhorn