---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "domain2"
  namespace: networking
spec:
  secretName: "domain2-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${DOMAIN_2}"
  dnsNames:
  - "${DOMAIN_2}"
  - "*.${DOMAIN_2}"
