kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:DYL+4tAsCajfqMovf+hMH+zX03gxyQ==,iv:QpWwLRB7vRjFhguQQd6pNrJfbrHoslfSGvUd2UCLk9c=,tag:OF6OTk830exgvGshHlNOpg==,type:str]
    FRIGATE_CAMERA_AMCREST_PASSWORD: ENC[AES256_GCM,data:JfA2cGpRZuhElk6EGlbuIKNtfAXfZQ==,iv:xMdCDCVs77asRcs8P4TVaWdwm6xghqDpdK2NcfRQhOA=,tag:0v91d8VHHhLRLleeev2yXg==,type:str]
    FRIGATE_CAMERA_DOORBELL_HOST: ENC[AES256_GCM,data:dkIIA0y8b3Lu/kODUA==,iv:CvzwVkMz9dbAssE/pDdJQZNqpTq1sHnBBhIuBqmO+ek=,tag:BsI9sguN3UclpB04ijy2Kg==,type:str]
    FRIGATE_CAMERA_DOORBELL_USER: ENC[AES256_GCM,data:11sBkgs=,iv:2CbYw4hXJLY5JlfI6X3TqMnslqc/xvi3WTSPGnDU+VM=,tag:KYUd9q3fo72RK2vH6rXmBA==,type:str]
    FRIGATE_CAMERA_LR_HOST: ENC[AES256_GCM,data:BhWMAsgISQ2/QjcU5A==,iv:xYcL5nQfqhB4xr5G9ct66an6OGWCvqEVBpOhE6/YDr4=,tag:1hRZ0lN6O8BE8WySg27JfA==,type:str]
    FRIGATE_CAMERA_LR_USER: ENC[AES256_GCM,data:zhlUq9mEEw==,iv:szdndbcLV/ZOF0eqg2y/Mjvow4yF9k4b9jPqxwAKHkI=,tag:QRvD0W6E+fPU7xrBNO2FVw==,type:str]
    FRIGATE_CAMERA_ATTIC_HOST: ENC[AES256_GCM,data:d/l2lBMpAY4WmdoPhw==,iv:1NI25O1cOm2K2Bx6JYPbjkUFW+6NoG5B6ed9SdxG5B8=,tag:luFS8G/sIm5x1Qk2GCCNPg==,type:str]
    FRIGATE_CAMERA_ATTIC_USER: ENC[AES256_GCM,data:tVT6UTXabQ==,iv:hfC/qAX6ov+rCCDbbf3g3H9PcHiSihCi8XUTrlnDgiU=,tag:ixnRjH68dFH45/NpRPQD7A==,type:str]
    FRIGATE_CAMERA_SUMP_HOST: ENC[AES256_GCM,data:z3i6f400lphHZD5t,iv:Lav0gC3V9wO2clgeUMDVOoZj5tCUSLMwJraOoYL5xQ4=,tag:ri10Lm5Fgbt3cT+L3J9uGg==,type:str]
    FRIGATE_CAMERA_SUMP_USER: ENC[AES256_GCM,data:44LaAQ==,iv:nRqiWfQQ0nIGZkagrXnzUqQ30BcsRd7Dq3bLg1DVFYw=,tag:mcqfzElvLF5l5ecoNEGZKQ==,type:str]
    FRIGATE_CAMERA_SUMP_PASSWORD: ENC[AES256_GCM,data:WMbZMeUY5jU=,iv:rqvUF1G8vzZwa3Uz/9hsrqt+c03K15X/VGjNGdm2k2U=,tag:ZVC7UR60sG6Qfj6u/+15/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2024-10-26T13:50:48Z"
          enc: vault:v1:8x6t0JVPm9fXQYiwG9NS8nITzobTVZsusb2T6OVk8kxv7qZhCP7d1ooZ1zqCnD6DzW2P7R/1dhl04jko
    age:
        - recipient: age1h4562p88dlf3mh8v585vuautuae4hs0pvuyeh8wlagplt5dz3yqsgx7q9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVUJaVWVPOHFFVU8yeE5j
            S3pYMGpoY29WaEtxN0dVSkF3M1FiODZCM2xBClRaMjNqU3VMbEVZMkRtMSthZE9p
            R2NNYnlxanN5eVRLRU14NEpmMjIyN1UKLS0tIFN6R1pxVTBZeVAyNkxGd203RzBD
            dlpWTkRZbzRPVUxmSkYvaUlVdkNCUTgKG0SGvhKZ2R6/L5tolqOLcYJ7y/45UqiW
            eVVtF2IFZ2F+qcmEo6B8ui2HEgJy1uJwx6+M4qAa+WMpqkfR4Vdx/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdklZZW5RaDBuSnh5ZUdq
            VkJQQUtMdVlBT1dTOEZIK3NvNWRWMDJ2VmpzCnVHNi9EN1ZncjNtbXpZbGdISWo2
            WTR4Ly9jSzhBdm5pMEk4L2VCTklwYXcKLS0tIGxvaGdFeitqeUZDS3ZYRzZySmRn
            QktHUlpSMWdSM0p4TnY5TUdMNzcrWWMKuFDeYXdMdrm50is7u11zUI+PLRaagoVQ
            e2beppwkKehLllsZ5KmotLlS6sOw2N1gM3sQ8WyV7KZtmC2m3QMHKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QmRuNWY0bWREQmFuQVFU
            R1BndVE3bnUvKytRTERUUElYVVh3azZrSUVnCnNGV2FLWE83MS9KMXEzaEs5Rm8v
            Q3ZkZ0NRLzA2S0YwVFRMRlI1SGRCbWsKLS0tIHFMenNOWXo5VTMxcGQ3dkpvcElj
            WHJ5eURLSU5kR2tDbXBvUzl4dUlYb0kK6b6afbXCgVDexHRTMvS4FwsuWn8rT6Df
            jeZgb27wIQsTiw8QPdt/lDyraUspeA8GT5RwrJgyIPTWmw1HU2uuyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TDdaR3huUVJlRFNYWnFI
            L1hDL3QzN0pxa3NpMFhPeXptdStTMEZUUTJzCnVUdzdudTJEOFhsOTk3amtxd0Jo
            WlJWazROZUc2TW9EblIzamJwa1pHdWMKLS0tIEtYZHJaNklTMis4bmhGVXdUVStO
            b2RpTTFUdUgxdW9BRVFkbi9HQ2cvSkkKqYmcwk9qpYtwet3u6WUzUzzH5T8co5Dw
            Axgu5D1vzti7qRkE2LEN43sbp/g8en5PVO2kjHYSxW+XTJ4MTwT3ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T13:50:48Z"
    mac: ENC[AES256_GCM,data:iox7eEmCxaTpJMZCV5e249oSogRL7rlZB7gIqt9VH4OLDDuupHGYE+ZbuK0En2sQOijWe+HMAPQ0ntwmTyXrX9+8eUvjwQcxUqRwt4xxEIMEX7ygq1odihBnDda2OorSZIZ80a+r+7xf6J4tu8Sv+qzwgYcohRy4M6qi/738hN8=,iv:TtO74FNCBmuitrK4Y4xe3iiX3JT6MLJhC+9OIZ4LfQ4=,tag:HDgkhtJ+hk6T1gUISpjliQ==,type:str]
    pgp:
        - created_at: "2024-10-26T13:50:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCARAAlhh6kbn2flBy6sJ+ZGVVjayvlo1GvYFYJVOsfXtUtjgo
            1CUOSUaS1CXuKwC4rL0Gh71EjfYLbcasu5x88K/34qmN4HfOQAsl/Kgowi0Oi2Wt
            Q0JNH/oRyWECjlNcRYzjHUlIOmvGTxlYpu9W8pxMMnEyfISF8jREk7mNPA2EYZqq
            HsvgFH+pxnoWjR2EjCZC31/AWkVc87bOwB5+1rWei8Z5TQ1Xf31t+/CX320+S21l
            JnUExd05wM50u5oA4YxW+YObA9yIVxx7yPXn1DNEKVbL3YlEnW3Z+FO3wVVfPq3t
            LySIJZPQocO+iohl1aSls+s49JiUanOX52gMcowGKzSH2JrV32MYW8EMhYp+sSqT
            uXZ/j6hmiur4sZnd5rGy6hGywKh2JQ437mNiqkrB0+YZzZWLgSzoGaCRDxzEaYQR
            9rs6UhXgdZoAsyiipe+hzQXtiC12wfZZ6Ayy7n2hIOyC0Nyk27zbOsKLKTtSR+g4
            vI9fu/h2ZlgFVGbp3NjNQUf3sYR7NNtSBlqz1fKSFt33pHMwBNH5UPW9DqM/a0Z3
            KLQ6UYf7TaDprucl3ysYkPUvXeQl/j2JJG7RVtRVQTX5nO5ElGnrzCOxqw7WiSxX
            Et/FSKLItPM7EifZrdJ8rs9NoPLVTqgCuZCXqdvq/Z2nmZiLUyslHua8bVkZsRfS
            XgEIwgQC96TcQHdOTgCxSZGWCs7Fd/au0liwhMC7QFzwFdPGZSfUssO53zKdkjDE
            6DM7aO2eottv3EhDZnIP4Z30DJ30b02vQjGBmTFD+avip3fR3xnDfWnMlNMa0/s=
            =2qEQ
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2024-10-26T13:50:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ//SHZyUevWSwnObS0KJECrqiu3M1ja8hWj507CcrmRVwRW
            v5sW65r2QK3ed0/ZF07bm9puXwIyE8z2HhuoYR8c+fK3yIgRzgibw0qChJLWiYU9
            CgiA9xKetF82tmEPnf9VGOlnc6E9WJI0hHI0eJycyaQ+o58+qW4U4Xc0++BoLizr
            RUbjdY40DutYtyksTHkW8/2GZRKfbxYt9zc9jfKmQ2Fl1pXC1e4Xm37MKl8bGmKJ
            ZdZBQ45rTnuRf/gApyF0vzki9PuzVtl/2UEdxkQMUWT/r3s4iMQZQ24XZvh4QDjA
            fvT4jy/zR8DKn4A+s6vogMjqyNvPTJIb5Zv5ONEPC4uvO+l2ghBEd8qce1z4MxKg
            65crDuSXHjzpSDeJWTT/s2Gj8uJlGonEApbHCZg0ehhBQm7l/g7mbFFT1pBjzIsB
            gEt1KS0yCOqnsEQvc3ESlntg6etOk62Hn6y1CIqi/juhntiqmKXvVouLYNyOBhgz
            Yp/iziA+A0hjUFld/LTuJ46GCLS8N9Xn3z3zQ/tGa52XbnN5l2Mm+mvd3v679U8P
            4n/2F1yAFfj44llBoouREGp6MplYvjiyNrACjcDbHPZCLm7sBiiPAmZaIuLxmk3A
            npAw2oUxC4B+bsIe1VkYiAdQEpJyzPFzsYWfDRy8T4Io19V04FrJKdTHrB6XcknS
            XgHNQUxAee3JE3jsBb94B37ALq+Ihur6prhRMIMDQUOHXt2wUwDgdzVNb29CGpUf
            1odx3y/RMZ6FQel1EEIMSWBySRxeucvtIfY9v6DNTAYijZngW02QMV/ylIw0I+E=
            =x0mi
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2024-10-26T13:50:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ//dPa/a9558/XgtL3/8cAItA9mS2V8JTCvNq8T9VYvIjcx
            q0Dm+0Tk0eMZjLvByyJekmqs7yWD+GEDWCq6p2st9IzWteCcvo/5ZFWMn5B3O0lZ
            QqVJxmhAVYFY+Cyaw6jMwpcNvpridO3p19yXRoZG1D204s7AzIeiVNw6L01iIOmq
            Tg3zEcjgB5GeGP1wzZsBAXc+ePFJgTMAYOaEuSzPQsijoJvH6n/Ml4sHgpsPDyb3
            gkE25J8XGfPTB4Zl5E4zqLXj2SGdsPvTfJ0tTIQ6MXo8nsmXyyEcoEMiOxpk6B3Y
            Yc3oblTs6Nu8rqqX2ZQRCQ3XHdGzwXjdRBs8AOgt7Zqi+PLVsxeusSj8mXkmiiJD
            ktPDBnHGaLV0yxw2bkh3V0ExsIRi9N/5Q6v/PEuX39OG07g9qirmcp9od4IEiZHv
            sMv26ixpHu2reH+nQyxWnGF+YYr3ib62lYfwK3YxnVvmTAZmhIfSEQtGeOsua4Sq
            SyYnbp/nMWkbI8b4t+lslQeI1noLy/XPq6sZw/NYELaontK6skS4JevDygBWtZpW
            m8F2gw3CZqP/Wj88xOB07031Qyi5Od0EeesAh0X1JDdVjTQFZJiwRqMdCvxfLIDw
            rcKk496U26lkB70SNXus+BTbHYhoj/xJ7gL9XLZhCdjsC94hXlgqANOKRrSf05fS
            XgF6BzOWXiEYMgU8X+onhh0q1+6BJDvpmd+jfogVhJ/8tnMz3ro19X1s5lY7Sjnf
            cH6bX8Ue3tXDMI1g+kjUOTn2+U1FcnFpTM/YI3m9yR9kdlGaTRD6Nxv8dqpL73A=
            =q2jp
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
