---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.9.2
      sourceRef:
        kind: HelmRepository
        name: rancher-server-charts
        namespace: flux-system
      interval: 5m
  values:
    hostname: "rancher.${DOMAIN_2}"
    replicas: 3
    ingress:
      enabled: true
      tls:
        source: secret
      extraAnnotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
    # extraEnv:

      
