---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app esphome
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m

  values:
    global:
      nameOverride: *app
    image:
      repository: esphome/esphome
      tag: 2022.6.2
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd
        hosts:
          - host: &host "esphome.${DOMAIN_2}"
            paths:
              - path: /
        tls:
          - secretName: tls.esphome
            hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config
    resources:
      requests:
        cpu: 15m
        memory: 512Mi
      limits:
        memory: 1024Mi
