---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-ui
  namespace: home
  labels:
    app.kubernetes.io/name: &name zwave-js-ui
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block