# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:R4u0JgIUbbaNz6F30qOgh3+oO/3C2V/9izYAw12k1KU=,iv:vc86Z4jo+0Zp3otIfkT93tkFW/EGoy8g3aF1Kijvk+c=,tag:UruMtCIVdqfsr5VbEL+O3w==,type:str]
sops:
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2025-05-04T03:59:13Z"
          enc: vault:v1:IqgY/ycFDSScWIJBjmLYBhmrKE2rbfqrj5CFRt7OIwik46BgcAJQDZ0Qb5BQmz0eKulG9tvOt5BMNHls
    age:
        - recipient: age1nhsedg5k84dkmeufjud2g0epwz8dsl2l9qnsrzg0vtwdd9zgkdvsh662xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdms3ZHZwNjl3M1pLT3l5
            MXpwdzVrZ3o1VDl6WHM4QVo3U0lNblNPbHhNCmhlY01zNEh6ZDAzTXJNNlRnWEJr
            a2hmTzhHUnpEUmpzbjN5ZXJkT1pCOWsKLS0tIEk3M0FQblZPMHNZWGJRdFlyakpO
            aWp1WFdzeTRKdzh0YXBSQjIwLzAyVlkKmgWSuA5i76JtaI8QjTLiM29Na8knGOXw
            Ck9Pjki1Fxjb5SIUB5G0JiO36qmb4DljFvF70VHHiTra2OZXBSrssw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaDRFQTNubU5KSTB5Kzg3
            d1FZaGpabXFURmFrOXRId1grSFExTS9OTGl3CmRBdmdJakQwNDZYeVJ3UzM5S1Qy
            M1ZNYlZMeXdvS0ZaaGRjbkNEd25UU0kKLS0tIEtkRVNKSmd6cEVvVC9Ydks3eFVG
            WDYyU1o4RklNOEFuZkRkUTExeGNOT2MKpanVhqOhI+lAZB8NqQF3oSyInsDy44j+
            orSEVfZTpe1d6EPM5hc/XPdU321cb3SkM0SJJ8SWuHRdltKef1TaUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T03:59:14Z"
    mac: ENC[AES256_GCM,data:a2cIdHaSemBs/fR0gLUKXgI8kiQuHa/JOBy6eyYIJFvCoezgIlXpaZPOZ/DoZxNnSZSl4CdvxzGJzMQby1BdQUwhYkmsJ7C+dq58wS2XDnBoV/BRAWvEyZn9rYpL+ebQePfFQoX/QjI6aYpB7PI03mtdgA3CDtVPsow+h4A6K7M=,iv:afklfdVfWIbGp2bP3OTvRa6vGnl7zpLnmvt06kW9gzQ=,tag:kY5NJHUNscWdWBJYkdBujQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
