---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/stable
      chart: rancher
      version: 2.6.2
      sourceRef:
        kind: HelmRepository
        name: rancher-server-charts
        namespace: flux-system
      interval: 5m
  values:
    hostname: "rancher.${DOMAIN_2}"
    replicas: 3
    letsencrypt:
      ingress:
        class: traefik
    ingress:
      enabled: true
      extraAnnotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
    # extraEnv:

      