---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: monitoring
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        type: daemonset
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule

        containers:
          main:
            image:
              repository: docker.io/timberio/vector
              tag: 0.46.1-debian@sha256:ccf9c8ffcd1ffbe59e4d62bf44926664908ea1cb6b492b91634d1afd01e3376f
            args:
              - "--config"
              - "/etc/vector/vector.yaml"
            env:
              PROCFS_ROOT: /host/proc
              SYSFS_ROOT: /host/sys
              VECTOR_SELF_NODE_NAME:
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.nodeName
              VECTOR_SELF_POD_NAME:
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              VECTOR_SELF_POD_NAMESPACE:
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
            resources:
              requests:
                cpu: 23m
                memory: 249M
              # limits:
              #   memory: 918M
            securityContext:
              privileged: true

    persistence:
      config:
        enabled: true
        type: configMap
        name: vector-agent-configmap
        globalMounts:
          - path: /etc/vector/vector.yaml
            subPath: vector.yaml
            readOnly: true
      data:
        type: emptyDir
        globalMounts:
          - path: /vector-data-dir
      var-log:
        type: hostPath
        hostPath: /var/log
        hostPathType: Directory
        globalMounts:
          - path: /var/log
            readOnly: true
      var-lib:
        type: hostPath
        hostPath: /var/lib
        hostPathType: Directory
        globalMounts:
          - path: /var/lib
            readOnly: true
      procfs:
        type: hostPath
        hostPath: /proc
        hostPathType: Directory
        globalMounts:
          - path: /host/proc
            readOnly: true
      sysfs:
        type: hostPath
        hostPath: /sys
        hostPathType: Directory
        globalMounts:
          - path: /host/sys
            readOnly: true

    service:
      main:
        enabled: false

    serviceAccount:
      create: true
      name: vector-agent
