---

#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#globalcluster-variables
#

# Use a specific version of k3s
k3s_release_version: "v1.26.8+k3s1"

# Install using hard links rather than symbolic links.
# ...if you are using the system-upgrade-controller you will need to use hard links rather than symbolic links as the controller will not be able to follow symbolic links.
k3s_install_hard_links: true

# Escalate user privileges for all tasks.
k3s_become_for_all: true

# Enable debugging
k3s_debug: false

#Enabled embedded etcd
k3s_etcd_datastore: true
# Enable for single or even number of masters
k3s_use_unsupported_config: false

# Control Plane registration address
# ...this is set to my kube-vip address
k3s_registration_address: 10.24.0.200
k3s_additional_registration_address: 192.168.24.200
k3s_dns_registration_address: "k8s-control-plane.rmcd.win"

#
# /var/lib/rancher/k3s/server/manifests
#

# # # Custom manifest files
# k3s_server_manifests_templates:
#   - "calico/calico-installation.yaml.j2"
#   # - "kube-vip/kube-vip-rbac.yaml.j2"
#   # - "kube-vip/kube-vip-pod.yaml.j2"
#   # # - "kube-vip/kube-vip-daemonset.yaml.j2"
#   # # - "calico/calico-bgpconfiguration.yaml.j2"
#   # # - "calico/calico-bgppeer.yaml.j2"
#   # # - "home-dns/home-dns-rbac.yaml.j2"

# # # Custom manifest URLs
# k3s_server_manifests_urls:
#   - url: https://docs.projectcalico.org/archive/v3.25/manifests/tigera-operator.yaml
#     filename: tigera-operator.yaml
