---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-config-v1
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client
