---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app kopia-sync
  namespace: services
spec:
  schedule: "0 */12 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 43200
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-repo
              image: ghcr.io/ryan-mcd/kopia:0.14.1@sha256:e8a08d734a54a9a15a82d8e65a88af35effaa34b67d8ac8a9faf0c4030e88b08
              command:
                - /bin/bash
                - -c
                - |-
                  until [ -f /snapshots/kopia.repository.f ]; do
                      printf "\e[1;32m%-6s\e[m\n" "Awaiting for the Kopia repo to become ready ..."
                      sleep 1
                  done
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
          containers:
            - name: sync
              image: ghcr.io/ryan-mcd/kopia:0.14.1@sha256:e8a08d734a54a9a15a82d8e65a88af35effaa34b67d8ac8a9faf0c4030e88b08
              env:
                - name: TZ
                  value: "${TIMEZONE}"
                - name: KOPIA_CACHE_DIRECTORY
                  value: /snapshots/cache
                - name: KOPIA_LOG_DIR
                  value: /snapshots/logs
                - name: KOPIA_PASSWORD
                  value: "none"
              command:
                - /bin/bash
                - -c
                - |
                  printf "\e[1;32m%-6s\e[m\n" "[01/03] Connect to repo ..."      && kopia repo connect filesystem --path=/snapshots --override-hostname=cluster --override-username=root
                  printf "\e[1;32m%-6s\e[m\n" "[02/03] Sync to remote ..."       && kopia repo sync-to from-config --file=/remote/repository.config --parallel 8 --delete
                  printf "\e[1;32m%-6s\e[m\n" "[03/03] Disconnect from repo ..." && kopia repo disconnect
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
                - name: remote-config
                  mountPath: /remote
                  readOnly: true
              securityContext:
                privileged: true
          volumes:
            - name: snapshots
              nfs:
                server: ${NAS_ADDRESS}
                path: /mnt/user/k8s-bak/kopia
            - name: remote-config
              secret:
                secretName: *app
