---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tautulli
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/tautulli
      tag: v2.10.1
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "chart-bar"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "tautulli.${DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tautulli.${DOMAIN_2}"
            secretName: "tautulli-${DOMAIN_2/./-}-tls"
    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config-v1
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/k8s-bak/tautulli
        mountPath: /config/backups
        readOnly: false
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 500Mi
