---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${APP}-restore-snapshot
  namespace: ${NAMESPACE}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: ghcr.io/ryan-mcd/kopia:0.15.0@sha256:a37a4eadefc8a6693f6dbeead47d796a165b3ada5dd33438c5ecefd67724d1c8
          env:
            - name: KOPIA_PASSWORD
              value: "none"
          command:
            - /bin/bash
            - -c
            - |-
              shopt -s dotglob
              printf "\e[1;32m%-6s\e[m\n" "[01/04] Connect to repo ..."      && kopia repo connect filesystem --path=/snapshots --override-hostname=cluster --override-username=root
              printf "\e[1;32m%-6s\e[m\n" "[02/04] Remove previous data ..." && rm -rf /data/${NAMESPACE}/${APP}/*
              printf "\e[1;32m%-6s\e[m\n" "[03/04] Restore snapshot ..."     && kopia snap restore "${SNAPSHOT}" /data/${NAMESPACE}/${APP}
              printf "\e[1;32m%-6s\e[m\n" "[04/04] Disconnect from repo ..." && kopia repo disconnect
          volumeMounts:
            - name: ${APP}-data
              mountPath: /data/${NAMESPACE}/${APP}
            - name: snapshots
              mountPath: /snapshots
          securityContext:
            privileged: true
      volumes:
        - name: ${APP}-data
          persistentVolumeClaim:
            claimName: ${VOLUME}
        - name: snapshots
          nfs:
            server: 10.11.1.111
            path: /mnt/user/k8s-bak/kopia
