---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  values:
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.18.0
        env:
          TZ: "${TIMEZONE}"
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
            cert-manager.io/cluster-issuer: "letsencrypt-production"
          hosts:
            - host: &host-config "hass-config.${DOMAIN_2}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host-config
              secretName: "hass-config-${DOMAIN_2/./-}-tls"
        volumeMounts:
          - name: config
            mountPath: /config