---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app glauth
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/glauth
              tag: v2.2.0-rc1
            command: ["/app/glauth", "-c", "/config"]

        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            memory: 50Mi

    service:
      main:
        ports:
          http:
            port: 5555
          ldap:
            enabled: true
            port: 389

    serviceMonitor:
      main:
        enabled: false
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    persistence:
      config:
        enabled: true
        type: secret
        name: glauth-secret
        globalMounts:
          - path: /config/server.toml
            subPath: server.toml
            readOnly: true
          - path: /config/groups.toml
            subPath: groups.toml
            readOnly: true
          - path: /config/users.toml
            subPath: users.toml
            readOnly: true