---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kopia
  namespace: services
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    initContainers:
      wait-for-repo:
        image: ghcr.io/ryan-mcd/kopia:0.13.0@sha256:37126186a001dd8963262ee045b7f21c9f6f40c4c1de275a17100487f3cf93d2
        command:
          - /bin/bash
          - -c
          - |-
            until [ -f /snapshots/kopia.repository.f ]; do
                printf "\e[1;32m%-6s\e[m\n" "Awaiting for the Kopia repo to become ready ..."
                sleep 1
            done
        volumeMounts:
          - name: snapshots
            mountPath: /snapshots
    image:
      repository: ghcr.io/ryan-mcd/kopia
      tag: 0.13.0@sha256:37126186a001dd8963262ee045b7f21c9f6f40c4c1de275a17100487f3cf93d2
    env:
      TZ: "${TIMEZONE}"
      KOPIA_PASSWORD: "none"
    command: kopia
    args:
      - server
      - start
      - --insecure
      - --address
      - 0.0.0.0:80
      - --metrics-listen-addr
      - 0.0.0.0:8080
      - --without-password
    service:
      main:
        ports:
          http:
            port: 80
          metrics:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: false
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "kopia.${DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "kopia-${DOMAIN_2/./-}-tls"
    podSecurityContext:
      supplementalGroups:
        - 100
        - 65540
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: repository.config
        mountPath: /config/repository.config
        readOnly: true
      snapshots:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/k8s-bak/kopia
        mountPath: /snapshots
        readOnly: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 30m
        memory: 450Mi
      limits:
        memory: 2000Mi