---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system
    - name: node-feature-discovery
      namespace: kube-system
      
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.27.2.5929-a806c5905
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
    service:
      main:
        type: LoadBalancer
        annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: https
        loadBalancerIP: "${LB_PLEX_IP}"
        externalTrafficPolicy: Local
        primary: true
        ports:
          http:
            port: 32400
      dnla-tcp:
        enabled: false
        type: NodePort
        ports:
          dnla-tcp:
            enabled: true
            port: 32469
            protocol: TCP
            targetPort: 32469
        externalTrafficPolicy: Local
      dnla-udp:
        enabled: false
        type: NodePort
        ports:
          dnla-udp:
            enabled: true
            port: 1900
            protocol: TCP
            targetPort: 1900
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /mnt/user/Media
        mountPath: /media
        readOnly: true
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/k8s-bak/plex-backup
        mountPath: /backups
        readOnly: false
      transcode:
        enabled: true
        type: emptyDir
      #   medium: Memory
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 800m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 4000Mi
