apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: media-backup
  namespace: kasten-io
spec:
  frequency: '@daily'
  retention:
    daily: 2
    weekly: 2
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - media
  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - matchExpressions:
          - key: kasten.io/backup-volume
            operator: In
            values:
            - enabled
      profile:
        name: nas-nfs
        namespace: kasten-io
  - action: export
    exportParameters:
      exportData:
        enabled: true
        overrides:
        - enabled: false
          storageClassName: nfs-client
      frequency: '@daily'
      migrationToken:
        name: media-backup-migration-token-ml7g7
        namespace: kasten-io
      profile:
        name: nas-nfs
        namespace: kasten-io
      receiveString: bIzAPpoanmFRkXtokRRIiuZBY0kaDhWI2DaPw2A2QZ4cLKd5vnqsYp2oYMuOle0dGSDezKuNGU+u7zELhTr9qw4piTkoCv+TYKyCxNaW9o+X9IIr4EQREkyn79fXC4FuT5MAhmMShrVKmbOQ7NyRmgKyM9LszmJ8zVfOHA6Cz/2N8qgYKEawiCSzmnnDMRFW/bxxQ5SEn01y00o3MTiL9929XXSzHSjrpihO/IrbWJdep4bOOnTYbsUDs6SuidqyZJbfIPjMK9NzS3Dooksp7mDI4OOZKrOO1lXSTj4nHjUrUimQ9j1ioSP25I+apIQ0khwjZd8f2HNfwp0vwmzMTq9D/7NTagkK5ZlrhZatt6a6gx/Fgs3H8GU3ghfkwXt799+GM5VW/uqiAzk/0MHrLk/7gLUcH6aN9RntyYVMPC5Qh+tAL+eJZzR+G1yNx7rmq7lKQBsf2FUNTCHSeoTvBw
    retention:
      daily: 1
      weekly: 4
      monthly: 12
      yearly: 7
