apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: monitoring-backup
  namespace: kasten-io
spec:
  frequency: '@daily'
  retention:
    daily: 3
    weekly: 2
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - monitoring
  actions:
  - action: backup
    backupParameters:
      filters:
        excludeResources:
        - name: loki
          resource: statefulsets
      profile:
        name: nas-nfs
        namespace: kasten-io
  - action: export
    exportParameters:
      exportData:
        enabled: true
      frequency: '@daily'
      profile:
        name: nas-nfs
        namespace: kasten-io
      receiveString: bIzAPpoanmEBkA9OvTMoz/xnWzMMIVPE/CKD5VJha7w5BrBavmPge4CbR8equdc9MCrszKuNGU+u7zELhTr9sjshuV8wNf27ZZ+c2eTN1oWpofxyu397DDWVzpuXDZ9qQKdUg05m5Lt8lbOQ7NzBm3aUH/WMi3ha9S3YM0jO6+mB1JpPAmSVojOQmmCPKAxl2rBVb66ktkdA00o3MTiL9929XXSzHSjrpihO/IrbWJdep4bOOnTYbsUDs6SuidqyZJbfIPjMK9NzS3Dooksp7mDI4OOZKrOO1lXSTj4nHjUrUimQ9j1ioSP25I+apIQ0khwjZd8f2HNfwp0vwmzMTq9D/7NTagkK5ZlrhZynt7P4kxfIjpXVs3tw1RO/zDJ7uYSwP9sJj9ikHTlO2YK7PQj03/4FFPbErlqhiNASfGlQnO5DJNKYfCh5IlfdjuL0KEbJuuu7/kxZ+WqjeoPkM0U04Nhk
    retention:
      daily: 1
      weekly: 4
      monthly: 12
      yearly: 7
