apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: non-media
  namespace: kasten-io
spec:
  frequency: '@daily'
  retention:
    daily: 7
    weekly: 2
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - home
      - security
      - networking
  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - matchExpressions:
          - key: kasten.io/backup-volume
            operator: In
            values:
            - enabled
  - action: export
    exportParameters:
      exportData:
        enabled: true
        overrides:
        - enabled: false
          storageClassName: nfs-client
      frequency: '@daily'
      profile:
        name: nas-nfs
        namespace: kasten-io
      receiveString: bIzAPpoanmEU6gFrhzBthdA9U1MxFleey0mg4nACcr55H85NnjbiOIGgVvG9g9c1MiTwzKuNGU+u7zELhTr9rWogk1FJL+HBW9LzqsCT1JXRnboyyFR9BRGTytvbDvhoHaNQumJl3bpBibOQ7NzU4XixJfbJwVQA/U3lBEyU3IKi07gsG2bVu02HujWNaw1ey4ZCVa6stElc00o3MTiL9929XXSzHSjrpihO/IrbWJdep4bOOnTYbsUDs6SuidqyZJbfIPjMK9NzS3Dooksp7mDI4OOZKrOO1lXSTj4nHjUrUimQ9j1ioSP25I+apIQ0khwjZd8f2HNfwp0vwmzMTq9D/7NTagkK5Zlrhpyn86ryhRfHy8Wb8Gxi0Aa/izwfpJGlCY1c3/vvDHA/24i7K0Pmnf5JQ6iVpFqjxo9DJCJcndRKM8KFeik1TgPSiyS8VptzldiePk0EPAe3Ig
    retention:
      daily: 7
      weekly: 4
      monthly: 12
      yearly: 7
