---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: neuvector-crds
  namespace: neuvector
spec:
  interval: 15m
  chart:
    spec:
      chart: crd
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: neuvector-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    openshift: false
    serviceAccount: default
    crdwebhook:
      type: ClusterIP