# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:eiIhbVfCA2ef0ikuGw==,iv:cVFoqCHQQ77SVpzJapM530GT7nnZ4HET/oHT8IeRiPs=,tag:6YpL0D5u4L2/D89at8MS4Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yoYhIhADycUKmPcJODHwKzW1wCnPbX42dhFd,iv:lQlyCj/6J+JPfbHIk1mGuuzO8Ak7RS8EkxCl+qv+PG8=,tag:tgekD7wG9OfCkmzJoPtK0Q==,type:str]
    DOMAIN_1: ENC[AES256_GCM,data:utXiMS4qdxOh7yk7bg==,iv:2SIpeJtz+EXZS7til61GpHS/+K4Z25j1POzUDZW66bg=,tag:+/QCCMNT6H3UwaFvg6KD8A==,type:str]
    DOMAIN_2: ENC[AES256_GCM,data:kAP1xhJ4ZQ==,iv:AZY2uR7U/XN4qlLYvnyWcSUjU99XLZ6PEV1A+b0H/nw=,tag:5vMswzxrMfcPzmF68ta1xA==,type:str]
    DOMAIN_3: ENC[AES256_GCM,data:J7ReIt9Hs3fI1zbdYA==,iv:wG5L7nDRRp80jwjFLfVkzzYFudXl2Tqe6emQMpdZdxo=,tag:IVhjXUNRNO+tnaDnbDsN+Q==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:w3vq6d+D,iv:NyKJduCc/GELTGv1kce2R2WGk1rcX+d9wxC8pClMc0I=,tag:2xP4v2Soc+L0zGa3eC5Qlg==,type:str]
    MINIO_ADDR: ENC[AES256_GCM,data:IHZLwzQoY2lgMW8=,iv:NjFpnjJBIGmpS3mzKZPtpnl1uwjMZjvO8TP3m05G+fU=,tag:ms7zC0ZPV3rVrFIEG2UrHQ==,type:str]
    NAS_ADDRESS: ENC[AES256_GCM,data:gPF3tWRk+zpyEVE=,iv:7rIX08X0d/dn6GorWdnnDUh41MqASPe3t7NM4kZ7vQA=,tag:TVORsRKr3FD3+XE5uzTexQ==,type:str]
    POSTGRESQL_ADDRESS: ENC[AES256_GCM,data:B6Wb4PWx+yCHNlM=,iv:FAYLYGAKYwrQ8AYT/98WfkNNbG8YisF1EWg9BW5hWws=,tag:76+cOK/ZOnh0qK74X4e1Mw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:kf0qIcKhhTZBUjuvtMNWD/mRSqI=,iv:nQuOabu3SbPet1yr+iCcKicSLc4NLHrG3nOvmmkc/MM=,tag:zoUqQa7Lx/5mlJqHZnPLrA==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:COJpH4wgd/68A0da4iOA+QC9wO6ustVVHCzYxf2wwtb50HyMHwuPAw==,iv:ktC7M7AJkJQHYhjawp2uwQ0VHaayjkT2YkjH2dln5t0=,tag:Gn048js5qgy7pO9fZl3ofg==,type:str]
    SECRET_NEW_MUSIC: ENC[AES256_GCM,data:WTAoygkL9FtauUg+,iv:FYbidtUILlcl+BjrQ3LiU23/5rNseha4j73flA8Nu1I=,tag:Yr4Qg65IhVH2d6Fy1aV4GA==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:jfwDgrY9uyK49o/jEZY6joEP9qGKqTEHCbzuYT8kgQAYpPW2fdq1G/SsJrcTWcB0Tf/1,iv:tBic/6wo/b7nLuZP+aj3c7FOv9YIX6CaZLU8o0JFTBQ=,tag:1MkUGJS44M+U5onnMXsohQ==,type:str]
    SECRET_KURED_DISCORD_WEBHOOK: ENC[AES256_GCM,data:f9DQHedxU2khik0/8315EBRMoRp+efKwvc7V72oVdl8P25N4C+HNt65aBWZBYH79NBxBR/YF2D8eBTPb2/qrv+3tSYVF54OKUIGU306qPpON7K0gTb+/hcuPankWTwuuVg==,iv:YN8KQekXD6zsKiLgOeqPJhoVp0WG2HVbLiOArArQ98U=,tag:s8lT8bPa6889eSKxDDebWg==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:9NRE2meRDIKBQkAxG+kYTKzoWvJZMU4hh+6uBqXOepwm0e9z86qgyiGseN/YaH4tWJLKO8L34MFrNP1p9ak+awyhGi/flQ6/q/VzKcuprNO8yzogg2LCzZAdCVLXG1pJd/O625A/vrYjzMElPGlkXKXp5t/lqq2LT+p7vd9U,iv:OHn0Jjq8RP0sE0gDBlbB5HPMQf64TkrpIbnnltZpGQs=,tag:hBkRvqv6uffwB9DZ9yzf0A==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:j6Ji+pyya2KP0tvqgoUG6+PoenjF,iv:VkjApfJlpygrWqiMqBh3NYsGQpasHyB1sQFXxcYaDB4=,tag:B/LJD2dYO2Gxcrjy/DpyrA==,type:str]
    SECRET_HOMEASSISTANT_PG_CONNECTION: ENC[AES256_GCM,data:RJED8hsVz3NiSmjKMYNVT2LH2QkfZbDZJQXMNtO6cPtX6+LSLsxOKCnb3T8xZGTp9zaVVRk4P20zpl/XHbqafKKxhz9ulg==,iv:jbiH9knT+q2AujWiEJe1Z1Z96ojrafu+1VlqfpbN17o=,tag:MRqN6ehHJUvbfgR5UJnmOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-08T01:44:34Z"
    mac: ENC[AES256_GCM,data:he1tCdl0v8zrC53BAo/T+7WwX4974iypr3x75pqTCN3eIdTQRi+V51ZxVSQokRMTHSACZlTdtDHq9VBEzfVRTc3LKuM1oGNWJdsKI1ytiyG4YzXEFWw2aCSuRfRpDAtUYoGLTYy4i/H6Vy8/QBfYutN1lQqJXx7v/9i3fKN94jg=,iv:aXOVDZERANflbNaaJHuMmm+OtJBfD8LY5ZxulhXBXmc=,tag:0M3T9vO3TKInsyyJrAO0eQ==,type:str]
    pgp:
        - created_at: "2021-08-06T15:22:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ/+O9WT0/Knhm8uVIpXWaZsCG7ltFhUW3yyfZ3Rzoq7ssE4
            DXTpeeR/wmJsIhLH4RDUFZILkQvvh1iRp8Y8xCJxBkx4BwvenMVQAT9P1/0A6jXT
            Ans1RrFzBBMT1j+ZJCDL2/us49SujzHyFjYZDedQa9jJHge7tHNlYXyGrGw1opWZ
            N32PHt5IDh2/tOHppDjGzYh5otCRpdrLGnJsyUoB03iAMOIrvmi+ruStC+gbu38N
            Nef3c4EaU4GnUrX9ruWKkyYHx0ToWJb1IZIXLZa7jntB/YgJQ/qLiGCU/j/V84rE
            hk5jLIkUYnCEEFmIY4AbNYe8GDouiAA5wNe9rgwaXBRLXId7eNdYdmA02FC+WnD4
            VcxumttpuUpVcWxQxrkwZ3E6Y4kk+DJiaBleXggPk35u9m+iIQ8R9+rqNnTRm46Q
            8I0mo7dOShZalnU12N5e+aJwB53MD5KXWZamHPwsOV4cSG/5weEKNdE0t40hv6fr
            7hl1P+UsuEhdzTUHTP6L1i6+mVJkcl5G7lCMl9qWl3QnPgsJF3fFwezQoUoboaZA
            SoStfzwC4QJQ6f6afN5z3zVDoC6CriWQnsJHP+Mdk0u36rfr7yyTbp6VftXYn6Yo
            DXQfJYZoQ10sbcSl8A8pfGtwR9OOOXa/Ty8KYQwY0ErtTBt3TXw0VAN/BwFOK+nS
            XAHc6Bk0rS0DZ+3ghk/dGYuIyGwUAlRA9BgKcvUCbYQu2QkLOtKnKoHMO7d+1TbW
            O8UJGWyGyrys4d+5KKZ+xAWBr+bcwpE67CkD+56UNsmzxMOfmK2SV5MyoHkP
            =IgLq
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2021-08-06T15:22:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAWGXN3R6u28w4p6G4fIFiOjeKKPg/Po0IEVppiCbFkNaL
            s+Ub5WIGENm0L1mn/2RrjpwPidPCYSSoaZ3KeQ1UkN2SeGuyaeWaBLMfQirS3SPF
            lPSN+ExQvpx6t+zWb2H7Rg4MXmABk+C1nHNlgh8jfQu9vPuZLGFj3hJ4Ryz076jf
            2nSng1H4uGLVY4RkjbTkuzB4/HErbzYAoNSSLESkAWquDIhe2kyR1jnoNanDR567
            /6q0WO4oLXzuc8rXljQHdDbGGjcOM2AlxyhdzMAIU7r3KUDAMP+RQHE5VqBaBlNs
            VnUtiD2QpTVttrLoDsqevPBzzEJw8zKUcKR4Bm3BWQpjkBSCEclZZGpY9oOrVl8x
            G7xjfT7gmJuPtx5gwGbELc38fkpAzDycqafaANG3oI5CBLtvcxlk0uJCR8PUfN9E
            zGE1j8qM2faDmUTifBBxx7f48J32pJvG1L3eGYqCeoH8CXikmkLOny8oFZ3ihXFs
            tsAE2Y3VoX1L2O24Eq81L1qgaRJp74x9GT8BYCatvHeQRXXsDwCsaT6at6XoSNeb
            JgOygL4wFELpwblbDvMdjYWnoxhkwQh9VIZXk9DyTV859/KRPCQcui0/IV1WcnJi
            2gg1cVPrSzXv0OOAisKXJmCaTGAsqazQ7FjzBH3NgOIoGHVYY0JV6XC400ZdtyPS
            5gEFslji/BQsJEedoU+oVccjBSZiMmrkUXgjjUBbzQSkybIsoSs/8bTSLchlChPX
            u/MREsPWacS7zDKbsXdx+u/kRH/Nt0P/xsW7sYo9TjgEfuLcszSjAA==
            =AyHX
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
