---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.24.0.210-10.24.0.225
  INGRESS_NGINX_LB: 10.24.0.210


  KUBE_VIP_IP: 10.24.0.200