---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher-server-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://releases.rancher.com/server-charts/stable
  timeout: 3m
