---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_2/./-}"
  namespace: networking
spec:
  secretName: "${DOMAIN_2/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_2}"
  dnsNames:
  - "${DOMAIN_2}"
  - "*.${DOMAIN_2}"
