---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: "10"
      backupTarget: s3://k8s-bak@us-east-1/cluster1/
      backupTargetCredentialSecret: minio-secret
    #   taintToleration: arm=true:NoExecute

    ingress:
      enabled: true
      ingressClassName: "traefik"
      tls: true
      host: "longhorn.${SECRET_DOMAIN}"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "security-ak-outpost-traefik@kubernetescrd"
