apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "longhorn-${SECRET_DOMAIN/./-}-tls"
  namespace: longhorn-system
spec:
  secretName: "longhorn-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - longhorn.${SECRET_DOMAIN}