apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "longhorn.${SECRET_DOMAIN}"
  namespace: default
spec:
  secretName: "longhorn-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - longhorn.${SECRET_DOMAIN}