apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: neuvector-kube-api
  namespace: neuvector
spec:
  addresses:
    - 10.43.0.1/32
  hosts:
    - kubernetes.default
  location: MESH_EXTERNAL
  ports:
    - name: kubernetes
      number: 443
      protocol: TCP
  resolution: NONE