kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:MUOV+qO0dlunepsbfYf9y2UoyPRLXg==,iv:ZXmhX+mL47R696F7CYvP9l9MJvpR612fAQis4oporZA=,tag:QBji0BMI2T1efTIMW0+OMw==,type:str]
    FRIGATE_CAMERA_DOORBELL_HOST: ENC[AES256_GCM,data:LTVwn6wTuqhCZJhr,iv:JzeuJLZQFJR8+Va8eUz3ulRysr8ZQIrLaaCECRvyEyI=,tag:cPzFCFVfl4+AgURVD4bYkg==,type:str]
    FRIGATE_CAMERA_DOORBELL_USER: ENC[AES256_GCM,data:BZcnX6c=,iv:6l9TdWqfdobSMwTAT4Ue3s3ZV1ge1v8hS4sYu/vVTA0=,tag:4zclPeP8Vm/+pl5nuTOVqA==,type:str]
    FRIGATE_CAMERA_DOORBELL_PASSWORD: ENC[AES256_GCM,data:E4PPCNn/wq3A84mjMIS44WVR7Zy5mg==,iv:grIcXXvdSl3EVXZyz259DQbvqOBl7pQbfvaFIn9nG4o=,tag:Vle3QD9TOWRKXcLaWQ1eXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-18T03:59:58Z"
    mac: ENC[AES256_GCM,data:Cna1jchhRsh/Jh5LpDxW2mDSgIuAQKcj0IUPfAZKCIEVky5uyuVqCDSysN67QqNbq2uSqZrSoDnQ4GLDAzmkpqbx57GwJilJrRh2YfMygkFvoWc51408jKFWtczYaRo1+AbApt5DcEq1II3MyqCrOFq4FocysnO6Xz6YEaHret4=,iv:Ycux3aZP+Do8ers3kPsRiwaixwrjAX7AW4Kgz6OEjHI=,tag:soXod8cYUT4Xgv7V0xTjxg==,type:str]
    pgp:
        - created_at: "2022-11-18T03:41:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCARAAuVkMwT+GssjhDh76yOvQPWz/2Fzm7UZx7lxY5rD9tLNb
            PvO0MFM+MikTZlIW25TdH1+fTwhF9CoPItOm+Vof920gF4ZVE/QpUjBGS7j3F00d
            7Dj96VuAWdJ38txNNlzLRxbxPjTG3HevywYwAX6NojJIjhBL3yowKW2sOKtj1vjV
            nICAvdz4KcDuUvWE3jhrtfCZpXzYqXtyp2KTzLV8ufmeHeFiMZ3wfm4ndyrXEB6L
            3eKdN5IS4uHgGgCMD7Hzz+G9O32Li+2vMH4iOngEaqAco47exIsZ6iJw0flXlL3T
            TKBzKgxx3bLkcBXPa04u+Jog5F4uMB7rBiLNjUuj5P7kNXPhotw/KiO46tNVQQA7
            x/LrYhzO3pFRx7EiTrsiYw/hfqbsAgosVi17axcxFyXAcj1d1kfjXpDpu0gBTVAQ
            ZC/IUcFxSDabLc0KtwnJZCo6sJeqqljyEHLGBz+CiuTUOxfk2aG1+B0c+tf8DOYc
            821Q+eXitzqVeS9ihr8rMrEqCmmR40+UhXyKiefk8QdAQTHiZV62y+GJpYTZV1IF
            O1yU7MSVXJ6dqg3AYQ1MrncZT4XIpvrxQl8PmzHr5cerYDyE/CiO8c74LLOH2Rqs
            wh7/XqhRKlZdosRRrdXHZRmO0RGrsjZH58xI+kTENzkVbdfoSZU+xvYj7mpBjiHS
            XgEnIJqYok0DX/gKw2Gp/Hb31wfQ6iFASkZjlB7IG7Xp5I+U3IHX2dtgcUQUq1DR
            LQpwZdfcdu4giHQDNto94DGxJLTO+MZ0Gic59vXBbo27JepdXWUa2+b7PnPka88=
            =7Jfa
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2022-11-18T03:41:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAjAYYy+CPpVm7stCoW+oEzpOQmd37sAzi3BTnRK7bBvEh
            REHOAatB0LcpqIkRndeZCPpEtgzB3zmAMWkXESFJPhnaeXVgyVrS5uAwGhMDQxTA
            8DnccbjdNJ5NDPuLvCQ+Oya2Mo3jQRyX4ElZYQ8vqGFlbMXbTfSscLeeCcQTYIiv
            3F0khrXf2OF1JudJ1qoIIR/eTBQPJk2QlUFNI9qKOds/06O6x9WEH6nc7CQKvgtI
            9+f80Rgw6pzK0FVuziVqNJlSRYg07NStBxMsH7wkhvDR5UHsdAVkIZCua303a2O2
            QbQgnRxzordyjqnNF8NvxjCfNv5e3fBQusGczG+xnc2K5AVGzqvi5yM77hX5zXRQ
            6PYCy9nd5ZBPnVqfr6XMf84yioRbO5r5rJk/JZihEdrTp8D5Luh7lujVF6Bx6ZDt
            V4kPirj6HDSHeYNMhQJki+q/ekHy7gMnXl/2cHFjgoIhzBOWd+Fw5q8Y/mpUwDfV
            cpz0RnmJ7d/RkX0tv6d98OrJ/koWY1phv7TJX/BMSVIT9gqu9MU5QGLxhjBd56Zx
            5Zfde8jmgzwdKW5yE2ES7NYxBAY3ob6bRMptk3US4ONNG3rzFfQ32B8hp0J2E4Ur
            NqoU1e6ylcDd8QDPla/EaAZdfp6L4EXPQoigOXYtnddsr7ckb7DWgqv36QUb3kTS
            5gH/XINWBom5b43CCw2rB8DtGMf9ILLH9sKsGla+3Cgj/5geQz+sp34gYqDrXW6g
            9AH2KY1pJ1xochH9Ux3jwf3k2BWojs9ty1LIGbaG2prpBOKwJrGNAA==
            =6WwV
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
