---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: debug
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/mendhak/http-https-echo
              tag: 36@sha256:43bdfe52abc5baed00706337efe26825c86360c6b9b74659a72a9aa2fca8bd55
            env:
              HTTP_PORT: &port 8080
              LOG_WITHOUT_NEWLINE: "true"
              LOG_IGNORE_PATH: "/healthz"
            resources:
              requests:
                cpu: 5m
                memory: 30M
              limits:
                memory: 30M

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: false
