---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: debug
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: docker.io/jmalloc/echo-server
      tag: 0.3.5

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: false


    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 128M
