---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: neuvector
  namespace: flux-system
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./cluster/apps/neuvector/neuvector/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets

  images:
    - name: neuvector/controller
      newName: ghcr.io/ryan-mcd/neuvector-controller
    - name: neuvector/enforcer
      newName: ghcr.io/ryan-mcd/neuvector-enforcer
    - name: neuvector/manager
      newName: ghcr.io/ryan-mcd/neuvector-manager
    - name: neuvector/updater
      newName: ghcr.io/ryan-mcd/neuvector-updater
    - name: neuvector/scanner
      newName: ghcr.io/ryan-mcd/neuvector-scanner
    - name: docker.io/neuvector/controller
      newName: ghcr.io/ryan-mcd/neuvector-controller
    - name: docker.io/neuvector/enforcer
      newName: ghcr.io/ryan-mcd/neuvector-enforcer
    - name: docker.io/neuvector/manager
      newName: ghcr.io/ryan-mcd/neuvector-manager
    - name: docker.io/neuvector/updater
      newName: ghcr.io/ryan-mcd/neuvector-updater
    - name: docker.io/neuvector/scanner
      newName: ghcr.io/ryan-mcd/neuvector-scanner