---

packages:
  apt_install:
  - apt-transport-https
  - arptables
  - ca-certificates
  - curl
  - ebtables
  - gdisk
  - hdparm
  - htop
  - iputils-ping
  - ipvsadm
  - net-tools
  - nfs-common
  - nano
  - ntpdate
  - open-iscsi
  - psmisc
  - socat
  - software-properties-common
  - unattended-upgrades
  - unzip
  apt_remove:
  - apport
  - bcache-tools
  - btrfs-progs
  - byobu
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - fwupd
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - open-vm-tools
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - tmux
  - ubuntu-advantage-tools
  - ufw
