---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airsonic
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: airsonic
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/airsonic-advanced/airsonic-advanced
      tag: edge-11.0.0-SNAPSHOT.20220203034658
      pullPolicy: IfNotPresent
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      # Run Once for /var/airsonic/transcode permissions issues      
      fsGroup: 2000
      # fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 100
      - 65540
    env:
      TZ: "America/New_York"
      JAVA_OPTS: "-Xms256m -Xmx512m -Dserver.forward-headers-strategy=native -Dserver.servlet.session.timeout=2880m"
    enableServiceLinks: false
    persistence:
      config:
        enabled: true
        existingClaim: airsonic-config-v1
        mountPath: /var/airsonic
      podcasts:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDRESS}
            path: /mnt/user/airsonic_podcasts
        mountPath: /var/podcasts
        readOnly: false
      media-nas:
        enabled: true
        existingClaim: nfs-media-nas-pvc
        subPath:
          - path: Music/Old
            mountPath: /var/music
            readOnly: true
          - path: ${SECRET_NEW_MUSIC}
            mountPath: /var/new
            readOnly: true
          - path: Music/Classical
            mountPath: /var/Classical
            readOnly: true
      backup:
        enabled: true
        existingClaim: nfs-backup-nas-pvc
        subPath:
          - path: airsonic-backup
            mountPath: /var/airsonic/backups
            readOnly: false
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "headphones-box"
        hosts:
        - host: "as.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "as.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: "768M"
      limits:
        memory: "2048M"

