---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airsonic
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: airsonic
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: airsonicadvanced/airsonic-advanced
      tag: latest
      pullPolicy: IfNotPresent
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
      supplementalGroups:
      - 100
      - 65540
    env:
      TZ: "America/New_York"
      JAVA_OPTS: "-Xms256m -Xmx512m -Dserver.forward-headers-strategy=native"
    enableServiceLinks: false
    persistence:
      config:
        enabled: true
        existingClaim: airsonic-config-v1
        mountPath: /var/airsonic
      podcasts:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        mountPath: /var/podcasts
        size: 10Gi
      media-nas:
        enabled: true
        existingClaim: nfs-media-nas-pvc
        subPath:
          - path: Music/Old
            mountPath: /var/music
            readOnly: true
          - path: ${SECRET_NEW_MUSIC}
            mountPath: /var/new
            readOnly: true
          - path: Music/Classical
            mountPath: /var/Classical
            readOnly: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "headphones-box"
        #   external-dns/is-public: "true"
        #   external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "airsonic.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "airsonic.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: "768M"
      limits:
        memory: "2048M"
