apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-podcasts
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: nfs-client