---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        replicas: 1
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.30.1

            resources:
              requests:
                memory: 150Mi
                cpu: 100m
              limits:
                memory: 500Mi

            env:
              TZ: "${TIMEZONE}"
              DOMAIN: https://bitwarden.${SECRET_DOMAIN}
              DATA_FOLDER: "config"
              ICON_CACHE_FOLDER: "config/icon_cache"
              ATTACHMENTS_FOLDER: "config/attachments"
              SENDS_FOLDER: "config/sends"
              SIGNUPS_ALLOWED: false
              INVITATIONS_ALLOWED: true
              WEBSOCKET_ENABLED: true
              WEBSOCKET_ADDRESS: 0.0.0.0
              WEBSOCKET_PORT: 3012
              SENDS_ALLOWED: true
              EMERGENCY_ACCESS_ALLOWED: true
              DISABLE_ICON_DOWNLOAD: false
              DISABLE_2FA_REMEMBER: false
              EMAIL_ATTEMPTS_LIMIT: 3
              PASSWORD_HINTS_ALLOWED: false
              ROCKET_PORT: 8080
              SMTP_SSL: true
              SMTP_PORT: 587
              IP_HEADER: "X-Envoy-External-Address"

              SIGNUPS_DOMAINS_WHITELIST:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: SIGNUPS_DOMAINS_WHITELIST
              ORG_CREATION_USERS:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: ORG_CREATION_USERS
              INVITATION_ORG_NAME:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: INVITATION_ORG_NAME      
              SMTP_HOST:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: SMTP_HOST
              SMTP_FROM:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: SMTP_FROM
              SMTP_FROM_NAME:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: SMTP_FROM
              SMTP_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: SMTP_USERNAME
              SMTP_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: SMTP_PASSWORD
              YUBICO_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: YUBICO_CLIENT_ID
              YUBICO_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-env
                    key: YUBICO_SECRET_KEY

            envFrom:
              - secretRef:
                  name: vaultwarden-env

    service:
      main:
        ports:
          http:
            port: 8080
          websocket:
            enabled: true
            port: 3012
    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config-v1
        globalMounts:
          - path: /config