---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  dependsOn:
    - name: loki
      namespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.3
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #   registry: 
    #   repository: 

    config:
      lokiAddress: http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:6014
              label_structured_data: true
              labels:
                job: "syslog"
            relabel_configs:
              - source_labels: ['__syslog_connection_ip_address']
                target_label: 'ip_address'
              - source_labels: ['__syslog_message_severity']
                target_label: 'severity'
              - source_labels: ['__syslog_message_facility']
                target_label: 'facility'
              - source_labels: ['__syslog_message_hostname']
                target_label: 'host'
              - source_labels: ['__syslog_message_app_name']
                target_label: 'app'
              - source_labels: ['__syslog_message_SRC']
                target_label: 'source_ip'
              - source_labels: ['__syslog_message_SPT']
                target_label: 'source_port'
              - source_labels: ['__syslog_message_DPT']
                target_label: 'destination_port'
              - source_labels: ['__syslog_message_DST']
                target_label: 'destination_ip'
          # - job_name: journal
          #   journal:
          #     path: /var/log/journal
          #     max_age: 12h
          #     labels:
          #       job: systemd-journal
          #   relabel_configs:
          #     - source_labels: ['__journal__systemd_unit']
          #       target_label: 'unit'
          #     - source_labels: ['__journal__hostname']
          #       target_label: 'hostname'
    extraPorts:
      syslog:
        name: tcp-syslog
        containerPort: 6014
        protocol: TCP
        service:
          type: LoadBalancer
          loadBalancerIP: ${LB_PROMTAIL_IP}

    # extraVolumes:
    #   - name: journal
    #     hostPath:
    #       path: /var/log/journal
    # extraVolumeMounts:
    #   - name: journal
    #     mountPath: /var/log/journal
    #     readOnly: true

    # tolerations:
    #   - key: "kubernetes.io/arch"
    #     operator: "Equal"
    #     value: "arm64"
    #     effect: "NoSchedule"

    # serviceMonitor:
    #   enabled: true