# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vector-aggregator-secret
    namespace: monitoring
stringData:
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:eRNQcmhX,iv:ruCbIeD/bxbRa+fZ/44I0sXNMelAd2Egd1hzjJ3Ki/k=,tag:UXjaFU0Z9f/YCAT6e1Dgkg==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:GFZpS5ADeppNaojafp5ZlJaU6+xTMcp38ZmoHIN5s1NinPJ4dg/sTA==,iv:y4VtFmRsUrsZCDqdSshPRGi8EEWrWm2biP74ossreuI=,tag:y24c2TgiCYxSR9+pqSr8Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2024-10-26T13:50:49Z"
          enc: vault:v1:GBmi1VK5wvvpeVFlkVrpszCFkdHhojFIHr4oS4vlRPZ4TXPtAQpVFeRMY/ce/Sv5E23QBlW0BYxN8GJP
    age:
        - recipient: age1h4562p88dlf3mh8v585vuautuae4hs0pvuyeh8wlagplt5dz3yqsgx7q9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaLzVybWdkdVphNE13cjVF
            cWNrTVdSSVdHVXUyVkJTSDVCc044aFlvUkY0CmJUSXJlMFEzdVNuUnFrc1JLUGtH
            QWhYN3lkaGgvVkFHN29mWC96ZkUrODgKLS0tIGtNQ3I2WmtVeVVqQmF2RVJmTEp0
            RnQ3RmVwV2J0R3g5anZOMVZ3MlJWNEkKgsdceuPSoHx3yoaBVyVsBzKW91js6R+G
            tqO6MxL3afvAaEuOmZmdIJZye1cITGF7mU1FNy7QX6PDmnuowfJylg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UEM0VlprNm5kd2VrVUVX
            VnFxdGdkSVZoTWYwRFNYdjZPVUNGVGNrb2dvCmt0TjBMcmxHbmRlaVUvcUNta1ha
            SE00UlZtMG1vYmhLKzVPUEJkNEh1RW8KLS0tIGl2dGMrazlINGZQa25HVVMrUStp
            YXZGWkpOWGh1T3k1Q2h2QUZscThJZW8KWdd4qiu4vhrlRj6eYvkJJ5htRUsvht5S
            6u39OWF3FyzHJbdZZjtmesSmaYcWmCzeaD05vHBOEn40NMmmnq1eDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSVhQOHYwdFlRb09MZmg0
            d1VxcWJuZHRwOTRmMjZxdDM2eGluUityMVM4CkFpZW9RMlFGaXhZVVdPbEtFVVdQ
            UjdpMnRBdWMrNjRBZXhsVktVTHpQWFkKLS0tIFBpVnNXRk5Nbnh1TkdUS2p0bGRn
            Zy9hWTVCZTRHVElLVG1yd05WOU5CdjQKjyoooIlUTed3OdxBpydd68lhg8J9OHCd
            JzOQuuE4H9U9e1Q7vBZdpAUOxWeYQqq7P8a2JaUrd6vYnI4GDvEiKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNWltZ3dSL3FuN1lIb2tI
            UnhzSThFbldHUkF3RVBGNk5odmdHa1hXaFY0CllWa2NHdnRDbVl4VDVaUTlDNm1E
            Y0dTTEdaeWdyMXd5YWUzdTNqWmx3MUEKLS0tIFBXRXRDUWtzTjZvdHA2VmRaM2hz
            ajc0SU02Ym1PWXI0WjkzVnZWSXZZSEUK2hTiiL+8528b40acX4cvM8Ylx8u8Ow4e
            w6vTNyIde6lpqMTg+Dn6SSu/OCQhu2aaNOOHHVMemoteafWR69BxGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T13:50:50Z"
    mac: ENC[AES256_GCM,data:ZTC9D9YQUIQFSEe4voaYsNXn0O6sPMNwMBbFfO4RokKEVEb9euD2JGl8XAsO4U954ORh2E06JqjzV4FzVnNAUfWYRAsKU1EQp1HiZ80jzHPXtjN38dwCZ8mgUxIVEzxqDNo/WWunIM1n0rBPraYRVaImAYJtP+tivZPc1fxR2UQ=,iv:QxIYG6RbfQbANv45gbD/rZKc6umscUk0ZIBJjrurId8=,tag:1TU8yC6E/o8eVqVJVyDp1w==,type:str]
    pgp:
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ/6A6+IOnYs1SeQ/NlNIQxNrg3+cE7JJe1SyftzIeEDSOxf
            ud/4IqFovqIvollOkFsdU7C/8z0EQZ2cujBjwRJaL9/FexVurQ47PJ5LrGwsa5xY
            Z1WMIyw/vZ2YOduGxvCPmoMnOb8MyTKSI6cLz8JcRmxuxLbumdiPaGynaaDsxgYe
            izLofnEZBdvgj24liUty4rdPF2Y6Vme2K2usKkW5pJQKTu8qGCvu86/Q6uYJdiAm
            wtTewfn1iEyIzmmd0X0WPiqhLclfiFncWswm0ipNKrqVkoeTiWXDP7qRp2bC0QAD
            w1OzOxVPINOu5ZLQlDDynt6AvagATA3GVxg5UxW1W7cnkxe3wuUOipkXnh2utLZn
            ERHIqujrSExfiSJC5pUHEIDJU7+oGLhMhQSYy/UBMIvOM99qLOabRHmV8gwyLYfv
            4Rt4B3sfULnLF3rctlEYh5Md6eLWlSK+UQO7OGllgFua+byQn+buZounQTv23YTl
            /jiTGAFfuSygeOS46JYN6Jt1mtw37wunwybK/Y9az3XriqbR9D3xZLdh1NVoSbwe
            irbBLwixLr3WmmLxiix6H6eyTr1+YSf0IIwkQbGanmmsCAn2FyG5xga7eEmZ5mV9
            gXgE2wFm36nsCyi/6ni796YEQQL37TvZ0W55NgjAu+xxAEkBdc0WI8J1uQRcSJrS
            XgHbjSc8ZxjYf3O7oYvLIIukpjJ2Imds+U0DQ89BSpDNnLHh2Uj9+Oz/IVFnBIGT
            JPzp6YMfoeNmf+FD/FCjzQYt5blRgvdTjXfUTZexfKg3UYjfgd3PxapbP4GPK2s=
            =fJF1
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAAwQkGNpTiiMiIn+96e2WAvR1OkIHfxaBmbbv0aqwGFylf
            oQO4jyiosCvLspY2zCxjDbfJs5YO/joPn59VT5w/Q1tIs2zkzllhOs1zJDDlquS+
            R0v6G38847hm/JtIveCjgGgTGCsCO08cWzENBUZ6dR6Rl54cCQtGj6yONHcIPBFY
            kp+WwvvuZjXvH2mC09ABf7nCAs4A57AdAheRM/MHLT7c1/ZTuiXcMuvItXv+y1Pa
            TErH6aa21wsLbDxlEH6BgumKaS+NfMlGYGQJ3aF3CBChAMgBUuSIz/eDEZel88Nt
            NFWBkU6gYVy5uL96u70JIxannhMU3hItL/b6Cu8+ME6/DXjpmrSl2HjXhLC30KjZ
            2aJu63Sei5Tyot++zhC/A22LNR65hD86GMjyQ4S8XJ6SssdVRWXAikA8CO28n4SW
            TeITSoIvP8gcnUxEq4cKf0nh0SNL/txkvu4Lp0RbWhDCqIIsOXXaMtJg1S7q4gmS
            tP0s2OOPHF0WEf6uABBMYsnvgH47gZD55Twaqs/ttUQYngc32P+U+BgbPVqGYc3I
            aJAksamHfqCQ3jtZDcZGHHmxIzW2jkz6DNHpvpzYG4tsWQQkI8Nu9z3gydm+IQ+D
            lxjT0kSgaKHooJZ7JcOZIvCyW8No/lW/WD9EzqjVFqqZRvXJsREKYBHZAU/QVQDS
            XgE0LEXWdPC4gmvtDAP4ygBCrhfnDUKG5mh7qAKTgk+VpyLIBqxbmOmossOcjekz
            TndJEgvQA6/mBOGiJjfT4ys25wfbkKmMX7nu+sDtFWoBBGoCwpFnWrO+MdVPA34=
            =n91n
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2024-10-26T13:50:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ//Z8sEYU49THvTuDanxR8zOCKVQ7KVL9q8zD/x8U+XW4qL
            dikBPlJv/0jIxV2cxobyI3SToatRClxaWZ2F6N5k2tKK0+7jGTrL4ozbjQekSDx/
            wXzl6bh/KtP+Aah+NbI8dfxTKn0nE7ZGQuDj0z6iJOi+aXDW6UShNNi0CPoP+tqs
            HdN8Pao9dRkn3ts2Vz97vURBjzUoqpItstWTXH2QRRDHUlWsdQg8GoGNPoRqRuPE
            +cXOkubx1klv1pYQJ7qwo+GFhySnNIZc9Swa3lX3pxd+0DrdqFmMqNSEfBxvEZMc
            ijYHFFpqnYNHjOY4woQS3HXCdROxkKillfkVFpVs3ndV/PUdJHJli+YU9QAIXeh1
            5WfcW1DlnIBT+264J9bpMe0ipFi89BK0Ked4NSUx0zFfyrBObf94sIg6p+/A3XWc
            1NGVsldwRPLPdNPdzKItkmaeucBUwzKhK6roW551P0PmDtx9fRgkgxD5C1p0sO3H
            tBcThurFpRAKDS/6JYGKxAJ5khQbgd3w9rqzRlevz/xQ4s//Flth6ZydQAgXOkHC
            nxTp/nITElux4/Hkp+DJc0A1Kl6O41yMt2Fn+d0MXy3T0aJT2D+6iHDgROr/oWF5
            pLK449/e+cDFK67uLC4QWrxHU8DJuEaUMtNsCw6FsX7pRic3URlUtm5g0Lodx9/S
            XgHLRR6RsRLRdxP1QIJ7tdG+1i3WV2cGyw+v0ygire64TDds4/STSorr6cPFcmA3
            Zv8sNDGhZCOB2IkEbENQQivfT+y0Y3d9Vdsbs9wlzb1zK7IU9kdRmPuEVn0Gw/8=
            =ne12
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
