{
	"data": "ENC[AES256_GCM,data:fU/WxRMRyj6JPYw06HsdD0Ps8EK6yUBkd/G3jnawVDaHw9aazgh1plRrba/kY1aal4RKObCf2XxvxC08N0tnflTUUqrITeyezsRJ8RMlRVca+tZxW4lz7Clllm9QCfE9Mah/hgqO6eSYhcAHSjcfkmb5YOf+M5PbqsXCjC3ObcM6n4y+1MstuvHEija+2TmxGsEv/O+PpkR4rDMZfdScIMatvwFRBs0Rz1EilysXMo6sphrWHnIOxsQqaWYolUV4yEBpliKgbKgJAAWsggZu/AOC0fBBpCJa2fYpYh7e2OTNpjws,iv:P0w7LfO7t/1ClTRtlI9UccyNSGWEgGfPxY1qHjxzhKk=,tag:RJOm4XwPAe4HWyTcmuQjRA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": [
			{
				"vault_address": "https://hashivault.rmcd.win",
				"engine_path": "sops",
				"key_name": "sops-user",
				"created_at": "2024-10-26T13:50:48Z",
				"enc": "vault:v1:n7EUcRDwg+oF9JrKiLhRtfa6+dCRVy58h7Eo2jkGAKV/ZBymqikwXAoIpei5pQgCiybFL8Xlzfo4iHjg"
			}
		],
		"age": [
			{
				"recipient": "age1h4562p88dlf3mh8v585vuautuae4hs0pvuyeh8wlagplt5dz3yqsgx7q9g",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Qm9Ea0IwM0VxUTRFdFZu\nWDBlb3VmdWtWS2VMOTQvS1VWTEM5NVNjZFVFCkpPNXJ5VGtldzhmT0JaNmFsVnNr\naDN5L2lMdFdvS1lQSytvZ0xvSERBRzQKLS0tIDhHakIrTDQ1eENMMmp6bmJtK3lR\nVEQyOWRNbzA1Rys3VUxCY0hBQncrd1EKLHlqbxUYmJ3LVHLRpH328seIh0mv77U/\npifovwr6Fgh2a/beqFZfv9oJYyM5O+cARjewQh2rXv/PNW0AhLxp2Q==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVHRSS0FuRHRYTnduWWV2\nOTZRbklWeTNzVU9rd3huQXBuV053VVJCeURJCmNzWXBVaG5NanZmSlZBOUJqUXVD\nbEtkZWRlcDRhRTlZOFV2K1Era04yR3MKLS0tIHhubmd5WnljYi9kUUo3c2dpYnll\nVGo2MlkrQnBJRUkrR2hhNnRWR1FPTUUKmRYRUFO5Vtw4B+5/j9MW+mRSROZFYBYQ\nIO6+nTl8348bY1K56rZV1ekdkZ2pnAS9o2aK9ABQtyrnKOwc4uK+AA==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RjZrQlNsMmhoL0lNSm51\nRkk1SWxBVnRNVlFuZmN2a2ZOTXp1alhEcEZJClNJR2JSV0RUNEhPMnRZeFIxVkl3\nWEp3OW5raUllOEVDS0N4R3pTbDMrUk0KLS0tIGJWRkZYdmRiUFpXZHMyUzliVjB0\nRDRkRWFoR04xeXNzRThFZUFkQjRkNGMKeRf915R27FawoX6pQyw6L+s6bGTvYadC\nfbGcJW6ctFimLIddqz7nSvfsPzbZNRVM0zDH55PVwldyUYx2B0V1iA==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNDIxL09DYUVEV1RwOTRx\nNjRqQkRPdjJwR0o2R3dvYm1jQjE4ci9vMW5jCmF1ZzVSZ25JdDBUb0RHbzlRekt1\nbXo0WVVIZU54VWVrTXBnbHMyZlNtOFUKLS0tIHUzTWF6b29ERFhzY1o0ZGNPeHNk\ndFhsM3N1MVo4ZWhPME9jVmxseUR0SEEKAsPM893gDTqrQuqUHIvbUgpb9aJb4RMU\nxQ2Wz/3b6AF7VkIGB2am6pDRY8wWhh5G5xLgZ4xd01QtMEF260g+NA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-10-26T13:50:48Z",
		"mac": "ENC[AES256_GCM,data:xyRdSftytzxpxW4jpT3yNpQB2yrpFP38u0K9ej6hetWyjIDHS7Sz62gQ2HBHVxyHDe26/0zzZPQAjkkUM9cpQ4BiLXlrQJsBvZKlnNIRKZlQOEwSyS0XJH1OKRh/XG5VSJVza1rpGPAYOOO4Jgfsk9Sg5W0RJQOV6PkBp1MwX/U=,iv:nXr87sAhmTkzI/FfhK8iDfRWBLNpIgT7lV8ZN8g33LM=,tag:JpsXCRn5yCv06gm2gh4Zww==,type:str]",
		"pgp": [
			{
				"created_at": "2024-10-26T13:50:48Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA59Pualoj6WCAQ//Y1Qs3g61PRbHSqMKjXDfwvHX2ORbOub9MTY+oM6dkmy3\nH26XGxReG52moSUGC9oCqp7UFTwtGXi/G05gJksqsntkNgFWpuoaD6U2Nmom04/+\nKsgcCPHpxQxFirnSygUedf09v0T+muHWcioDs+OzJX2Rl0BC1nN2ojHMceMHGAzG\noz8sh/+Bw0scCvNInZRPE0gAUtAjq7KvRDQpZIjfd/csHYV79+ttjuLLzYYSWqdm\nfmnnK7Twg25u8reWNC47LhcSoVdZuj2Dc2TrGNZXM2/iyWRQSLx2Xu7oV/WMuVyg\nFnX2k0ybOBhRCC7zNBkwTRmzGhAjxkiaD0Wa3GMdu8ZqdVnBw2pchEG3viXg7GlX\nHyQ/tawf7Yrfb03cSJNaApBnU3pvmxnpPREPMB7iPlRjQP1wuJ6+YkpfhlOXYRwV\nyxpYKS7E9+b31JQBVVXAiaG+ekSCfJCaiCopMkCLFrQCqr7LhJT1yh0kTCzZ9m7E\nPGgeykRjBmlrcCAd2eHwO+On8g1QFqrfQ7q++0ewjAUSTC5LP3ulSGD8hycLNcmI\n2wLU5TT7001PItC+qD9CCkMa3BPDQSXAEDVuAZhRncbGO3nzbPYPOQmqK+Ka+TT7\nq0Wg2V2XA57mzfRehSv5W7UUpVbRCUIWs5Wm4IigmEHQFs2ka7i8klZd1EzbRKzS\nXgET5o4No+yqWj0YCcvKHUFyJQLUY0YluTLVUPQyyScC1Z0JvAwMX3XcdqkxrQur\nETbOngunSAITKduBkFtA8uD1Ls5C60xaotUm9RZr0RekleQuA2xrDsEW3/kh4+4=\n=NEKk\n-----END PGP MESSAGE-----",
				"fp": "B98EF6FF6F3748661F449D0CA912302389FEB397"
			},
			{
				"created_at": "2024-10-26T13:50:48Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA9Qs/eFVrZ++AQ//a7IpUZx+DPPFJzYXCvKJft9sGSFbI8D60HAmoFIBNiv9\nb0x5jbFGAlH7mxOi1nQxYfoMRxJKH27fXG8u4fQcZllgH37NWBqAdxTHq7C2ZIpc\nvbNkPhKqMsTpleLcGbiVvk1uWby5vKDEcL54JVXgflwY3RGHVlqMH65Eb2aA4DPA\ndec1S1P9gP+gIwcpnvphe5rb5q3TIAjbg+FikqXryGo108UbWbRbwACdNCO85I9h\nYsQ8bUdshpmnCWIwvBFvBbmbXXVgm7HIU7hhBZ8nMi4/62Unf09nq8L/K9s33xdy\nsfKmtvj/hebfwSm6SswPlq7v1hn/RSunx7aHQdbRyQSMtdiIVynvMimJYooeFnIL\nQLw3FByNLgJUelvubO/apDMQh/nrjwf125RwGxqkHwb5tH3aWO094WGuGGho5qXP\nh/vQi9Ayo4LmB+Y/5dQV0HkccJ1h2sQMXsuyhyFb2VcIUAJIHNHAVTTVRcy0sXNJ\nP77lMMEz2UlG7fDUv/REkbis7VXd4g5IVfr0lEjLLVis+WwiOUAXXfP+mabnryCo\nloJ31RTtDGdFxCmwJCcjxXbLsoS6LiuJDw8LxnHWgqUEk+0yH/OB/v8SXg2e8Dv0\nd+6j5F4JDn+6TXILSXy/BdxZBUmgTB9ZH5SW9fKJ24SNAORwxA4unqdnFnPkygnS\nXgEhhe5EUStH3247cMzNMYLYjl1DSRTb54Gm8YDzdpbGNJ1xEuB1yhRoK8xAtIG8\nYofMvHou142lfUCSmZLGKhrSxEm7v7AynCBkkPbUkcY/DmfepPjN/lGKPiaYkJc=\n=UXhK\n-----END PGP MESSAGE-----",
				"fp": "95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0"
			},
			{
				"created_at": "2024-10-26T13:50:48Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMAxnLN2eNn/kQAQ//XklogFsSHXjrHcBDISV+2Wboj1bVrDsKVUdR6CRS2f1g\nR6DO8yEpgcDorTmKAhqRYmE74k2IEzNbO4WPw6ptufbTO15jDIqwyrwo8U1fXdSr\nn9zPFWlTedIYmikhwqL6ZHCG2xJmY7Wp0j/Ro9d39D/tGSZvvHhFbWPPabYXiWd6\ngam66KIHteWWj0WkAt0TskoxQxNde3PyKumgvGVESm9e3xDd7eH1AGkxlSHv/m+u\nRYh6osF8mORicdSnRePrO1Kq1hALIww9tbxHv0u9XG1WcZs7mJZaMf0LhLxoCmhk\nSeDTO5+mLNJdXmn1Yty/4AAimeCmRrQImXZkYCv1OXH0MXRmJT3wgovTPIwuwcwU\nUi9cCSFyWuW6nM0D6Tmnwu4uCl7QMoTEQLp5Tirjm+Xbt6HEXaTCuOOF0uxxgPp3\n0XyTu0uZ3JVdKRZK5upKOoF3RIH0kuAOnQF2R3ZzrPhrI+MRGjV0RLotU9ClBHC4\nIhK6w/a7lUabEQy122gHhfMoxpSnshlshz3ZnH7Ggxq5wMh8DKs2Pamf0rmOyIvN\nedrmYY5mvA10m8Zm52gMa+l13bNbRQ2TtVzxqg9Git/QHq79nD+1i7ygbfBkOxk4\nYc1AvQOMKJLk7HDlKxyr0yx14Ph6+TZ02kR8lel0a0Gj8VaLAcBVbF46lP5QOkXS\nXgHdkgOEMt5iw5B5mK1ULhP5xaRm/T4u/cFemIT3UT9F5rHXJEsKP5LP/TANZK/i\namFd0X16cjoS/fZbHb4T+Xu8JHmG3bWO7Qkoovw14rHlP4kEd/vewlGCih3GZys=\n=DTOz\n-----END PGP MESSAGE-----",
				"fp": "E6D978BF2C0B69227A85D9BA04812C60A830A726"
			}
		],
		"encrypted_regex": "^(data|stringData)$",
		"version": "3.9.1"
	}
}