---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: esphome/esphome
              tag: 2024.4.0
              pullPolicy: Always
            env:
              TZ: "${TIMEZONE}"
              ESPHOME_DASHBOARD_USE_PING: "true"
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: esphome-config
    resources:
      requests:
        cpu: 15m
        memory: 512Mi
      limits:
        memory: 1024Mi
