apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: omada
  namespace: networking
spec:
  host: omada-controller-controller.networking.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
