---
# yaml-language-server: $schema=https://1n1raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: intel-device-plugins-gpu
      namespace: system
  values:
    controllers:
      plex:
        labels:
          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.7.9799
            env:
              TZ: America/New_York
              PLEX_ADVERTISE_URL: https://plex.${SECRET_DOMAIN}:443,http://192.168.209.213:32400
              # PLEX_NO_AUTH_NETWORKS: ${CLUSTER_CIDR},${TRUSTED_CIDR}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 2000Mi
                gpu.intel.com/i915: 1
              limits:
                memory: 4000Mi
                gpu.intel.com/i915: 1
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 100]
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.209.213, ::ffff:192.168.209.213
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/server-snippet: |
            location ~ ^/library/streams {
              proxy_set_header        Range "";
              proxy_pass              http://plex.media.svc.cluster.local:32400;
              proxy_http_version      1.1;
            }
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
      # Separate PVC for cache to avoid backing up cache files
      plex-cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs
      tmp:
        type: emptyDir
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcode
      # transcode:
      #   type: emptyDir
      media:
        type: nfs
        server: nas.rmcd.internal
        path: /mnt/tank/media
        globalMounts:
          - path: /media
            readOnly: true
      recorded:
        type: nfs
        server: nas.rmcd.internal
        path: /mnt/tank/media/Recorded
        globalMounts:
          - path: /media/Recorded
            readOnly: false
      backup:
        enabled: true
        type: nfs
        server: nas.rmcd.internal
        path: /mnt/tank/kubernetes/plex-backup
        globalMounts:
          - path: /backups
            readOnly: false