---

# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

# Define the host as control plane nodes
k3s_control_node: true

# k3s settings for all control-plane nodes
k3s_server:
  # system-default-registry: "{{ system_default_registry }}"
  node-ip: "{{ ansible_host }}"
  tls-san:
    # # kube-vip
    # - "{{ kubevip_address }}"
    # haproxy
    - "{{ k3s_registration_address }}"
  docker: false
  flannel-backend: "none" # This needs to be in quotes
  disable:
    - flannel
    - traefik
    - servicelb
    - metrics-server
    - local-storage
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"

  # Network CIDR to use for pod IPs
  cluster-cidr: "172.17.0.0/16"

  # Network CIDR to use for service IPs
  service-cidr: "10.43.0.0/16"
  
  # Required to monitor component with kube-prometheus-stack
  etcd-expose-metrics: true

  kubelet-arg:
    - "feature-gates=MixedProtocolLBService=true,ReadWriteOncePod=true"
    # Adding to reserve resources for host daemons
    ## - Kubernetes docs state the following but it doesn't work
    # - "system-reserved=[cpu=200m][,][memory=500Mi]"
    - "system-reserved=cpu=200m,memory=500Mi,ephemeral-storage=5Gi"
    - "kube-reserved=cpu=150m,memory=1000Mi,ephemeral-storage=2Gi"
    # - "eviction-hard=memory.avail<500Mi,nodefs.available<10%"
  kube-controller-manager-arg:
    - "feature-gates=MixedProtocolLBService=true,ReadWriteOncePod=true"
    # Required to monitor component with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    - "feature-gates=MixedProtocolLBService=true,ReadWriteOncePod=true"
    # Required to monitor component with kube-prometheus-stack
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "feature-gates=MixedProtocolLBService=true,ReadWriteOncePod=true"
    # - "address=0.0.0.0"
    # Required to monitor component with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  kube-apiserver-arg:
    - "feature-gates=MixedProtocolLBService=true,ReadWriteOncePod=true"
    - "anonymous-auth=true"

  # # TODO: enable with cilium
  # node-taint:
  #   - node.cilium.io/agent-not-ready