apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: lb-pool
spec:
  blockSize: 28
  cidr: 10.44.44.0/28
  ipipMode: Never
  vxlanMode: CrossSubnet
  natOutgoing: true
  disabled: false
  nodeSelector: all()