---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: networking
spec:
  headers:
    sslRedirect: true
    sslHost: "${SECRET_DOMAIN}"
    stsSeconds: 315360000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    frameDeny: true
    customFrameOptionsValue: SAMEORIGIN
    contentTypeNosniff: true
    browserXssFilter: true