---

all:
  children:
    servers:
      children:
        # Master group, do not change the 'master' name
        # hosts should match the filenames in 'host_vars'
        master-nodes:
          hosts:
            k8s-master01:
            k8s-master02:
            k8s-master03:
        # Worker group, do not change the 'worker' name
        # hosts should match the filenames in 'host_vars'
        worker-nodes:
          hosts:
            k8s-worker01:
            k8s-worker02:
