---
all:
  children:
    master:
      hosts:
        k8s-3080-5xn:
          ansible_host: 10.24.0.20
          rook_devices:
          - /dev/nvme0n1
        k8s-3080-1yn:
          ansible_host: 10.24.0.21
          rook_devices:
          - /dev/nvme0n1
        k8s-590-n61:
          ansible_host: 10.24.0.22
          rook_devices:
          - /dev/nvme0n1
      vars:
        ansible_user: ubuntu
    # worker:
    #   hosts:
    #     k8s-w-pve:
    #       ansible_host: 10.24.0.10
    #       rook_devices:
    #       - /dev/vda
    #     k8s-w-pvegpu:
    #       ansible_host: 10.24.0.11
    #       rook_devices:
    #       - /dev/vda
    #     k8s-w-590:
    #       ansible_host: 10.24.0.12
    #       rook_devices:
    #       - /dev/nvme0n1
    #   vars:
    #     ansible_user: ubuntu
    physical:
      hosts:
        k8s-3080-5xn:
          ansible_host: 10.24.0.20
        k8s-3080-1yn:
          ansible_host: 10.24.0.21
        k8s-590-n61:
          ansible_host: 10.24.0.22
      vars:
        ansible_user: ubuntu
    # cloud-init:
    #   hosts:
    #     k8s-w-pve:
    #       ansible_host: 10.24.0.10
    #   vars:
    #     ansible_user: ubuntu
    #     physical:
    #       hosts:
    #       vars:
    #         ansible_user: ubuntu

# router:
#   hosts:
#     gateway:
#       ansible_host: 192.168.1.1
#       ansible_user: root

# storage:
#   hosts:
#     expanse:
#       ansible_host: 192.168.42.50
#       ansible_user: root
