---
all:
  children:
    master:
      children:
        cloud-init:
          hosts:
            k8s-master01:
              ansible_host: 10.24.0.10
            k8s-master02:
              ansible_host: 10.24.0.11
          vars:
            ansible_user: ubuntu
        physical:
          hosts:
            k8s-master03:
              ansible_host: 10.24.0.12
          vars:
            ansible_user: ubuntu
    worker:
      hosts:
        # k8s-worker01:
        #   ansible_host: 10.24.0.20
        #   #rook_devices:
        #   #  - /dev/nvme0n1
        # k8s-worker02:
        #   ansible_host: 10.24.0.21
        #   #rook_devices:
        #   #  - /dev/nvme0n1
      vars:
        ansible_user: ubuntu

# router:
#   hosts:
#     gateway:
#       ansible_host: 192.168.1.1
#       ansible_user: root

# storage:
#   hosts:
#     expanse:
#       ansible_host: 192.168.42.50
#       ansible_user: root
