---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true

  values:
    defaultPodOptions:
      annotations:
        secret.reloader.stakater.com/reload: "home-assistant"
      # # Already privileged, what's the point?
      # securityContext:
      #   runAsUser: 568
      #   runAsGroup: 568
      #   fsGroup: 568
      #   fsGroupChangePolicy: "OnRootMismatch"
      #   supplementalGroups:
      #     - 100

    controllers:
      main:
        strategy: Recreate
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          main:
            securityContext:
              privileged: true

            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.3.0
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
                memory: 350Mi
              limits:
                memory: 750Mi

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${LB_HOME_ASSISTANT_IP}
        ports:
          http:
            port: 8123
          coiot:
            enabled: true
            port: 5683
            protocol: UDP
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
    ingress:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
        globalMounts:
          - path: /config
      backup:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: /mnt/user/k8s-bak/hass-backup
        mountPath: /config/backups
        readOnly: false
