---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: 1.0.54
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: reloader
    fullnameOverride: reloader
    reloader:
      deployment:
        tolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
