---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/weaveworks/kured
      tag: "1.9.2"
    updateStrategy: RollingUpdate
    configuration:
      timeZone: "America/New_York"
      startTime: "2am"
      endTime: "6am"
      drainTimeout: 15m          # timeout after which the drain is aborted
      rebootDays: ["tu,th"]
      # Using --lock-ttl=30m will allow other nodes to take over if TTL has expired (in this case 30min) and continue reboot process.
      lockTtl: 60m               # force clean annotation after this amount of time
      # Using --lock-release-delay=30m will cause nodes to hold the lock for the specified time frame (in this case 30min) before it is released and the reboot process continues. This can be used to throttle reboots across the cluster.
      lockReleaseDelay: 10m      # hold lock after reboot by this duration
      notifyUrl: "${SECRET_KURED_DISCORD_WEBHOOK}"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    metrics:
      create: true
