{
	"data": "ENC[AES256_GCM,data:sJPHqTCeeXSBKIq6ePyP89UOEy3l2ArPASFIvZbsKneEAPbW6kijqFhg8P7nJQ0YLrZMcmLS6/PIQPQVoaUph62yP6jYEblSh8TgaTQZAYpXtKOeCy1dncQ7ugnIlIoB0mRpeQ3ko8bY7QF3RXEEyu00shZYgWeBLrMD2QU3NhnpBtpdYfb/uVONhv0sSnNZDILIvTXuxh8KXxymTQ==,iv:yXZw7WKYzt6b6DBrRAXSVKQv/vsJkZsNKPMrShngZW0=,tag:7o9BPuVUK5+fcmF+q/WPng==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2023-02-16T04:17:47Z",
		"mac": "ENC[AES256_GCM,data:mTYbhJk/p38ONz3KGrH2NHf8JZx3DUCoH/BEQcauLxVtPF7XkiD8AmGRC+MfCEtXNuBhRC+lRYJlukdZVoPqq8jB2mSPwB7YIL5Sx4WjMD7siI2NewavPu81RFJFxSYCF+1ZU6ws4sg+OcWkrw5wVyAYOmM5OdNq6M0pVsknikA=,iv:lc9dstoqA/IRh58wX1QSpRCYN8+05c3nUIFi3cORTPA=,tag:/FimfzS5Lntbbm+I1pqujQ==,type:str]",
		"pgp": [
			{
				"created_at": "2023-02-16T04:17:46Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA59Pualoj6WCARAAtS7jHl1kdJ7iIaYOtKyH1r0HDro0Qzde2mUasjoNCVbs\nNhoQELOew/wXThuayBBompdPjFOdliw9JF5jdZ3fmC/njwKeab5dbhf2fb2MIEVl\nK/LxFwcSoQo9agrpYb52i6cBmEv1PVUjA4oK9VfsClZVD4bajfl6ls82ssgAZJ2u\n1hpEVRZNO2OMJRLUSM2aP6TNX2N/+iY8u7esoM3zqy46rCEi0AZ1UCYfPNuOqy/q\n2w9/KwI/zPsmKdNBu88gjV1Xk1WQ/1mDoWh4tX7LuKUmAej1kf5tJZPqo/bdw0EV\n0wxr903uHni2v47xO+qglA7BHH1AYLs4uxr32aCH0fTBvdXEK6Q+w1r3zyRUg4iO\nDdgumWjAK8FZfIr/C4hE4XSjeUC3ElZYw1eLwS2nbiFCZr3p8DN9Ce6UfkmuJkG+\nc9+9iCf0YCOfJBTFozA2pvYXYJkzJh2/otIQNH8l/2xrkqjfW4+735zdD+m/lWt3\nFTj1GAdJFWOUYpAOjcgZPhFETASjMoN+enqGjzcZZEhfzg2JBWOk/6W74t8Ggcsh\nzHs7rKQ/mXCNvZbYzRBEC5tDEHIDrlMV/JOQYUcdOS2+G4XStUjMg4yKTuO8qolH\neTj10tFeOs2vJjTeIwhrAm/dQX38ji0Rgm6iMyFP7cyceu63/FdklUagiO5JGhbS\nXAGAmmGjZ9Nl4rwE/BaHs3uE+7G8sAd83wJRU/gyUJIm20phs6N70/1YK/jUk4oK\n4wogS9yMMIuy15V+KOc53PtWqyAJlpd2dMsL4erh5NikJOMWXyiUqzxZ73Zd\n=hBVk\n-----END PGP MESSAGE-----\n",
				"fp": "B98EF6FF6F3748661F449D0CA912302389FEB397"
			},
			{
				"created_at": "2023-02-16T04:17:46Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nwcFMA9Qs/eFVrZ++ARAAAaaTRALXz4dj/RSuXraBkuEjjsia1wIZFh9B/hhb8H9n\nbK61FR6ENSrjO1fugfS1ZUHYakr+9EXtQnAPTGXzTc9jOZZpKnLOErekKSgC1kUJ\nH5SmF3gpkiWG9367pLeFJg24W0Vte4qHVkRLQRXiNcp0xy/Rm+mKGa5CpsOHBxv0\nAeur5ureoGL92JawlQCGIMCmAVDNi1ZPhK1FAGOTLzfDlcISNW6iA5o4DmDQsaYo\nxvpfPb4yDdIoELQeqHJf4Z5eyzyWU1YanxBR45WsvkgEl5hTfcLadJ8ji/U0lPNQ\nMjgVR5Wja1pdaheYDu/dNPREkSUNV+s1r6qHgONTQ0RTc9H67PSdMYkiR1ZZgFrl\n/WERjMzlzzDpzNIJgSvriCqPFOWxBROlNcRhlEslBIEKJnmZ5IGAp/7QOg9hfyIQ\nobshLidODMx6ArJnQjE3NK2A6a8L+3eCj1AK5cBZ/rb1IjKSv9sNI7590S1jPOP+\nYqB1U9vw2znUk+Ng4AhTiRuiFJ9UKrs92/p99Bic/lKcQRb4tnVwNywPIiMjSz/y\n0d2UIlb4fu3MNRsBU6QzstIGPaDBiO55j9mJZfek/UDESexWaCK/TMbXaVptB7WW\nj63i2BAwv3u4mdFBVZMVyjNoKuBg/w6TMWjiLXdNnCwdIfpCVOriX6jVj3fGYczS\n5gEXKdPKaVdMBTcVqw3VTDz2eH9nLmRMjySeNtIXPLgt/F2tcg9kyVh+L3HCx20K\nM/rqByN9bi1HcEJeyYFvIBvk81YTdj7ykLVfG8FEMXU0DOIIBXfCAA==\n=sh62\n-----END PGP MESSAGE-----",
				"fp": "95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0"
			}
		],
		"encrypted_regex": "^(data|stringData)$",
		"version": "3.7.1"
	}
}