---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./intel-device-plugins/ks.yaml
  - ./reloader/ks.yaml
components:
  - ../../components/namespace
