---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "secretdomain-tls"
  namespace: networking
spec:
  secretName: "secretdomain-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
