---
apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    istio-injection: enabled
  annotations:
    "cni.projectcalico.org/ipv4pools": "[\"default-ipv4-ippool\"]"