---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 9.6.1
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gitea/gitea
      tag: 1.21.11
    service:
      ssh:
        annotations:
          metallb.universe.tf/allow-shared-ip: traefik
        type: LoadBalancer
        port: 22
        loadBalancerIP: ${LB_GITEA_IP}
        # loadBalancerIP: ${LB_TRAEFIK_IP}
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
      hosts:
        - host: "code.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "code.${SECRET_DOMAIN}"
          secretName: "gitea-tls"
    persistence:
      enabled: true
      mount: true
      create: false
      claimName: gitea-config-v1
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      oauth:
        - name: "keycloak"
          provider: "openidConnect"
          auto-discover-url: "https://id.${DOMAIN_1}/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"
          existingSecret: gitea-oauth-secret
          scopes: "gitea email profile"
          group-claim-name: groups
          admin-group: "/admins"
          skip-local-2fa: "true"
      config:
        server:
          PROTOCOL: http
          DOMAIN: "code.${SECRET_DOMAIN}"
          ROOT_URL: "https://code.${SECRET_DOMAIN}"
          # START_SSH_SERVER: "true"
          SSH_DOMAIN: ssh-code.${SECRET_DOMAIN}
          LFS_START_SERVER: "false"
        actions:
          ENABLED: "true"
        service:
          # Force users to log in to view any page or to use API.
          REQUIRE_SIGNIN_VIEW: "true"
          # Disable registration
          DISABLE_REGISTRATION: "false"
          # ... except via OpenID
          ALLOW_ONLY_EXTERNAL_REGISTRATION: "true"
        openid:
          # Do not allow signin to local users via OpenID
          ENABLE_OPENID_SIGNIN: "false"
          # Allow creation of new users via OpenID
          ENABLE_OPENID_SIGNUP: "true"
        migrations:
          ALLOW_LOCALNETWORKS: "true"
      additionalConfigFromEnvs:
      - name: GITEA__DATABASE__DB_TYPE
        value: postgres
      - name: GITEA__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: SECRET_GITEA_PG_HOST
      - name: GITEA__DATABASE__NAME
        value: gitea
      - name: GITEA__DATABASE__USER
        value: gitea
      - name: GITEA__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: SECRET_GITEA_PG_PASSWORD
      - name: GITEA__DATABASE__SCHEMA
        value: public
      - name: GITEA__CACHE__ADAPTER
        value: redis
      - name: GITEA__CACHE__HOST
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: SECRET_GITEA_REDIS_HOST
      - name: GITEA__SECURITY__SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: SECRET_GITEA_SECRET
      - name: GITEA__QUEUE__TYPE
        value: redis
      - name: GITEA__QUEUE__CONN_STR
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: SECRET_GITEA_REDIS_HOST
      - name: GITEA__SESSION__PROVIDER
        value: redis
      - name: GITEA__SESSION__PROVIDER_config
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: SECRET_GITEA_REDIS_HOST

    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
