apiVersion: v1
data:
    key: ENC[AES256_GCM,data:ViQo6IoCiBlBhIdGY2fJ98VMXB0psYi9ZLV3gxkikB8=,iv:jlfM1Prz4/u+TpNWtbC/SrERSjuNdZZdjSWxfHM3o5I=,tag:FkFCnxbqc0Q2RxavBvo3kw==,type:str]
kind: Secret
metadata:
    name: k10-dr-secret
    namespace: kasten-io
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-28T04:21:14Z"
    mac: ENC[AES256_GCM,data:cd95blmhpKKELF/zWzhH508LrXxMY/g9fLxh6cRWDFof852Jc0BAkOMoYoLFWxT4ZoIdQGIqMZ0hRfWVkwtc1FXeYMmE+rqxX1olTM38AOqY7MSU/Ob7e9xsQpd/NCBlzQW1Gys8z7VA0N30C84+/Er/hiRIVvxVP2SULn3anrY=,iv:cwsJPLPiFKqK8u3Y4TcEazFL7Gw72N/u/TS5QbZWGj0=,tag:jYg2B/wj+mT789gkYPoR7A==,type:str]
    pgp:
        - created_at: "2022-05-28T04:21:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ/9H7f+iVdhMPzWEz1cv/1umvmbelBvQ78E5MtEdJODpiG/
            W2SXPMEe0yQ2mavgfwUqNSF7S4drFSaSVO3sM/sndULzz6tqosDCdDuBBMCIl4NJ
            b4m6eWiuB4FU+g1wT7rY6L6tB0sgX/6zn9XIjHkwTJfj8Y0MY0U98CMXFmPJvyJ4
            n5h8SgEUh2NZGi0mJfuQ6Y/5HYPjfKVNH1gfmxuJnlMvvYj863WZCT3CCMQcfX/g
            1ysEgyrVcBSDynRUmTRrsItFpXyaN9OrofADFm80WZ/0o1oCR3AvCblZVumJ2XC6
            /oCLWu37yf3LKqexLb9uMcHatacDzJL+fc1nlDx+dXHWq/BuSb+1XKe5H3RWXEty
            Y8EKH58K2dnUcq1vkcBss4bSaSNYUkfKn4k+ICEqrmXkFMfGma2geVV0mUEyLE1t
            dQp/hcLUkxNjI8Zx2JoM1sMyp+CXfSbEow9O8K1HECNi+P71oGynpPEclsuTSfJb
            jfM0+NkmP7pyd47J3yNZ+FNLfyFjURxfKR14c7jd8O5P7a141RbHZiDJaz9FVPTV
            dVol5XYqQ3wrcaAOATzlg1VkJct636srmpFuSw8ydyezvo6Ksvur5HDP3pfb2sjl
            1PH/biJZPw1h/JwUwOdJ2Vc6fNjtXang8zs0FNNxaQSsgNjUfU2VV90MuusKs4TS
            XgHZKO257S5QCIVOQeawMKGVAjcyBlK3X1Slm1eh6uV5xXDknixoKX+lsjWPKJWG
            0nNFCr6bX7sJvRzU1HI60UZy1HblgKV5KXh34qUZf0FinH4MqrD+txiWbmwP+2E=
            =ou8z
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2022-05-28T04:21:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAYImiJOKrFI1PoYdXw4JnVUl+wOrijVICyWYpQeRTQE6B
            F7JVXEmgQ7f7i6f7D6+zvAWY9RjdNyBwcb5EVKNUF3FYsqGQYwyIs+wkFrATB0KX
            dTtko8yUiHoepAkiGpfp5BhKpw8LoigHTn6jK3DPNDNHipKsT4MXtU0uyNC0KJLX
            fCuMpC+eaE0xgc9adQDjgoCPgYMFNCEXyuMTLvgd8/MLsYMOVpIkG3AQPfX55SgH
            /6PIYYQkLTZSjniW1NCwn67iZnEtqYvN9Pa2dH1Tf6fZsnYeNNTjQGV5UlpUgA6O
            m1rs5Lilan6FZjdW/YaWmVTqfqjyVo7CJ1PaTVx7B8F+KQ1SJD1nuq2qWlyIMjWW
            1cQc1S/gAmRlRgvPXBSQKi9b1rQw0JvbyQTTN5LmLztWOvH/U+Y7M1A1BbKDOJTo
            vWB2uqC8hYd4wTTvHn5vXF9X5Y+Z11gsagD1/T7f5QfEiek3Jngxlbp0Z6XgvMMP
            3yFOU8ReTBzBs5l+tkOuZHD0k60CvHrb8KRD2Elv8CqQ+HfSaYxex0AypyLjSgqR
            P8Tyb+m0w9YPdnpFjRsGQzTCCrtTOa1+FY7qhTrgF3hGiFuz14kXj8+giGdMDUyL
            pjBHJXwU2FOaeEXl2pI3gGlva6BX+EOUsSqsLYycQH3NUCxZEUPlAXcVhFdVdkTS
            5gFMIkUWwij3h/nDP+bKf6Ev5FIG/dtSMwOKVLXdEibxmAuDR2vp4laRJsCLOpow
            fbsBKQZrZb9x7BesE4VWXMrkZJ9aUwlG1GrOuuDMAQku5OKWeGkhAA==
            =OLoC
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
