---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant-code
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: home-assistant
      namespace: home
  values:
    image:
      repository: ghcr.io/coder/code-server
      tag: 4.7.1
    env:
      TZ: "${TIMEZONE}"
    args:
      - --auth
      - "none"
      - --user-data-dir
      - "/config/.vscode"
      - --extensions-dir
      - "/config/.vscode"
      - --port
      - "8080"
      - "/config"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host-config "hass-config.${DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host-config
            secretName: "hass-config-${DOMAIN_2/./-}-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: ["home-assistant"]
                - key: app.kubernetes.io/instance
                  operator: In
                  values: ["home-assistant"]
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
