---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
  values:
    defaultPodOptions:
      annotations:
        secret.reloader.stakater.com/reload: mosquitto
    controllers:
      main:
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.18
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/secret/* /mosquitto/external_config/ && mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd && chmod 600 /mosquitto/external_config/mosquitto_pwd"
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.18
            env:
              TZ: "${TIMEZONE}"
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 500Mi
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${LB_MOSQUITTO_IP}
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
            primary: false
          mqtt:
            enabled: true
            port: 1883
            primary: true
          mqtts:
            enabled: true
            port: 8883

    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
        type: persistentVolumeClaim
        globalMounts:
          - path: /mosquitto/data
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        advancedMounts:
          main:
            main:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
                readOnly: true
      configinc:
        enabled: true
        type: secret
        name: mosquitto
        advancedMounts:
          main:
            init-config:
              - path: /tmp/secret
      mosquitto-tls:
        enabled: true
        type: secret
        name: mqtt-${DOMAIN_2/./-}-tls
        globalMounts:
          - path: /etc/ssl/mosquitto
            readOnly: true
      mosquitto-externalconfig:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config