---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: eclipse-mosquitto
      tag: "2.0.18"
    env:
      TZ: "America/New_York"
    service:
      main:
        ports:
          http:
            enabled: false
            primary: false
          mqtt:
            enabled: true
            port: 1883
            primary: true
          mqtts:
            enabled: true
            port: 8883
        type: LoadBalancer
        loadBalancerIP: ${LB_MOSQUITTO_IP}
        externalTrafficPolicy: Local
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
        mountPath: /mosquitto/data
      config:
        enabled: true
        type: custom
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
        volumeSpec:
          configMap:
            name: mosquitto-config
      configinc:
        enabled: true
        type: custom
        mountPath: /mosquitto/configinc
        volumeSpec:
          secret:
            secretName: mosquitto
      mosquitto-tls:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mqtt-${DOMAIN_2/./-}-tls
        mountPath: /etc/ssl/mosquitto
        readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 500Mi
