---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-cert
  namespace: home
spec:
  secretName: mqtt-${DOMAIN_2/./-}-tls
  privateKey:
    rotationPolicy: Always
    size: 4096
    algorithm: RSA
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - mqtt.${DOMAIN_2}
