---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster
  namespace: staging-vcluster
spec:
  interval: 15m
  chart:
    spec:
      chart: vcluster
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: loft-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    vcluster:
      image: rancher/k3s:v1.26.1-k3s1

    sync:
      nodes:
        enabled: true
        syncAllNodes: true
      ingresses:
        enabled: true

    # Enable HA mode
    enableHA: true
    # Scale up syncer replicas
    syncer:
      replicas: 3
      extraArgs:
        - --tls-san=staging-vcluster.${DOMAIN_2}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    # Scale up etcd
    etcd:
      replicas: 3
      fsGroup: 12345
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    # Scale up controller manager
    controller:
      replicas: 3
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    # Scale up api server
    api:
      replicas: 3
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    # Scale up DNS server
    coredns:
      replicas: 1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 12345
        runAsNonRoot: true
        runAsUser: 12345
        seccompProfile:
          type: RuntimeDefault

    isolation:
      enabled: true

      podSecurityStandard: baseline

      resourceQuota:
        enabled: true
        quota:
          requests.cpu: 10
          requests.memory: 20Gi
          requests.storage: "100Gi"
          requests.ephemeral-storage: "200Gi"
          limits.cpu: 20
          limits.memory: 40Gi
          limits.ephemeral-storage: "200Gi"
          services.nodeports: 20
          services.loadbalancers: 2
          count/endpoints: 40
          count/pods: 30
          count/services: 40
          count/secrets: 100
          count/configmaps: 100
          count/persistentvolumeclaims: 20
        scopeSelector:
          matchExpressions:
        scopes:

      limitRange:
        enabled: true
        default:
          ephemeral-storage: 2Gi
          memory: 512Mi
          cpu: "300m"
        defaultRequest:
          ephemeral-storage: 1Gi
          memory: 128Mi
          cpu: 100m

      networkPolicy:
        enabled: true
        outgoingConnections:
          ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 100.64.0.0/10
              - 127.0.0.0/8
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16

    # service:
    #   type: LoadBalancer
    #   loadBalancerIP: ${LB_VCLUSTER_IP}
    ingress:
      enabled: false

    # securityContext:
    #   runAsUser: 12345
    #   runAsNonRoot: true
