---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    createNamespace: true
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system
    - name: node-feature-discovery
      namespace: kube-system

  values:

    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/custom-intel-gpu
                    operator: In
                    values:
                      - "true"
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 44
          - 109
          - 100
          - 65539

    controllers:
      main:
        replicas: 1
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/jellyfin
              tag: 10.8.11@sha256:acb5ea8fa8c9f3b893e870cefe539629af9e33ff84a7bcf1283a094883d2b7ff
            env:
              TZ: "${TIMEZONE}"
              JELLYFIN_CACHE_DIR: "/config/cache"
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
                gpu.intel.com/i915: 1
              limits:
                memory: 4000Mi
                gpu.intel.com/i915: 1

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${LB_JELLYFIN_IP}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
        globalMounts:
          - path: /config
      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: /mnt/user/Media
        globalMounts:
          - path: /media-nas
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcode
      #   medium: Memory
