apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vpa
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    recommender:
      enabled: true
      image:
        repository: k8s.gcr.io/autoscaling/vpa-recommender
        tag: 0.13.0
      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
        prometheus-address: |-
          http://thanos-query.monitoring.svc.cluster.local:9090
    updater:
      enabled: false
    admissionController:
      enabled: false
