---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.30.0
      sourceRef:
        kind: HelmRepository
        name: calico-charts
        namespace: flux-system

  install:
    crds: Create
    remediation: # perform remediation when helm install fails
      retries: 5

  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true

  values:
    # Configures general installation parameters for Calico. Schema is based
    # on the operator.tigera.io/Installation API documented
    # here: https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
    installation:
      enabled: true
      registry: quay.io
      imagePath: calico
      # Configures Calico networking.
      calicoNetwork:
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
          - blockSize: 26
            cidr: 172.17.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
          # # Created by apps/networking/calico/lb-pool
          # - blockSize: 29
          #   cidr: 10.44.44.0/29
          #   encapsulation: VXLANCrossSubnet
          #   natOutgoing: Enabled
          #   nodeSelector: all()
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093

    resources:
      requests:
        cpu: 100m
        memory: 120Mi
