---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 4.5.12
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    services:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    eula:
      accept: true
      company: Ryan-McD
      email: Ryan-McD@users.noreply.github.com
    global:
      persistence:
        storageClass: ceph-block
    auth:
      tokenAuth:
        enabled: true
    clusterName: k8s
    ingress:
      create: true
      urlPath: k10
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      host: "k10.${DOMAIN_2}"
      hosts:
        - "k10.${DOMAIN_2}"
      tls:
        enabled: true
        secretName: "k10-${DOMAIN_2/./-}-tls"
    grafana:
      enabled: false
    prometheus:
      server:
        persistentVolume:
          enabled: true
          size: 15Gi #30Gi
        retention: "15d" #"30d"
    # injectKanisterSidecar:
    #   enabled: false
    #   namespaceSelector: {}
    genericVolumeSnapshot:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi