# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gitea-oauth-secret
    namespace: development
stringData:
    key: ENC[AES256_GCM,data:sOc+b4s=,iv:8jUyeqMHor6dnvupqI37hmV0HsVk+pAxqYGKvju+frk=,tag:QAOZl9jOSvDiEA4apBdzog==,type:str]
    secret: ENC[AES256_GCM,data:VWPIPIa1si+M8zOHG2SUVO/cEFGezKkNbkKC6+seaQ4=,iv:Vae6o94VfHMqXSWsnbwvdo4Ik0r1kUdX4EdFgrvccJY=,tag:1+hu/s0YFzzq9dXLvprTtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-10-08T01:42:53Z"
          enc: vault:v1:xnInW8NHmAd9fmL6AwIzaBjQSaJjoV3RO+ZC+Eh3wZjnGh2eJszPlKLi5w3+f+WUI8l1D0aqt9/d0X+l
    age:
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d1ExRytpRmFINEsyeENk
            b0VNUUFnNDRRTXVFTkpIWnVvRUtRUkkxWVdRCldyVU9OaXY0NXI4SkV2R1ZtU2VF
            UEdTbFI5QVMvdE9ZdGZmbFJjSDhySFUKLS0tIERSbnhoRUIxdkNCWitpTU55clBh
            d3p3V0picXJlMFk2MEJPVURJaUZTVUEKkAcz0BOYyYJdN1+9j3dQOtgczOFCT59c
            mNJx142zj4cvNAqfOd6VgggRcRwCfxgbFWnq4uGT8lz+VuA3GZuWcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfmjgyxfv09xc7kvy0895wekpcqarywaeeuxs7cy0n37zs77tejs9z40a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKakRPOU4xTVJad3U3dmxD
            OWdrczd0K040VjFuRjVSNGswR1NZOUY3TWdrCjNzTDhvNnpDT1pYcUg2Y1pQM3F1
            SWowQ0RHd0pKNm5DQVdLdnoxaGxyd1EKLS0tIGFMRjBqVU9TZW5qSk02dUx4Uld5
            TnA0M09JYzlFc084V2ltbHFPb2t1TTAKd+W7FSpH3kGal5B/sRyvOdRPNty4Ir9V
            VJO5YPzDOGghv+/g+Hwq5VhlppJgDchBO8FEr1sRpFrr8l0P6GE/bQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a6zmnhmgqf2u6a4c0hwjelf8zcr9azv0fmkz45dmsxljljd9mpescf070l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVlA4NzZLMU92QTBtQnFs
            SGx4UWdTOG1NZkFScDgvcjNMaUFrd2I0em5FCkloQ1V1M2FaT1lkS0xKbHlDTlBr
            S1h3b1VCSisrQWZJMGYxNmE0a1ZxRVEKLS0tIGpzamFENkhySXBteXhsOERPQWY4
            QzEyMUkwWVZzc1FwcXVubmh1OFU3SWsKTnKXHRF/9lYUc/U8ik7k/64l5j3Ky1Qj
            QBWsMmloqGpXPUk998Z1v5ArAt0l+uGNIFalc+IiffDB9lwSqnfEng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T01:42:54Z"
    mac: ENC[AES256_GCM,data:TyNBoDpif+v1aS45wgj5bzLCjK4fqyffi1Tnf1FcMGurHCsUsca2Gye8+4Xzi1UNbwLcGWoCxi/k1EHokNj5nDDWG6HJkuT/moU5YbUerqym4aajUv4SVFuyALHQJaMrKbx/lr98uUb7e6MECCQJCXjYjejwYBG0Zhzny3Y/QFA=,iv:T0jY6Gi0wJMuvdUZcuPbEGgkMC0ZqJLtRkxQTS51Z3M=,tag:VqDHM8nyBWnpTX+5hdQ2Ow==,type:str]
    pgp:
        - created_at: "2023-10-08T01:42:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//ZU8VgQmietrkPQxLf/l+j7KHzO4FDZZKLEm1B2zUmhlz
            q+4s5Ymn4A4iIL4kdXRZc7Z5+0JzGQ+CsxxK1g5nygkQFBIMbvZDV0YF91aOjDTI
            e/7BIEymrdZx5BhHYLNfs1et5xENHqBxLZDx7KgSN4d104bkHoXBYsm8Kj/5ob4J
            pqvrqQnXgbBeMkM8QL3/LdxG162PBSNeFVYPvI36GNiimp8pCb8txBoR9kFfhOyE
            cSSDWNPG3QWcQtlXB4etWuiKd+na4bAVbzEHprQhQ1MzUh53UdK9ACLgZRyNnCz8
            Znw+w4nM7PDD1sGrf8vMvsUoGfGdsE6Q0PxDoRyM1K37PHzGAZ+rICXQk5jog6bw
            AKlwQMVzpR36gGDSs256ito8PLBBEXluhr0DddVJ9eglZIX8F2OsHJLxPNirsewm
            ToPrueBGmQ/gNJsqr/ABo3QZUOWhNfLwKv5C1fAq0I4CHZuXjk6h0RzpUvUKKU80
            fHw7O3Qut40+sFDJ9PI/FDVyn+E8DBFvfid82ak6bQmONgomAsWSleuNCK4IjYKz
            927qSxZd7rhLOMsNdAwLVzFmvCrXcR9RzW1McvLi1cuJRrHmXFPsokAbBsOxe8d9
            D9s16Ff3Cfq44rG5F7j08fog/tscx5dJZ5xN1XCwIfptJckdihZ6/ARXwSqk90fS
            XgEiR6U9W+OYW6gW8zH8GxA5nd4b0b3woeH5lGZUlNeWJKIyUSi5bTax6/HqOn1b
            4tCMC+Mkqm7MoB8fyFe/eD+uh7mxY7G9xLX9NvZp3Oz9zTc9d8QIaZXearAnOj4=
            =3QKN
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-10-08T01:42:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAAw2iTA3QJncEyQ3CajtRT3de7dGbIlwwJY8pRRgXybEQT
            6hF144fhjNeR2uKBXXXRU1LfADEiUnDixPBpmG8QFxFo+vEB1adZ8KD22f+ExWUc
            Zq+aN+KbrxpWRdVPLbwtLMqnNEVCJsbujkEZkyUio3i9ncKTAWhWTEwtvGXRpTVT
            KecxktIv2rtsADvHPCiCUFEuKzDFe0J+MOdCaDFY+GGLdJA4vhcqn49dqNbeQ2Pk
            iNchs4ttkxMPiZ1xVZqC0bSBrSoNJhP1RxvizbmfxZ2PWpnz6jQn2UOJae+6BcRF
            b0HhneURp+oTLLn8uYjsmtIZys33q9FvCY4gBaV5lf4GdrDcvdbNURGaFX+T4wAb
            SyXD+tpSeUMx2Lzl0RNPbZt/hqg3Rh3aoVfwSqUWZJmIWQgpG6p+uvDQSj6ch40i
            LlAhN/IVjL6sRzlv/6g0oHIqa9Zv1cA/s0X9vSuQVglQJZJRmOOPjblQNDQ+iSBy
            x9gvmVusfOaS8iI9EZTMv0CxG+AHLOQnvovWzHlLx6I++O+hx1/s1ztofvI9vP2N
            cswFvfSwQe6x25eNDgw4lfXfy47Em2Sm55WzrYnJZFTD0AIlutW+EGdQC16son2p
            L6yI0hhmCRXn4DVqSa+YDbmWxbT0K/gDCAO/42T23cjEGUmrvhsp22IMWhZ3/KHS
            XgGmxA92QqD2RNWrLtB6m1comyzcI2SrZkZV6mZOlnQzyDkT0Ec/F4ZPrKXG+rr9
            Z386sslQXhJukvb2gOOx/qucV9rqi8yYV2za+iNpwofELMkCsquD58teiJvm4DQ=
            =MXyh
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
        - created_at: "2023-10-08T01:42:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ//d/9io9tP9xdc0NZ+usEPTGv07UmaeFtlG9ukQdyqdnqq
            4ZuA989ty4s/+Ao50TTNeYy7PoV834TExIohEpHqtRKCCWqI1rTrqdwM7Z31kH27
            Gv8q5E7P49IMJ+jhtHqKBT0oz3fYMzVcdslfErFwJxx7A4I8ftpno6wnTgkdEZUU
            T1Gx1zECpdRZb/8C6JjkFXcVJ8nTJoHIqQElUT6uU2mDNJ57D+G5TfdqOAvY3pNK
            qoXAYBcTtMKmY1zeWzzrUkerGUcyPJo/ovn2G+KHmNtgCk8Pz5pGgk9eSP4wwBJ3
            ZYZ+0327kYhUEBD3cfVVsIUEuc0MfVQV/p2Ovnd9FGWA/2VfZQEwAvUiYASnaG/1
            emVf7bHhxtME2RQ/7IrY4hzPwE/h+xptdeGxtlQiieHjnw8O4KIJmtRJh36KB5Yf
            2uK3sfBZDoUHlSdc39ThIXqMcw1YwhXFrQ/KXSmCjmvgXml7KoUahtGQMYZKvq2M
            jEKy/WCbHpxv1psT/jDQ+AFSE0Y7EHs0vSATt331Eoq5Zu4ohkb/r5EOHw8KzQvP
            WipIpltro4ixQeUfzk/9Jxniwrf6qiUnx/vWZEmHQqgIonXQu8vewCUvqQ14E5qd
            8ug7ESSR58m/JZ2gHK0ybKtjTNShfFdmRlgng1EtwdKLDXtv4dteMz6Cqa6fMf7S
            XgGvqh4w4v32ZQCZZkhkAvICzqZ2431EDuU0o7uoQniJnfKVMFWioQRGMDLgeBBl
            UNvGBWsUfawQjs/7yWrD3jOKjgXVxcDYF3kMLDVi3A7pyXJYE2bEZk3U1d6M5d4=
            =cwEc
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
