---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gitea/gitea
      tag: 1.19.1
    service:
      ssh:
        annotations:
          metallb.universe.tf/allow-shared-ip: traefik
        type: LoadBalancer
        port: 22
        loadBalancerIP: ${LB_GITEA_IP}
        # loadBalancerIP: ${LB_TRAEFIK_IP}
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
      hosts:
        - host: "code.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "code.${SECRET_DOMAIN}"
          secretName: "gitea-tls"
    persistence:
      enabled: true
      existingClaim: gitea-config-v1
    gitea:
      admin:
        #existingSecret: gitea-admin-secret
        username: ${SECRET_GITEA_ADM_USER}
        password: ${SECRET_GITEA_ADM_PASS}
        email: "${SECRET_GITEA_ADM_EMAIL}"
      oauth:
        - name: "keycloak"
          provider: "openidConnect"
          auto-discover-url: "https://id.${DOMAIN_1}/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"
          existingSecret: gitea-oauth-secret
          scopes: "gitea email profile"
          group-claim-name: groups
          admin-group: "/admins"
          skip-local-2fa: "true"
      config:
        server:
          PROTOCOL: http
          DOMAIN: "code.${SECRET_DOMAIN}"
          ROOT_URL: "https://code.${SECRET_DOMAIN}"
          # START_SSH_SERVER: "true"
          SSH_DOMAIN: ssh-code.${SECRET_DOMAIN}
          LFS_START_SERVER: "true"
          LFS_JWT_SECRET: ${SECRET_GITEA_LFS_JWT}
        database:
          DB_TYPE: postgres
          HOST: ${POSTGRESQL_ADDRESS}:5432
          NAME: gitea
          USER: gitea
          PASSWD: ${SECRET_GITEA_PG_PASSWORD}
          SCHEMA: public
        service:
          # Force users to log in to view any page or to use API.
          REQUIRE_SIGNIN_VIEW: "true"
          # Disable registration
          DISABLE_REGISTRATION: "false"
          # ... except via OpenID
          ALLOW_ONLY_EXTERNAL_REGISTRATION: "true"
        openid:
          # Do not allow signin to local users via OpenID
          ENABLE_OPENID_SIGNIN: "false"
          # Allow creation of new users via OpenID
          ENABLE_OPENID_SIGNUP: "true"
        security:
          SECRET_KEY: "${SECRET_GITEA_SECRET}"
        migrations:
          ALLOW_LOCALNETWORKS: "true"

    postgresql:
      enabled: false
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
