---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app gitea-redis
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        name: bjw-s-helm-charts
        kind: HelmRepository
        namespace: flux-system
      interval: 5m
  values:
    global:
      fullnameOverride: *app
      labels:
        app: *app
    podLabels:
      app: *app
    automountServiceAccountToken: false
    controller:
      type: deployment
      replicas: 1
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 7.0.11-bullseye
    command:
      - sh
    args:
      - -c
      - >-
        redis-server --requirepass $REDIS_PASSWORD
    env:
      REDIS_PORT: "6379"
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: SECRET_GITEA_REDIS_PASSWORD
    service:
      main:
        ports:
          http:
            enabled: false
            primary: false
          tcp-redis:
            enabled: true
            port: 6379
            primary: true
    resources:
      requests:
        cpu: 10m
        memory: 204Mi
      limits:
        memory: 512Mi