# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:mqx8MQeV6w54fDAG44SrXEP9G4meemOSRCo1rjQk/qRv/zBIpYxQ4oWPw9GLLvq4vrmyolz1OWVEr4kXKkCOoBRrlAVK9F21J3SvNVG+MkWNM4eTLd8YQ0v8lPgnEZ2IRjiiPQBS9WchfjtDxyfceZHTxMeMy5MTzE6OLoITdjzQJ+qT6m/RSMDR06/5zY/ZlYuhVTEdoh8fxa3JFUZOi8prljnxSOUwJ63mxpb2fu34tIojBCEo6Tp7niUZM2znyFsEqIft,iv:GtOKwt9t1SmuGBnU2qMIOUt7mc++d0eq9ZnaSeA3Dew=,tag:ISTRI/fsU6CWZ7Rra19RYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-17T01:49:27Z"
    mac: ENC[AES256_GCM,data:KVZFtbUKfGDNnTJrCjF1slZiZuh03fbVUkS6pa6y8s0iEyIK/AYktf1aQr/ztRTwOr5hOgtvvlo7nSMCOlj8tNv5Ii+aOYdrftcisy9T0uhPeEVLB9OeP0SOY+kGaacx91xkFVgpMvIb+dSVSbYnWT7cQW5q4COPdqdzHk6pAtM=,iv:Nk2EZ4/gJtUdbbCOYwsCvMh+zOhHhDMsyONkj2oI9o4=,tag:dbw2oHDHqVhe6m0nD8S8RA==,type:str]
    pgp:
        - created_at: "2021-10-17T01:49:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCARAAg6x/8ZO6J0PpkoJNwMjgH+756wWuBjtDGwsuWyOd4UUl
            NrZ+jNOoU9uUgH1rLjydMyZXX+7uMSkxal/2w80UcIDFE/DM3u2BOl8QmrfqI2eh
            8rhSd/v1phVrAJovJKgJAcOdqo+okMyhAj974XlgcB4eGs7wQr7yb7zuyhvDkmKK
            QkuO7VxAJIwcKTsFmwXsmEe1K9k3KI6RmeJSQnjskz+QFJnUhD0t8NYVfGyVxX4g
            IO7SOxUo7xri191RSxMbESRb7h6F07NvWxly9TLblP38OtIHFIbeVfu9PImndIXJ
            bl2P+86/EJI83flRJHhVxcOXrR9cpXveEllWPGioE7vh7SdakvDkz9c3Jiqe9JfJ
            ddcSTkWzGPbwwzU3yu5HBADo5QagJUADSY7v6zuk1Oc+Dbh9R+kA9cVGGziTycuY
            Z2L87kkDHHGmINs/p+Z1/pJUAGUxN+L1tYxa7BE5NBMQhINShcxvML5kwZa2OKW6
            6huPvFg0gW3Qj3C8d9NdC5rJcDvLnOwaBkW577bX4/YYoYRVtZOcqvP/3zYb8t6R
            8vDR+nk7e8ZNZpBpa0yilQsg0vg1Iif1p9w5+L0/MHluhZuR4dldCx7wGbAezVJv
            UceCcxxgKqrXZoxEgR3j2eJrGt5fTGwmeNdOPTkR+WiNuXy1ATuAbvHT7rXlxaTS
            XgGbiWpP7eGv53Nm1mi6cJ2/3zz3IzP1MBToStUYJ2S63ag4D5jNjkGmp8BZZ1Sy
            zlP0kW1FaSdF2Qg6ABD9xtNx9EVpRO7EayXIE2N8vrxxARrvT2iHVuuk6vQ9ULs=
            =fLIe
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2021-10-17T01:49:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAV8C38cxAITdaU2F36yhGAuv8xFvoKNHjKU0tWfurBuUm
            xV6t59Cr04ORlCOB9zSORmljwinBjp0YCvVBsN61cjqJLYPrhWarWr6W6So/jULG
            0K4TiY/D/h6/9RiNUfmSh2LHUKEsp9ibpL48wjAEghShlRRrgrbkZd8GlIfNDkEd
            FEYE30g2q1lBPd+N1AwlsNZutrhQ9+Y7BjJIQ5Ii3gSjnzmlThbeH7dCK9n2DVqS
            1FedVdYKfRSG/zlR5yNLKtJ0FvujBVJufC4CJD2OzxIn+0K9zg+ClHqAq58MOcZq
            DhSx3McH4uVZFOqSjWuyP0GGUOl3jQV4juu3W3OIptRgzu/wk5+rqwqraT70aAKA
            YTrbOPF0/VFZk9FIJ5T2WPfNEKRQurddDHwBvPjStEuBF8CCQTM47yJ+EolnzAQB
            lszZ/ngMiGFKYYeQcjZIkb6AQ3GYsc7QAx67XxCpU10QhDcBXuUWymaFcijrLWB2
            BkVATQdfN/RUJClCIEnXDotLzkbIjn2xKJJc8XW1G2EvvcWtGMTXvI2n4d7l2uQq
            OOS/uY6bfb4smWflVxUppj231jB3PFD8AgDMcx8CHnKUkxlL7MPdOB8iGL0QV1T5
            mU+g515N0ra69j+qsClgknh4/NJ5jggWPCA6HcZ7fHLpfBEfzl3yhXgrq7ZvRp3S
            5gF7kbkyRI+94gYUF6jNbyZErpINYdjCaIiNv68B31XsO0vVKkGocpuh8NrWcgX2
            3Nfi/hUZzyoBf7eAMIT99EzkopJG/KDC+LuvWwSjm2FbPOLmeJxgAA==
            =Mh+t
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
