---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Labeler"

on:
  workflow_dispatch:
  pull_request_target:
    branches: ["main"]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@f1a63e87db0c6baf19c5713083f8d00d789ca184 # v6.0.0
        with:
          configuration-path: .github/labeler.yaml
