---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: neuvector-core
  namespace: neuvector
spec:
  interval: 15m
  chart:
    spec:
      chart: core
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: neuvector-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    openshift: false

    registry: "docker.io"

    psp: false
    rbac: true
    serviceAccount: default

    controller:
      enabled: true
      replicas: 1
      disruptionbudget: 1
      strategy: 
        type: Recreate
        rollingUpdate: null

      
      pvc:
        enabled: true
        existingClaim: false
        accessModes:
          - ReadWriteOnce
        capacity: 1Gi
      ingress: # for rest API
        enabled: false

      resources:
        requests:
          cpu: 10m
          memory: 440Mi
    
    enforcer:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 150Mi
    manager:
      enabled: true
      env:
        ssl: false
      svc:
        type: ClusterIP
      route:
        enabled: false
      ingress:
        enabled: false
        host: &host "neuvector.${DOMAIN_2}"
        ingressClassName: "traefik"
        path: "/"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        tls:
          - hosts:
              - *host
            secretName: "neuvector-${DOMAIN_2/./-}-tls"
        # host:  # MUST be set, if ingress is enabled
        # ingressClassName: ""
        # path: "/"
        # annotations:
        #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        #   # kubernetes.io/ingress.class: my-nginx
        #   # nginx.ingress.kubernetes.io/whitelist-source-range: "1.1.1.1"
        #   # nginx.ingress.kubernetes.io/rewrite-target: /
        #   # nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
        #   # only for end-to-end tls conf - ingress-nginx accepts backend self-signed cert
        # tls: false
        # secretName:  # my-tls-secret
      resources:
        requests:
          cpu: 10m
          memory: 500Mi
      runAsUser: 5454
    cve:
      updater:
        enabled: true
        secure: false
        podAnnotations:
          sidecar.istio.io/inject: "false"
        image:
          tag: "5"
        schedule: "0 0 * * *"
        runAsUser: 5454
      scanner:
        replicas: 1
        image:
          tag: "5"
        runAsUser: 5454
        resources:
          requests:
            cpu: 10m
            memory: 400Mi
          limits:
            cpu: 1500m
            memory: 1500Mi

    # ??
    # docker:
    #   path: /var/run/docker.sock

    resources:
      # limits:
      #   cpu: 400m
      #   memory: 2792Mi
      requests:
        cpu: 10m
        memory: 500Mi

    k3s:
      enabled: true
      runtimePath: /run/k3s/containerd/containerd.sock

    admissionwebhook:
      type: ClusterIP

    crdwebhook:
      enabled: false #disabled due to crd chart

  # postRenderers:
  #   - kustomize:
  #       patchesJson6902:
  #         - target:
  #             version: v1
  #             kind: Deployment
  #             name: neuvector-controller-pod
  #           patch:
  #             - op: replace
  #               path: /spec/strategy
  #               value: { type: Recreate }
