---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.9.8
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  dependsOn:
    # TODO(rook-ceph): Rename dependency to rook-ceph-operator
    - name: rook-ceph
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: "traefik"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        host:
          name: "rook.${DOMAIN_2}"
          path: "/"
        tls:
          - hosts:
              - "rook.${DOMAIN_2}"
            secretName: "rook-${DOMAIN_2/./-}-tls"
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v17.2.1
      # TODO(rook-ceph): Enable host network on next rebuild
      # network:
      #   provider: host
      # TODO(rook-ceph): Enable compression on next rebuild
      # connections:
      #   compression:
      #     enabled: true
      crashCollector:
        disable: false
      mgr:
        count: 2
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "k8s-w-pve"
            devices:
              - name: "vda"
          - name: "k8s-w-pvegpu"
            devices:
              - name: "vda"
          - name: "k8s-w-590"
            devices:
              - name: "nvme0n1"
      resources:
        mgr:
          requests:
            # cpu: "500m"
            # memory: "512Mi"
            cpu: "200m"
            memory: "100Mi"
        mgr-sidecar:
          requests:
            # cpu: "100m"
            cpu: "50m"
            memory: "40Mi"
          limits:
            cpu: "1"
        mon:
          requests:
            # cpu: "1000m"
            # memory: "1Gi"
            cpu: "100m"
            memory: "256Mi"
        osd:
          requests:
            # cpu: "1000m"
            # memory: "4Gi"
            cpu: "300m"
            memory: "1Gi"
        prepareosd:
          requests:
            # cpu: "500m"
            cpu: "100m"
            memory: "128Mi"
        crashcollector:
          requests:
            # cpu: "100m"
            cpu: "50m"
            memory: "60Mi"
        logcollector:
          requests:
            cpu: "100m"
            memory: "100Mi"
        cleanup:
          requests:
            cpu: "500m"
            memory: "100Mi"
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-rbdplugin-snapclass
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems: []
    cephObjectStores: []
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: monitoring.coreos.com
              kind: PrometheusRule
              name: prometheus-ceph-rules
              version: v1
            patch:
              # remove CephNodeInconsistentMTU
              - op: remove
                path: /spec/groups/6/rules/4
              # alert on nic packet errors and drops rates > 1% packets/s
              - op: remove
                path: /spec/groups/6/rules/2
              - op: remove
                path: /spec/groups/6/rules/1
